In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sys
import os

project_root = os.path.dirname(os.path.abspath(''))
if project_root not in sys.path:
    sys.path.append(project_root)

from FEATURES.features import *
from PROPS_EV.calculateEVS import *
from BACKTEST.backtest import *
from MODELS.pipeline import *
# from DATA.TOOLS.fetchPlayersStatsV2 import *
from DATA.TOOLS.fetchPlayersStats import *
from DATA.TOOLS.fetchTeamStats import *
from DATA.TOOLS.playerPositions import *

In [2]:
pd.set_option('display.max_columns', None)
    
s19_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S19.csv')
s20_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S20.csv')
s21_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S21.csv')
s22_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S22.csv')
s23_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S23.csv')
s24_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S24.csv')
s25_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S25.csv')
s26_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S26.csv')

df = pd.concat([s19_regular, s20_regular, s21_regular, s22_regular, s23_regular, s24_regular, s25_regular])
df.tail()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_NAME,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,whos_favored,spread,total,team_is_favored,team_spread,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,GP,AGE,FREQ_FG3,FG3M_main,FG3A_main,FG3_PCT_main,NS_FG3_PCT,PLUS_MINUS_FG3,FREQ_FG2,FG2M,FG2A,FG2_PCT,NS_FG2_PCT,PLUS_MINUS_FG2,FREQ_LT_06,FGM_LT_06,FGA_LT_06,LT_06_PCT,NS_LT_06_PCT,PLUS_MINUS_LT_06,FREQ_LT_10,FGM_LT_10,FGA_LT_10,LT_10_PCT,NS_LT_10_PCT,PLUS_MINUS_LT_10,FREQ_GT_15,FGM_GT_15,FGA_GT_15,GT_15_PCT,NS_GT_15_PCT,PLUS_MINUS_GT_15,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,Unnamed: 0.4,Unnamed: 0.3,TEAM_SEASON_ID_x,OPP_BLOWOUT_RISK,OPP_TOV_x,OPP_TOV_y
26301,26301.0,26301,26301,Amir Coffey,1629599,LAC @ GSW,LAC,1610612746,GSW,0,22401198,2025-04-13,W,0,0,1,0,0,NaN,0,0,NaN,0,0,NaN,0,1,0,0,1,-13,0.2,0.000,NaN,NaN,NaN,NaN,11.3,NaN,191.3,-163.9,0.000,0.500,0.167,0.000,0.000,0.0,0.100,0.000,102.32,107.37,-0.083,9.0,89.47,0.113,3.80,4.47,0.30,0.0,1.0,1.0,6.0,0.0,0.0,5.0,0.0,0.0,0.000,0.0,0.0,0.000,1.0,1.0,1.000,0.0,0.0,0.0,0.0,7.0,0.0,5.0,6.0,0.0,1.0,0.0,0,LA Clippers,265,48,86,0.558,14,30,0.467,14,18,0.778,9,33,42,28,11,3,16,21,124,5,91.9,91.9,91.9,1610612744,122.9,117.9,121.4,116.5,119.0,43.0,79.0,0.544,25.0,31.0,11.0,6.0,16.0,0,3.5,218.5,0,-3.5,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,NaN,28.0,0.444,1.28,3.42,0.374,0.369,0.005,0.556,2.43,4.28,0.568,0.541,0.027,0.310,1.54,2.39,0.645,0.629,0.017,0.408,1.86,3.14,0.593,0.584,0.008,0.496,1.47,3.82,0.385,0.375,0.010,1.0,1.0,0.0,0.0,3.0,1.42,1.000,NaN,2.11,0.00,0.00,0.70,0.70,NaN,NaN,22024.0,0.0,NaN,NaN
26302,26302.0,26302,26302,Derrick Jones Jr.,1627884,LAC @ GSW,LAC,1610612746,GSW,0,22401198,2025-04-13,W,3,1,5,1,3,0.333,0,1,0.000,1,2,0.500,1,4,0,0,0,-4,10.5,0.773,0.333333,NaN,NaN,NaN,105.6,NaN,108.6,-5.3,0.063,0.222,0.147,0.091,0.333,0.0,0.098,0.387,95.96,97.43,0.069,35.0,81.19,0.102,17.73,4.11,1.31,4.0,4.0,7.0,15.0,0.0,0.0,11.0,1.0,2.0,0.500,0.0,1.0,0.000,1.0,1.0,1.000,0.0,2.0,0.0,2.0,13.0,0.0,8.0,14.0,0.0,1.0,1.0,0,LA Clippers,265,48,86,0.558,14,30,0.467,14,18,0.778,9,33,42,28,11,3,16,21,124,5,91.9,91.9,91.9,1610612744,122.9,117.9,121.4,116.5,119.0,43.0,79.0,0.544,25.0,31.0,11.0,6.0,16.0,0,3.5,218.5,0,-3.5,0.667,0.333,0.667,0.000,0.00,0.000,0.333,0.000,0.667,1.000,0.000,0.0,0.0,1.000,0.000,NaN,28.0,0.396,1.12,3.39,0.330,0.364,-0.034,0.604,2.86,5.17,0.553,0.540,0.013,0.326,1.97,2.79,0.707,0.634,0.073,0.414,2.26,3.55,0.637,0.585,0.052,0.475,1.38,4.06,0.339,0.372,-0.033,6.0,9.0,3.0,5.0,16.0,7.02,0.667,0.60,2.28,0.00,0.00,0.14,0.43,NaN,NaN,22024.0,0.0,NaN,NaN
26303,26303.0,26303,26303,Buddy Hield,1627741,GSW vs. LAC,GSW,1610612744,LAC,1,22401198,2025-04-13,L,8,0,1,3,7,0.429,2,6,0.333,0,0,NaN,0,1,0,0,0,-6,9.2,1.143,0.571429,NaN,NaN,NaN,99.4,NaN,131.2,-31.0,0.000,0.083,0.040,0.000,0.571,0.0,0.200,0.571,93.20,92.95,0.051,32.0,77.46,0.217,15.75,4.45,1.25,0.0,2.0,2.0,21.0,0.0,0.0,14.0,0.0,1.0,0.000,3.0,6.0,0.500,0.0,0.0,0.000,0.0,0.0,0.0,2.0,5.0,6.0,1.0,22.0,0.0,2.0,0.0,0,Golden State Warriors,265,43,79,0.544,15,33,0.455,18,23,0.783,3,22,25,31,11,6,16,20,119,-5,91.9,91.9,91.9,1610612746,116.5,121.4,117.9,122.9,124.0,48.0,86.0,0.558,42.0,28.0,11.0,3.0,16.0,0,3.5,218.5,1,3.5,0.143,0.857,0.250,0.000,0.75,0.000,0.000,0.000,0.250,1.000,0.000,1.0,0.0,1.000,0.000,NaN,32.0,0.349,1.22,3.35,0.364,0.367,-0.003,0.651,3.41,6.24,0.547,0.538,0.009,0.379,2.26,3.63,0.621,0.628,-0.007,0.493,2.67,4.73,0.564,0.581,-0.016,0.413,1.56,3.96,0.394,0.373,0.021,5.0,8.0,1.0,4.0,12.0,6.24,0.625,0.25,1.92,0.32,0.00,0.16,0.32,NaN,NaN,22024.0,0.0,NaN,NaN
26304,26304.0,26304,26304,Ben Simmons,1627732,LAC @ GSW,LAC,1610612746,GSW,0,22401198,2025-04-13,W,0,1,2,0,0,NaN,0,0,NaN,0,0,NaN,2,0,0,0,1,-11,2.9,0.000,NaN,NaN,NaN,NaN,88.5,NaN,146.8,-57.9,0.200,0.000,0.133,0.167,0.000,1.0,0.040,0.000,86.54,85.90,-0.027,19.0,71.59,0.041,10.62,4.04,0.77,3.0,0.0,3.0,20.0,0.0,1.0,18.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,10.0,0.0,5.0,10.0,0.0,2.0,0.0,0,LA Clippers,265,48,86,0.558,14,30,0.467,14,18,0.778,9,33,42,28,11,3,16,21,124,5,91.9,91.9,91.9,1610612744,122.9,117.9,121.4,116.5,119.0,43.0,79.0,0.544,25.0,31.0,11.0,6.0,16.0,0,3.5,218.5,0,-3.5,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,NaN,28.0,0.381,1.12,3.10,0.361,0.360,0.001,0.619,2.65,5.04,0.525,0.551,-0.025,0.352,1.86,2.86,0.651,0.641,0.009,0.467,2.22,3.80,0.582,0.591,-0.008,0.455,1.33,3.71,0.360,0.366,-0.006,0.0,1.0,0.0,1.0,0.0,3.63,0.000,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,22024.0,0.0,NaN,NaN
26305,26305.0,26305,26305,Jimmy Butler III,202710,GSW vs. LAC,GSW,1610612744,LAC,1,22401198,2025-04-13,L,30,9,1,12,20,0.600,0,2,0.000,6,9,0.667,0,1,1,1,1,2,49.7,1.252,0.600000,F,NaN,NaN,120.5,NaN,120.9,-0.5,0.000,0.028,0.014,0.333,0.600,9.0,0.245,0.626,91.08,89.94,0.137,91.0,74.95,0.252,48.03,4.07,3.49,0.0,4.0,4.0,77.0,1.0,1.0,50.0,6.0,9.0,0.667,6.0,11.0,0.545,1.0,3.0,0.333,11.0,2.0,8.0,22.0,16.0,14.0,5.0,46.0,0.0,1.0,9.0,0,Golden State Warriors,265,43,79,0.544,15,33,0.455,18,23,0.783,3,22,25,31,11,6,16,20,119,-5,91.9,91.9,91.9,1610612746,116.5,121.4,117.9,122.9,124.0,48.0,86.0,0.558,42.0,28.0,11.0,3.0,16.0,0,3.5,218.5,1,3.5,0.900,0.100,0.800,0.067,0.00,0.267,0.200,0.367,0.733,0.667,0.333,0.0,0.0,0.667,0.333,NaN,35.0,0.445,1.78,4.84,0.368,0.361,0.008,0.555,3.40,6.04,0.563,0.539,0.024,0.334,2.36,3.64,0.650,0.627,0.023,0.421,2.71,4.58,0.591,0.582,0.009,0.510,2.09,5.55,0.377,0.369,0.008,10.0,23.0,2.0,10.0,22.0,20.33,0.435,0.20,1.08,0.25,0.05,0.00,0.30,NaN,NaN,22024.0,0.0,NaN,NaN

## Fetches Player Gamelogs

In [3]:
nba = FetchPlayersStats()
data = nba.getCompleteStats(
    season='2025-26', 
    season_type='Regular Season', 
    sleep_time=2, 
    max_workers=5,
    batch_limit=10,
    complete_cache_file='../DATA/CSV_FILES/REGULAR_DATA/S26.csv'
)
data.head()

Processing 10 games (limited by batch_limit=10)

Processing batch 1/1 (10 games)
Completed batch 1/1
Cache updated. Total games now: 12

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
0,0.0,Jake LaRavia,1631222,LAL vs. GSW,LAL,1610612747,GSW,1,22500002,2025-10-21,L,5,0,3,2,4,0.500,1,2,0.500,0,2,0.000,2,1,0,0,0,-5,8.6,1.025,0.625000,NaN,NaN,111.8,111.8,130.3,130.3,-18.5,0.118,0.063,0.091,0.000,0.625,0.00,0.122,0.512,101.56,101.56,0.028,34,84.63,0.122,15:50,4.37,1.13,4,2,6,27,0,0,22,0,1,0.0,2,3,0.667,1,4,0.25,0.0,2.0,0.0,2.0,4.0,7.0,2.0,10.0,0.0,1.0,1.0,0.500,0.500,0.400,0.000,0.600,0.000,0.000,0.000,0.400,0.0,1.0,1.0,0.0,0.500,0.500,2.0,9.0,1.0,2.0,7.0,6.31,0.222,0.500,0.222,0.500,1.11,0.00,0.00,0.16,0.16,22025.0,Los Angeles Lakers,2025-10-21,LAL vs. GSW,L,240.0,42.0,77.0,0.545,8.0,32.0,0.250,17.0,28.0,0.607,7.0,32.0,39.0,23.0,7.0,2.0,20.0,21.0,109.0,-10.0,1.0,101.5,101.5,101.5,1.610613e+09,106.5,116.3,108.2,118.1,119.0,38.0,78.0,0.487,40.0,29.0,10.0,4.0,19.0
1,1.0,Buddy Hield,1627741,GSW @ LAL,GSW,1610612744,LAL,0,22500002,2025-10-21,W,17,0,1,6,11,0.545,5,10,0.500,0,0,NaN,0,1,1,0,2,5,19.2,1.545,0.772727,NaN,NaN,106.7,106.7,95.6,95.6,11.1,0.000,0.038,0.022,0.000,0.773,0.00,0.271,0.773,97.08,97.08,0.170,45,80.90,0.271,22:15,4.63,1.65,3,4,6,38,0,0,25,1,1,1.0,5,10,0.500,0,1,0.00,2.0,0.0,0.0,2.0,10.0,6.0,2.0,26.0,0.0,0.0,0.0,0.091,0.909,0.118,0.000,0.882,0.000,0.000,0.118,0.118,0.0,1.0,0.8,0.2,0.667,0.333,7.0,10.0,2.0,3.0,16.0,9.22,0.700,0.667,0.700,0.667,1.74,0.11,0.00,0.00,0.43,22025.0,Golden State Warriors,2025-10-21,GSW @ LAL,W,240.0,38.0,78.0,0.487,17.0,40.0,0.425,26.0,29.0,0.897,9.0,31.0,40.0,29.0,10.0,4.0,19.0,27.0,119.0,10.0,1.0,101.5,101.5,101.5,1.610613e+09,118.1,108.2,116.3,106.5,109.0,42.0,77.0,0.545,39.0,23.0,7.0,2.0,20.0
2,2.0,Jaxson Hayes,1629637,LAL vs. GSW,LAL,1610612747,GSW,1,22500002,2025-10-21,L,4,1,6,2,3,0.667,0,0,NaN,0,0,NaN,2,4,0,0,1,-6,11.7,1.333,0.666667,NaN,NaN,100.0,100.0,125.0,125.0,-25.0,0.125,0.364,0.222,0.111,0.667,1.00,0.111,0.667,96.91,96.91,0.115,29,80.76,0.111,14:07,4.16,0.96,3,5,7,20,0,0,16,0,1,0.0,2,2,1.000,2,2,1.00,2.0,0.0,2.0,4.0,4.0,2.0,2.0,8.0,1.0,2.0,0.0,1.000,0.000,1.000,0.000,0.000,0.500,0.000,0.500,1.000,1.0,0.0,0.0,0.0,1.000,0.000,2.0,2.0,1.0,1.0,5.0,5.61,1.000,1.000,1.000,1.000,0.89,0.18,0.00,0.18,0.53,22025.0,Los Angeles Lakers,2025-10-21,LAL vs. GSW,L,240.0,42.0,77.0,0.545,8.0,32.0,0.250,17.0,28.0,0.607,7.0,32.0,39.0,23.0,7.0,2.0,20.0,21.0,109.0,-10.0,1.0,101.5,101.5,101.5,1.610613e+09,106.5,116.3,108.2,118.1,119.0,38.0,78.0,0.487,40.0,29.0,10.0,4.0,19.0
3,3.0,Jimmy Butler III,202710,GSW @ LAL,GSW,1610612744,LAL,0,22500002,2025-10-21,W,31,4,5,7,14,0.500,1,2,0.500,16,16,1.000,2,3,1,0,1,20,45.0,1.473,0.535714,F,NaN,135.2,135.2,104.1,104.1,31.1,0.067,0.097,0.082,0.174,0.536,4.00,0.282,0.737,99.50,99.50,0.188,71,82.92,0.282,34:44,4.01,2.28,4,4,7,64,1,0,39,2,4,0.5,5,10,0.500,4,4,1.00,6.0,2.0,4.0,8.0,12.0,7.0,2.0,40.0,0.0,4.0,9.0,0.857,0.143,0.387,0.129,0.097,0.129,0.516,0.194,0.258,0.5,0.5,1.0,0.0,0.571,0.429,8.0,12.0,3.0,7.0,21.0,13.76,0.667,0.429,0.667,0.429,1.53,0.00,0.00,0.15,0.15,22025.0,Golden State Warriors,2025-10-21,GSW @ LAL,W,240.0,38.0,78.0,0.487,17.0,40.0,0.425,26.0,29.0,0.897,9.0,31.0,40.0,29.0,10.0,4.0,19.0,27.0,119.0,10.0,1.0,101.5,101.5,101.5,1.610613e+09,118.1,108.2,116.3,106.5,109.0,42.0,77.0,0.545,39.0,23.0,7.0,2.0,20.0
4,4.0,Draymond Green,203110,GSW @ LAL,GSW,1610612744,LAL,0,22500002,2025-10-21,W,8,9,7,3,6,0.500,1,3,0.333,1,3,0.333,1,6,1,2,4,20,34.9,1.093,0.583333,C,NaN,123.3,123.3,90.0,90.0,33.3,0.040,0.194,0.125,0.429,0.583,2.25,0.167,0.546,101.40,101.40,0.109,60,84.50,0.167,28:24,3.85,1.79,2,11,12,64,0,0,55,0,1,0.0,3,5,0.600,0,1,0.00,2.0,0.0,2.0,4.0,8.0,5.0,0.0,28.0,0.0,5.0,3.0,0.500,0.500,0.500,0.000,0.375,0.250,0.125,0.250,0.500,0.0,1.0,1.0,0.0,0.333,0.667,2.0,7.0,0.0,2.0,5.0,11.69,0.286,0.000,0.286,0.000,0.43,0.17,0.09,0.17,0.09,22025.0,Golden State Warriors,2025-10-21,GSW @ LAL,W,240.0,38.0,78.0,0.487,17.0,40.0,0.425,26.0,29.0,0.897,9.0,31.0,40.0,29.0,10.0,4.0,19.0,27.0,119.0,10.0,1.0,101.5,101.5,101.5,1.610613e+09,118.1,108.2,116.3,106.5,109.0,42.0,77.0,0.545,39.0,23.0,7.0,2.0,20.0

In [4]:
data

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
0,0.0,Jake LaRavia,1631222,LAL vs. GSW,LAL,1610612747,GSW,1,22500002,2025-10-21,L,5,0,3,2,4,0.500,1,2,0.500,0,2,0.000,2,1,0,0,0,-5,8.6,1.025,0.625000,NaN,NaN,111.8,111.8,130.3,130.3,-18.5,0.118,0.063,0.091,0.000,0.625,0.00,0.122,0.512,101.56,101.56,0.028,34,84.63,0.122,15:50,4.37,1.13,4,2,6,27,0,0,22,0,1,0.0,2,3,0.667,1,4,0.25,0.0,2.0,0.0,2.0,4.0,7.0,2.0,10.0,0.0,1.0,1.0,0.500,0.500,0.400,0.000,0.600,0.000,0.000,0.000,0.400,0.00,1.00,1.000,0.000,0.500,0.500,2.0,9.0,1.0,2.0,7.0,6.31,0.222,0.500,0.222,0.500,1.11,0.00,0.00,0.16,0.16,22025.0,Los Angeles Lakers,2025-10-21,LAL vs. GSW,L,240.0,42.0,77.0,0.545,8.0,32.0,0.250,17.0,28.0,0.607,7.0,32.0,39.0,23.0,7.0,2.0,20.0,21.0,109.0,-10.0,1.0,101.5,101.5,101.5,1.610613e+09,106.5,116.3,108.2,118.1,119.0,38.0,78.0,0.487,40.0,29.0,10.0,4.0,19.0
1,1.0,Buddy Hield,1627741,GSW @ LAL,GSW,1610612744,LAL,0,22500002,2025-10-21,W,17,0,1,6,11,0.545,5,10,0.500,0,0,NaN,0,1,1,0,2,5,19.2,1.545,0.772727,NaN,NaN,106.7,106.7,95.6,95.6,11.1,0.000,0.038,0.022,0.000,0.773,0.00,0.271,0.773,97.08,97.08,0.170,45,80.90,0.271,22:15,4.63,1.65,3,4,6,38,0,0,25,1,1,1.0,5,10,0.500,0,1,0.00,2.0,0.0,0.0,2.0,10.0,6.0,2.0,26.0,0.0,0.0,0.0,0.091,0.909,0.118,0.000,0.882,0.000,0.000,0.118,0.118,0.00,1.00,0.800,0.200,0.667,0.333,7.0,10.0,2.0,3.0,16.0,9.22,0.700,0.667,0.700,0.667,1.74,0.11,0.00,0.00,0.43,22025.0,Golden State Warriors,2025-10-21,GSW @ LAL,W,240.0,38.0,78.0,0.487,17.0,40.0,0.425,26.0,29.0,0.897,9.0,31.0,40.0,29.0,10.0,4.0,19.0,27.0,119.0,10.0,1.0,101.5,101.5,101.5,1.610613e+09,118.1,108.2,116.3,106.5,109.0,42.0,77.0,0.545,39.0,23.0,7.0,2.0,20.0
2,2.0,Jaxson Hayes,1629637,LAL vs. GSW,LAL,1610612747,GSW,1,22500002,2025-10-21,L,4,1,6,2,3,0.667,0,0,NaN,0,0,NaN,2,4,0,0,1,-6,11.7,1.333,0.666667,NaN,NaN,100.0,100.0,125.0,125.0,-25.0,0.125,0.364,0.222,0.111,0.667,1.00,0.111,0.667,96.91,96.91,0.115,29,80.76,0.111,14:07,4.16,0.96,3,5,7,20,0,0,16,0,1,0.0,2,2,1.000,2,2,1.00,2.0,0.0,2.0,4.0,4.0,2.0,2.0,8.0,1.0,2.0,0.0,1.000,0.000,1.000,0.000,0.000,0.500,0.000,0.500,1.000,1.00,0.00,0.000,0.000,1.000,0.000,2.0,2.0,1.0,1.0,5.0,5.61,1.000,1.000,1.000,1.000,0.89,0.18,0.00,0.18,0.53,22025.0,Los Angeles Lakers,2025-10-21,LAL vs. GSW,L,240.0,42.0,77.0,0.545,8.0,32.0,0.250,17.0,28.0,0.607,7.0,32.0,39.0,23.0,7.0,2.0,20.0,21.0,109.0,-10.0,1.0,101.5,101.5,101.5,1.610613e+09,106.5,116.3,108.2,118.1,119.0,38.0,78.0,0.487,40.0,29.0,10.0,4.0,19.0
3,3.0,Jimmy Butler III,202710,GSW @ LAL,GSW,1610612744,LAL,0,22500002,2025-10-21,W,31,4,5,7,14,0.500,1,2,0.500,16,16,1.000,2,3,1,0,1,20,45.0,1.473,0.535714,F,NaN,135.2,135.2,104.1,104.1,31.1,0.067,0.097,0.082,0.174,0.536,4.00,0.282,0.737,99.50,99.50,0.188,71,82.92,0.282,34:44,4.01,2.28,4,4,7,64,1,0,39,2,4,0.5,5,10,0.500,4,4,1.00,6.0,2.0,4.0,8.0,12.0,7.0,2.0,40.0,0.0,4.0,9.0,0.857,0.143,0.387,0.129,0.097,0.129,0.516,0.194,0.258,0.50,0.50,1.000,0.000,0.571,0.429,8.0,12.0,3.0,7.0,21.0,13.76,0.667,0.429,0.667,0.429,1.53,0.00,0.00,0.15,0.15,22025.0,Golden State Warriors,2025-10-21,GSW @ LAL,W,240.0,38.0,78.0,0.487,17.0,40.0,0.425,26.0,29.0,0.897,9.0,31.0,40.0,29.0,10.0,4.0,19.0,27.0,119.0,10.0,1.0,101.5,101.5,101.5,1.610613e+09,118.1,108.2,116.3,106.5,109.0,42.0,77.0,0.545,39.0,23.0,7.0,2.0,20.0
4,4.0,Draymond Green,203110,GSW @ LAL,GSW,1610612744,LAL,0,22500002,2025-10-21,W,8,9,7,3,6,0.500,1,3,0.333,1,3,0.333,1,6,1,2,4,20,34.9,1.093,0.583333,C,NaN,123.3,123.3,90.0,90.0,33.3,0.040,0.194,0.125,0.429,0.583,2.25,0.167,0.546,101.40,101.40,0.109,60,84.50,0.167,28:24,3.85,1.79,2,11,12,64,0,0,55,0,1,0.0,3,5,0.600,0,1,0.00,2.0,0.0,2.0,4.0,8.0,5.0,0.0,28.0,0.0,5.0,3.0,0.500,0.500,0.500,0.000,0.375,0.250,0.125,0.250,0.500,0.00,1.00,1.000,0.000,0.333,0.667,2.0,7.0,0.0,2.0,5.0,11.69,0.286,0.000,0.286,0.000,0.43,0.17,0.09,0.17,0.09,22025.0,Golden State Warriors,2025-10-21,GSW @ LAL,W,240.0,38.0,78.0,0.487,17.0,40.0,0.425,26.0,29.0,0.897,9.0,31.0,40.0,29.0,10.0,4.0,19.0,27.0,119.0,10.0,1.0,101.5,101.5,101.5,1.610613e+09,118.1,108.2,116.3,106.5,109.0,42.0,77.0,0.545,39.0,23.0,7.0,2.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,NaN,Trae Young,1629027,ATL vs. TOR,ATL,1610612737,TOR,1,0022500082,2025-10-22,L,22,5,1,5,14,0.357,1,7,0.143,11,13,0.846,0,1,1,0,2,-14,31.7,1.116,0.392857,G,,110.5,110.5,129.8,129.8,-19.3,0.000,0.030,0.013,0.208,0.393,2.50,0.232,0.558,118.95,118.95,0.066,86,99.13,0.232,34:18,0.00,0.00,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.00,2.0,0.0,2.0,8.0,17.0,19.0,28.0,74.0,0.0,4.0,11.0,0.500,0.500,0.364,0.000,0.136,0.091,0.500,0.091,0.364,0.00,1.00,0.000,1.000,0.000,1.000,9.0,13.0,2.0,6.0,26.0,12.98,0.692,0.333,0.692,0.333,2.00,0.15,0.00,0.23,0.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,NaN,Luke Kennard,1628379,ATL vs. TOR,ATL,1610612737,TOR,1,0022500082,2025-10-22,L,6,3,4,2,7,0.286,1,5,0.200,1,1,1.000,0,4,1,0,3,-16,15.3,0.806,0.357143,,,100.0,100.0,123.5,123.5,-23.5,0.000,0.154,0.063,0.158,0.357,1.00,0.133,0.403,107.19,107.19,0.023,68,89.32,0.133,30:27,0.00,0.00,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.00,3.0,0.0,3.0,2.0,8.0,10.0,23.0,50.0,0.0,3.0,1.0,0.286,0.714,0.333,0.000,0.500,0.500,0.167,0.500,0.333,1.00,0.00,1.000,0.000,1.000,0.000,6.0,9.0,0.0,1.0,14.0,11.89,0.667,0.000,0.667,0.000,1.18,0.25,0.00,0.08,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,NaN,Kristaps Porziņģis,204001,ATL vs. TOR,ATL,1610612737,TOR,1,0022500082,2025-10-22,L,20,2,7,5,12,0.417,4,7,0.571,6,6,1.000,2,5,0,2,2,-11,35.4,1.366,0.583333,C,,114.3,114.3,129.7,129.7,-15.4,0.069,0.238,0.140,0.111,0.583,1.00,0.236,0.683,119.22,119.22,0.115,63,99.35,0.236,25:34,0.00,0.00,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.00,8.0,6.0,0.0,2.0,16.0,9.0,15.0,50.0,2.0,4.0,3.0,0.417,0.583,0.100,0.000,0.600,0.000,0.300,0.400,0.100,1.00,0.00,1.000,0.000,1.000,0.000,9.0,15.0,0.0,0.0,20.0,9.86,0.600,0.000,0.600,0.000,2.03,0.41,0.10,0.10,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,NaN,Desmond Bane,1630217,ORL vs. MIA,ORL,1610612753,MIA,1,0022500081,2025-10-22,W,23,3,4,7,18,0.389,3,6,0.500,6,6,1.000,0,4,0,2,4,-3,34.3,1.114,0.472222,G,,101.4,101.4,102.6,102.6,-1.3,0.000,0.108,0.055,0.188,0.472,0.75,0.305,0.557,110.71,110.71,0.104,74,92.26,0.305,32:31,0.00,0.00,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.00,6.0,2.0,0.0,6.0,10.0,5.0,11.0,30.0,0.0,4.0,3.0,0.667,0.333,0.348,0.087,0.391,0.000,0.261,0.261,0.261,0.75,0.25,0.333,0.667,0.571,0.429,4.0,14.0,2.0,7.0,14.0,11.96,0.286,0.286,0.286,0.286,1.17,0.00,0.17,0.25,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,NaN,Donovan Mitchell,1628378,CLE @ NYK,CLE,1610612739,NYK,0,0022500003,2025-10-22,L,31,5,2,12,25,0.480,2,9,0.222,5,5,1.000,0,2,2,1,3,-14,46.9,1.140,0.520000,G,,101.2,101.2,123.1,123.1,-21.8,0.000,0.065,0.030,0.278,0.520,1.67,0.357,0.570,106.35,106.35,0.163,81,88.62,0.357,35:53,0.00,0.00,0,0,0,0,0,0,0,0,0,0.0,0,0,0.000,0,0,0.00,4.0,0.0,9.0,10.0,17.0,10.0,11.0,36.0,1.0,2.0,6.0,0.640,0.360,0.645,0.323,0.194,0.290,0.161,0.129,0.323,0.10,0.90,0.000,1.000,0.083,0.917,3.0,7.0,3.0,6.0,9.0,14.35,0.429,0.500,0.429,0.500,0.63,0.07,0.07,0.00,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Merge team data into player logs

In [4]:
# # Drop all team-related columns to re-merge with correct pace calculations
# data = s26_regular

# columns_to_drop = [
#     'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
#     # Pace columns (incorrect calculations)
#     'TEAM_PACE', 'GAME_PACE', 'OPP_PACE',
    
#     # Rating columns (may need recalculation with correct pace)
#     'TEAM_OFF_RATING', 'TEAM_DEF_RATING',
#     'OPP_OFF_RATING', 'OPP_DEF_RATING',
    
#     # Other team stats that came from the merge
#     'TEAM_PTS', 'TEAM_FGM', 'TEAM_FGA', 'TEAM_FG_PCT',
#     'TEAM_FG3M', 'TEAM_FG3A', 'TEAM_FG3_PCT',
#     'TEAM_FTM', 'TEAM_FTA', 'TEAM_FT_PCT', 
#     'TEAM_OREB', 'TEAM_DREB', 'TEAM_REB',
#     'TEAM_AST', 'TEAM_STL', 'TEAM_BLK', 'TEAM_TOV',
#     'TEAM_PF', 'TEAM_PLUS_MINUS',
    
#     # Opponent stats
#     'OPP_TEAM_ID', 'OPP_PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
#     'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK', 'OPP_TOV'
    
#     'TEAM_SEASON_ID_x',	'OPP_TOV_x', 'TEAM_SEASON_ID_y', 'OPP_TOV_y', 'TEAM_SEASON_ID', 'TEAM_NAME', 'TEAM_GAME_DATE', 'TEAM_MATCHUP', 'TEAM_WL', 'TEAM_MIN', 'VIDEO_AVAILABLE'
# ]

# # Drop columns that exist in the dataframe
# existing_cols = [col for col in columns_to_drop if col in data.columns]
# data = data.drop(columns=existing_cols)

# teamlogs = mergeTeamtoPlayer(data, season='2025-26', season_type='Regular Season')
# teamlogs

In [5]:
# teamlogs.to_csv('../DATA/CSV_FILES/REGULAR_DATA/S26.csv')
# teamlogs

## Assign features for regular season data

In [6]:
# Add this line after your current imports
from FEATURES.features import teamContext as features_teamContext

def convert_min_to_float(min_str):
    try:
        if isinstance(min_str, str) and ":" in min_str:
            minutes, seconds = map(int, min_str.split(":"))
            total_minutes = minutes + seconds / 60
            return round(total_minutes, 2)
        elif isinstance(min_str, (int, float)):
            return float(min_str)
        else:
            return 0
    except:
        return 0

def process_season_features(season_df, prop_type, year):
    df = season_df.copy()
    df = sort_data_for_features(df)
    df['STARTING'] = df['START_POSITION'].apply(lambda x: 1 if x in ['G','F','C'] else 0)
    df['BLOWOUT_RISK'] = (abs(df['spread']) >= 10).astype(int)
    df['TEAM_IMPLIED_PTS_FAV'] = ((df['total'] + df['team_spread']) / 2).round(1)
    df['TEAM_IMPLIED_PTS_UND'] = ((df['total'] - df['team_spread']) / 2).round(1)
    
    # Add position data
    cache_file = os.path.join(project_root, 'DATA', 'TOOLS', 'playerInfo.csv')
    df = assign_position_with_cache(df, cache_file=cache_file, max_workers=4, delay_between_requests=1.5)
   
    df = add_rest_day_features(df)
    df['HEIGHT'] = df['HEIGHT'].apply(convert_height_to_inches)
    df['MIN'] = df['MIN'].apply(convert_min_to_float)
    
    # Prop-specific features
    df = assign_team_opp_def_by_position(df)
    df = teamRollingDefenseByPosition(df, team_id_col='TEAM_ID', date_col='GAME_DATE', windows=[5,10,15])
    df = assign_team_opp_zone_by_position(df)
    df = rollingAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE', windows=[5,7,10,15,25,40])
    df = statAgainstTeam(df, player_id_col='PLAYER_ID', opp_col='OPP_ABBREVIATION', stat_line=prop_type)
    df = HomeAwayAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE')
    
    # ADD THESE MISSING CALLS:
    df = getPlayerAvgToDateVectorized(df) 
    df = assign_opponent_team_stats_dict(df)  
    
    df = addLagFeatures(df)
    df = add_volatility_features(df, windows=[5,7,10,15,25])
    df = add_standard_deviation_features(df)
    # df = add_performance_volatility_categories(df)
    # df = add_recent_form_volatility(df)
    df = process_star_players_data(df, min_minutes=20)
    df = add_performance_without_stars_columns(df, min_games=1)
    # df = teamUsualStarters(df)
    # df = oppTeamUsualStarters(df)
    df = features_teamContext(df)
    df = dynamic_defense_ranking(df)
    df = add_opponent_team_rolling_stats(df, windows=[3,5,7,10])
    df = add_opponent_team_form_indicators(df, windows=[3,5,7,10])
    df = expectedPace(df)
    df = add_interaction_features(df)  

    # Clean up any unwanted columns
    if 'Unnamed: 0' in df.columns:
        df.drop(columns=['Unnamed: 0'], inplace=True)
    if 'Unnamed: 0.1' in df.columns:
        df.drop(columns=['Unnamed: 0.1'], inplace=True)
    return df

prop_types = ['PTS']
data = [s19_regular,s20_regular, s21_regular,s22_regular,s23_regular,s24_regular,s25_regular]
seasons = [2019,2020,2021,2022,2023,2024,2025]
# data = [s26_regular]
# seasons = [2026]

# Pre-define output directory once
output_dir = os.path.join(project_root, 'DATA', 'CSV_FILES', 'TRAIN_DATA')
os.makedirs(output_dir, exist_ok=True)

# Process each season sequentially but with optimized operations
for season_data, year in zip(data, seasons):
    print(f"Processing year {year}...")
    
    # Process features
    processed_data = process_season_features(
        season_data, 
        prop_type='PTS',
        year=year
    )
    
    # Save file
    output_path = os.path.join(output_dir, f'PTS_TRAIN_{str(year)[-2:]}.csv')
    processed_data.to_csv(output_path)
    print(f"Completed {year}")

Processing year 2019...
Loading position cache...
Loaded 1175 players from cache
Found 530 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2019
Processing year 2020...
Loading position cache...
Loaded 1175 players from cache
Found 529 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2020
Processing year 2021...
Loading position cache...
Loaded 1175 players from cache
Found 540 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2021
Processing year 2022...
Loading position cache...
Loaded 1175 players from cache
Found 605 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2022
Processing year 2023...
Loading position cache...
Loaded 1175 players from cache
Found 539 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2023
Processing year 2024...
Loading position cache...
Loaded 1175 players from cache
Found 572 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2024
Processing year 2025...
Loading position cache...
Loaded 1175 players from cache
Found 569 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1175 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Creating PTS_AVG_TO_DATE
Creating FGA_AVG_TO_DATE
Creating FG3A_AVG_TO_DATE
Creating FTM_AVG_TO_DATE
Creating FG_PCT_AVG_TO_DATE
Creating TS_PCT_AVG_TO_DATE
Creating POSS_AVG_TO_DATE
Creating USG_PCT_AVG_TO_DATE
Creating MIN_AVG_TO_DATE
Creating PACE_AVG_TO_DATE
Creating TCHS_AVG_TO_DATE
Creating EFG_PCT_AVG_TO_DATE
Creating percentagePointsPaint_AVG_TO_DATE
Creating percentagePointsMidrange2pt_AVG_TO_DATE
Creating percentagePoints3pt_AVG_TO_DATE
Creating percentagePointsFreeThrow_AVG_TO_DATE
Completed 2025