In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from pathlib import Path
import sys
import os
from sklearn.preprocessing import LabelEncoder


project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.utils.nbaPlayerLogs import NBAGameLogs
from src.features.feature_engineer.pbp_features import *

pd.set_option('display.max_columns', None)

## Fetches Player Gamelogs

In [ ]:
# df = NBAGameLogs(season='2024-25', season_type='Regular Season').fetch(skip_start_positions=True).build().get_df()
# df.head()

# Session by session — run this repeatedly until all games are done
logs = NBAGameLogs(season='2025-26', season_type='Playoffs')
logs.fetch(batch_size=50, start_position_delay=2.5, start_position_workers=5, checkpoint_path='tracking_checkpoint.csv')

In [9]:
s26 = pd.read_csv(project_root / 'data/raw/season_stats/S26.csv').sort_values(by='GAME_DATE')
p26 = pd.read_csv(project_root / 'data/raw/playoff_stats/P26.csv').sort_values(by='GAME_DATE')
s26 = pd.concat([s26, p26])
s26.head(5)

/var/folders/9q/5_554qsx5z70w9d_vkmvjg0h0000gn/T/ipykernel_93736/1522414347.py:1: DtypeWarning: Columns (186) have mixed types. Specify dtype option on import or set low_memory=False.
  s26 = pd.read_csv(project_root / 'data/raw/season_stats/S26.csv').sort_values(by='GAME_DATE')

,Unnamed: 0.1,Unnamed: 0,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM_PG,FGA_PG,START_POSITION,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_TOV,TEAM_STL,TEAM_BLK,TEAM_BLKA,TEAM_PF,TEAM_PFD,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_E_OFF_RATING,TEAM_OFF_RATING,TEAM_E_DEF_RATING,TEAM_DEF_RATING,TEAM_E_NET_RATING,TEAM_NET_RATING,TEAM_AST_PCT,TEAM_AST_TO,TEAM_AST_RATIO,TEAM_OREB_PCT,TEAM_DREB_PCT,TEAM_REB_PCT,TEAM_TM_TOV_PCT,TEAM_EFG_PCT,TEAM_TS_PCT,TEAM_E_PACE,TEAM_PACE,TEAM_PACE_PER40,TEAM_POSS,TEAM_PIE,OPP_TEAM_ID,OPP_OPP_ABBREVIATION_base,OPP_OPP_NAME_base,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_BLKA,OPP_PF,OPP_PFD,OPP_PTS,OPP_PLUS_MINUS,OPP_E_OFF_RATING,OPP_OFF_RATING,OPP_E_DEF_RATING,OPP_DEF_RATING,OPP_E_NET_RATING,OPP_NET_RATING,OPP_AST_PCT,OPP_AST_TO,OPP_AST_RATIO,OPP_OREB_PCT,OPP_DREB_PCT,OPP_REB_PCT,OPP_TM_TOV_PCT,OPP_EFG_PCT,OPP_TS_PCT,OPP_E_PACE,OPP_PACE,OPP_PACE_PER40,OPP_POSS,OPP_PIE,IS_PLAYOFF,POS,AGE,TEAM_SPREAD,GAME_TOTAL,STARTING,PTS_PER_MIN,AST_PER_MIN,REB_PER_MIN,IS_HOME,POSITION_ENCODED,name
0,0.0,0.0,2025-26,1630611,Gui Santos,Gui,1610612744,GSW,Golden State Warriors,22500002,2025-10-21,GSW @ LAL,W,2.646667,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,0,0,0,0,0,0,0,-1.0,0,0,0.0,1,2:39,1,94.9,100.0,100.0,123.0,120.0,120.0,-28.0,-20.0,-20.0,0.000,0.00,0.0,0.000,0.000,0.000,100.0,100.0,0.000,0.000,0.167,0.158,101.56,99.75,83.12,99.75,-0.111,6,0.0,0.0,NaN,4.50,0.21,1,0,1,4,0,0,3,0,0,0.000,0,0,0.000,1,1,1.0,38,78,0.487,17,40,0.425,26,29,0.897,9,31,40,29,19.0,10,4,2,27,21,119,10.0,118.1,119.0,106.5,106.9,11.6,12.1,0.763,1.53,21.0,0.209,0.744,0.477,0.190,0.596,0.656,101.5,101.00,84.17,100,0.546,1610612747,LAL,Los Angeles Lakers,42,77,0.545,8,32,0.250,17,28,0.607,7,32,39,23,20.0,7,2,4,21,27,109,-10.0,106.5,106.9,118.1,119.0,-11.6,-12.1,0.548,1.15,16.9,0.256,0.791,0.523,0.196,0.597,0.610,101.5,101.00,84.17,102,0.454,0,PF,23.0,1.0,227.5,0,0.000000,0.000000,0.000000,0,1,NaN
22,19.0,20.0,2025-26,1628983,Shai Gilgeous-Alexander,Shai,1610612760,OKC,Oklahoma City Thunder,22500001,2025-10-21,OKC vs. HOU,W,47.216667,12,26,0.462,1,9,0.111,10,14,0.714,0,5,5,5,3,2,2,2,2,10,35,3,57.5,0,0,54.0,1,47:13,1,105.6,111.1,111.1,100.6,104.3,104.3,5.0,6.8,6.8,0.208,1.67,12.2,0.000,0.109,0.051,7.3,7.5,0.481,0.544,0.340,0.336,97.15,93.02,77.52,93.02,0.182,90,12.0,26.0,G,3.75,2.89,4,6,9,104,0,0,63,2,4,0.500,10,22,0.455,3,5,0.6,46,104,0.442,13,52,0.250,20,25,0.800,11,27,38,29,12.0,12,4,5,27,26,125,1.0,107.8,112.6,103.6,107.8,4.1,4.8,0.630,2.42,18.5,0.283,0.518,0.397,0.108,0.505,0.543,97.5,93.52,77.93,111,0.521,1610612745,HOU,Houston Rockets,43,97,0.443,11,39,0.282,27,31,0.871,16,36,52,23,25.0,6,5,4,26,27,124,-1.0,103.6,107.8,107.8,112.6,-4.1,-4.8,0.535,0.92,13.9,0.482,0.717,0.603,0.217,0.500,0.560,97.5,93.52,77.93,115,0.479,0,PG,27.0,-6.5,226.0,1,0.741264,0.105895,0.105895,1,2,NaN
23,1.0,22.0,2025-26,1630559,Austin Reaves,Austin,1610612747,LAL,Los Angeles Lakers,22500002,2025-10-21,LAL vs. GSW,L,36.333333,9,16,0.563,1,5,0.200,7,10,0.700,1,4,5,9,5,2,0,1,5,10,26,-14,46.5,0,0,45.0,1,36:20,1,99.5,102.7,102.7,121.9,119.7,119.7,-22.3,-17.1,-17.1,0.409,1.80,26.5,0.031,0.148,0.085,14.7,14.5,0.594,0.637,0.301,0.308,100.43,99.74,83.12,99.74,0.147,75,9.0,16.0,F,4.08,2.41,2,5,7,86,1,0,55,6,7,0.857,3,9,0.333,2,2,1.0,42,77,0.545,8,32,0.250,17,28,0.607,7,32,39,23,20.0,7,2,4,21,27,109,-10.0,106.5,106.9,118.1,119.0,-11.6,-12.1,0.548,1.15,16.9,0.256,0.791,0.523,0.196,0.597,0.610,101.5,101.00,84.17,102,0.454,1610612744,GSW,Golden State Warriors,38,78,0.487,17,40,0.425,26,29,0.897,9,31,40,29,19.0,10,4,2,27,21,119,10.0,118.1,119.0,106.5,106.9,11.6,12.1,0.763,1.53,21.0,0.209,0.744,0.477,0.190,0.596,0.656,101.5,101.00,84.17,100,0.546,0,SG,27.0,-1.0,227.5,1,0.715596,0.247706,0.137615,1,4,NaN
24,2.0,23.0,2025-26,1642964,Brooks Barnhizer,Brooks,1610612760,OKC,Oklahoma City Thunder,22500001,2025-10-21,OKC vs. HOU,W,2.256667,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0,-2,0.0,0,0,0.0,1,2:15,1,60.0,60.0,60.0,83.3,100.0,100.0,-23.3,-40.0,-40.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,116.99,106.35,88.63,106.35,0.000,5,0.0,0.0,NaN,4.70,0.17,0,1,1,1,0,0,1,0,0,0.000,0,0,0.000,0,0,0.0,46,104,0.442,13,52,0.250,20,25,0.800,11,27,38,29,12.0,12,4,5,27,26,125,1.0,107.8,112.6,103.6,107.8,4.1,4.8,0.630,2.42,18.5,0.283,0.518,0.397,0.108,0.505,0.543,97.5,93.52,77.93,111,0.521,1610612745,HOU,Houston Rockets,43,97,0.443,11,39,0.282,27,31,0.871,16,36,52,23,25.0,6,5,4,26,27,124,-1.0,103.6,107.8,107.8,112.6,-4.1,-4.8,0.535,0.92,13.9,0.482,0.717,0.603,0.217,0.500,0.560,97.5,93.52,77.93,115,0.479,0,SG,23.0,-6.5,226.0,0,0.000000,0.000000,0.000000,1,4,NaN
25,4.0,25.0,2025-26,1631119,Jaylin Williams,Jaylin,1610612760,OKC,Oklahoma City Thunder,22500001,2025-10-21,OKC vs. HOU,W,12.883333,1,5,0.200,0,4,0.000,0,0,0.000,0,0,0,1,0,1,0,0,1,1,2,-3,6.5,0,0,5.0,1,12:53,1,96.3,96.2,96.2,105.1,100.0,100.0,-8.8,-3.8,-3.8,0.143,0.00,16.7,0.000,0.000,0.000,0.0,0.0,0.200,0.200,0.179,0.185,97.99,100.60,83.83,100.60,-0.024,26,1.0,5.0,NaN,3.95,0.85,1,2,3,24,0,0,19,0,0,0.000,1,5,0.200,1,1,1.0,46,104,0.442,13,52,0.250,20,25,0.800,11,27,38,29,12.0,12,4,5,27,26,125,1.0,107.8,112.6,103.6,107.8,4.1,4.8,0.630,2.42,18.5,0.283,0.518,0.397,0.108,0.505,0.543,97.5,93.52,77.93,111,0.521,1610612745,HOU,Houston Rockets,43,97,0.443,11,39,0.282,27,31,0.871,16,36,52,23,25.0,6,5,4,26,27,124,-1.0,103.6,107.8,107.8,112.6,-4.1,-4.8,0.535,0.92,13.9,0.482,0.717,0.603,0.217,0.500,0.560,97.5,93.52,77.93,115,0.479,0,PF,23.0,-6.5,226.0,0,0.155239,0.077620,0.000000,1,1,NaN

In [16]:
import sys
sys.path.append('src')
from src.utils.pbp_stats import NBAPlayByPlay

# Pass a list of game IDs
game_ids = s26['GAME_ID'].unique().tolist()

pbp = NBAPlayByPlay(game_ids).fetch(
    delay=2,           # seconds between requests (default 0.3)
    workers=5,           # parallel threads (default 8)
    batch_size=100,      # games per batch (default 100)
    checkpoint_path='pbp_checkpoint.csv',  # saves progress so you can resume
    run_all_batches=True # set False to stop after first batch
).build()
df = pbp.get_df()
# df.to_csv(project_root / 'data/raw/pbp_season_stats/S22.csv', index=False)
df

✓ Checkpoint loaded — 0/1298 games done, 1298 remaining

── Batch 1/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 1 done — checkpoint saved (52365 rows total)

── Batch 2/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 2 done — checkpoint saved (104333 rows total)

── Batch 3/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 3 done — checkpoint saved (155346 rows total)

── Batch 4/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 4 done — checkpoint saved (206113 rows total)

── Batch 5/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 5 done — checkpoint saved (257264 rows total)

── Batch 6/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 6 done — checkpoint saved (307110 rows total)

── Batch 7/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 7 done — checkpoint saved (357536 rows total)

── Batch 8/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 8 done — checkpoint saved (407424 rows total)

── Batch 9/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 9 done — checkpoint saved (457665 rows total)

── Batch 10/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 10 done — checkpoint saved (507597 rows total)

── Batch 11/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 11 done — checkpoint saved (557647 rows total)

── Batch 12/13 (100 games) ──
  … 25/100 games in batch
  … 50/100 games in batch
  … 75/100 games in batch
  … 100/100 games in batch
  ✓ Batch 12 done — checkpoint saved (607054 rows total)

── Batch 13/13 (98 games) ──
  … 25/98 games in batch
  … 50/98 games in batch
  … 75/98 games in batch
  ✓ Batch 13 done — checkpoint saved (656172 rows total)
✓ Built — shape: (656172, 24)

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022500085,2,PT12M00.00S,1,0,,0,,,0,0,0,,0,0,0,0,,Start of 1st Period (8:13 PM EST),period,start,1,0,1
1,0022500085,4,PT12M00.00S,1,1610612763,MEM,1628991,Jackson Jr.,J. Jackson Jr.,0,0,0,,0,,,0,h,Jump Ball Jackson Jr. vs. Missi: Tip to Morant,Jump Ball,,1,0,2
2,0022500085,7,PT11M47.00S,1,1610612763,MEM,1628991,Jackson Jr.,J. Jackson Jr.,0,0,0,,0,,,0,h,Jackson Jr. Bad Pass Turnover (P1.T1),Turnover,Bad Pass,1,0,3
3,0022500085,7,PT11M47.00S,1,1610612740,NOP,1642274,Missi,Y. Missi,0,0,0,,0,,,0,v,Missi STEAL (1 STL),,,1,0,4
4,0022500085,9,PT11M43.00S,1,1610612740,NOP,1629673,Poole,J. Poole,-28,94,10,Made,1,0,2,2,v,Poole 10' Driving Floating Jump Shot (2 PTS),Made Shot,Driving Floating Jump Shot,1,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656167,0042500236,754,PT00M52.60S,4,1610612750,MIN,1630538,Hyland,B. Hyland,-173,191,26,Missed,1,,,0,h,MISS Hyland 26' 3PT Step Back Jump Shot,Missed Shot,Step Back Jump shot,1,3,527
656168,0042500236,755,PT00M49.90S,4,1610612759,SAS,203486,Plumlee,M. Plumlee,0,0,0,,0,,,0,v,Plumlee REBOUND (Off:0 Def:2),Rebound,Unknown,1,0,528
656169,0042500236,756,PT00M26.70S,4,1610612750,MIN,1630538,Hyland,B. Hyland,0,0,0,,0,,,0,h,Hyland P.FOUL (P1.T2) (J.Capers),Foul,Personal,1,0,529
656170,0042500236,758,PT00M12.70S,4,0,,1610612759,,,0,0,0,,0,,,0,v,Spurs Turnover: Shot Clock (T#16),Turnover,Shot Clock Turnover,1,0,530
656171,0042500236,759,PT00M00.00S,4,0,,0,,,0,0,0,,0,109,139,248,,End of 4th Period (12:16 AM EST),period,end,1,0,531

In [17]:
df.to_parquet("/Users/alexgonzalez/Documents/NBA-Prop-Predictor/data/raw/pbp_stats/s26_pbp.parquet", compression="snappy")

In [10]:
s25 = pd.read_parquet(project_root / 'data/raw/pbp_stats/s25_pbp.parquet')
s25.head()

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022400061,2,PT12M00.00S,1,0,,0,,,0,0,0,,0,0,0,0,,Start of 1st Period (7:36 PM EST),period,start,0,0,1
1,0022400061,4,PT12M00.00S,1,1610612738,BOS,201143,Horford,A. Horford,0,0,0,,0,,,0,h,Jump Ball Horford vs. Towns: Tip to White,Jump Ball,,1,0,2
2,0022400061,7,PT11M48.00S,1,1610612738,BOS,1628369,Tatum,J. Tatum,141,228,27,Made,1,3,0,3,h,Tatum 27' 3PT Pullup Jump Shot (3 PTS) (White ...,Made Shot,Pullup Jump shot,1,3,3
3,0022400061,9,PT11M27.00S,1,1610612752,NYK,1628384,Anunoby,O. Anunoby,36,46,6,Made,1,3,2,5,v,Anunoby 6' Driving Layup (2 PTS) (Brunson 1 AST),Made Shot,Driving Layup Shot,1,2,4
4,0022400061,11,PT11M16.00S,1,1610612738,BOS,1628369,Tatum,J. Tatum,-83,242,26,Missed,1,,,0,h,MISS Tatum 26' 3PT Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,3,5

In [23]:
game_df = s25[s25['gameId'] == '0022400061']
game_df = cleanPlaybyPlay(game_df)
# game_df.to_parquet("example_game.parquet", compression="snappy")
game_df['subType'].unique()

/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/features/feature_engineer/pbp_features.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MIN_SECONDS'] = df['clock'].apply(lambda x: isodate.parse_duration(x).total_seconds())
/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/features/feature_engineer/pbp_features.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['scoreHome'] = df['scoreHome'].replace('', np.nan).ffill()
/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/features/feature_engineer/pbp_features.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['scoreAway'] = df['scoreAway'].replace('', np.nan).ffill()

array(['start', '', 'Pullup Jump shot', 'Driving Layup Shot', 'Unknown',
       'Running Layup Shot', 'Driving Floating Jump Shot', 'Jump Shot',
       'Turnaround Hook Shot', 'Regular', 'Cutting Layup Shot',
       'Turnaround Fadeaway shot', 'Lost Ball', 'Running Dunk Shot',
       'Layup Shot', 'Tip Layup Shot', 'Fadeaway Jump Shot', 'Shooting',
       'Free Throw 1 of 2', 'Normal Rebound', 'Free Throw 2 of 2',
       'Bad Pass', 'Driving Finger Roll Layup Shot',
       'Step Back Jump shot', 'Putback Layup Shot', 'Personal',
       'Support Ruling', 'Running Pull-Up Jump Shot', 'Free Throw 1 of 1',
       'Defensive Goaltending', 'Driving Hook Shot', 'end',
       'Offensive Charge', 'Offensive Foul Turnover',
       'Floating Jump shot', 'Step Out of Bounds Turnover',
       'Running Jump Shot', 'Cutting Dunk Shot',
       'Driving Reverse Layup Shot', 'Out of Bounds Lost Ball Turnover',
       'Defense 3 Second', 'Free Throw Technical',
       'Driving Floating Bank Jump Shot', '8 Second Violation',
       'Tip Dunk Shot', 'Loose Ball', 'Kicked Ball',
       'Out of Bounds - Bad Pass Turnover', 'Shot Clock Turnover'],
      dtype=object)

In [24]:
game_df['actionType'].unique()

array(['period', 'Jump Ball', 'Made Shot', 'Missed Shot', 'Rebound',
       'Timeout', 'Turnover', '', 'Foul', 'Free Throw', 'Substitution',
       'Instant Replay', 'Violation'], dtype=object)