### Grabs the players data using the fetchplayerstats class
Enter the year you want in season and if you want Regualr Season or Playoffs in season_type

In [ ]:
import os
import sys
import pandas as pd

# Get the absolute path to the project root directory (going up one level from NOTEBOOKS)
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))

# Add the project root directory to sys.path
if project_root not in sys.path:
    sys.path.append(project_root)

from DATA.PROCESSED.fetchPlayersStats import FetchPlayersStats

nba = FetchPlayersStats()
data = nba.getCompleteStats(
    season='2020-21', 
    season_type='Regular Season', 
    sleep_time=3, 
    max_workers=3,
)
pd.set_option('display.max_columns', None)
data.head()

In [ ]:
data.to_csv('../DATA/CSV_FILES/REGULAR_DATA/S21.csv')

In [6]:
import pandas as pd

data = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P22.csv')
data.head()

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_DEF_RATING,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,PCT_FGM,PCT_FGA,PCT_FG3M,PCT_FG3A,PCT_FTM,PCT_FTA,PCT_OREB,PCT_DREB,PCT_REB,PCT_AST,PCT_TOV,PCT_STL,PCT_BLK,PCT_BLKA,PCT_PF,PCT_PFD,PCT_PTS
0,0,Jordan McLaughlin,1629162,MIN @ MEM,MIN,1610612750,MEM,0,42100151,2022-04-16,W,0,3,0,0,1,0.000,0,1,0.000,0,0,NaN,0,0,0,0,0,-2,4.5,0.000,0.000000,NaN,NaN,95.2,99.0,110.0,109.6,-14.8,0.0,0.000,0.000,0.429,0.000,0.0,0.038,0.000,103.01,104.85,0.033,21,87.37,0.043,240.0,45.0,90.0,0.500,16.0,41.0,0.390,24.0,27.0,0.889,11.0,35.0,46.0,32.0,5.0,7.0,18.0,32.0,130.0,108.88,108.9,108.92,119.397502,9:23,4.47,0.76,0,0,0,21,1,0,19,0,0,0.000,0,1,0.000,0,0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,3.0,10.0,0.0,1.0,0.0,0.000,0.056,0.000,0.091,0.000,0.000,0.000,0.000,0.000,0.500,0.000,0.0,0.000,0.000,0.200,0.000,0.000
1,1,Ziaire Williams,1630533,MEM vs. MIN,MEM,1610612763,MIN,1,42100151,2022-04-16,L,4,0,0,2,4,0.500,0,2,0.000,0,0,NaN,0,0,0,0,0,6,4.0,1.000,0.500000,NaN,NaN,108.3,105.5,83.3,84.6,25.0,0.0,0.000,0.000,0.000,0.500,0.0,0.160,0.500,118.24,117.55,0.000,24,97.96,0.156,240.0,39.0,86.0,0.453,7.0,27.0,0.259,32.0,43.0,0.744,8.0,27.0,35.0,25.0,7.0,8.0,12.0,24.0,117.0,108.92,108.9,108.88,107.418289,9:48,4.28,0.76,0,0,0,7,0,0,3,2,2,1.000,0,2,0.000,0,0,0.0,2.0,0.0,4.0,4.0,1.0,2.0,4.0,6.0,0.0,2.0,1.0,0.200,0.200,0.000,0.333,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.286,0.143,0.154
2,2,D'Angelo Russell,1626156,MIN @ MEM,MIN,1610612750,MEM,0,42100151,2022-04-16,W,10,9,3,2,11,0.182,1,3,0.333,5,5,1.0,0,3,1,0,2,12,28.1,0.758,0.227273,G,NaN,121.2,121.1,107.9,106.4,13.3,0.0,0.091,0.049,0.360,0.227,4.5,0.189,0.379,107.09,106.30,0.071,66,88.58,0.192,240.0,45.0,90.0,0.500,16.0,41.0,0.390,24.0,27.0,0.889,11.0,35.0,46.0,32.0,5.0,7.0,18.0,32.0,130.0,108.88,108.9,108.92,119.397502,29:08,4.16,2.19,1,3,4,67,1,1,50,0,4,0.000,2,7,0.286,3,3,1.0,0.0,0.0,2.0,2.0,16.0,8.0,11.0,40.0,2.0,3.0,3.0,0.074,0.200,0.100,0.130,0.313,0.313,0.000,0.125,0.097,0.529,0.182,0.5,0.000,0.286,0.167,0.214,0.125
3,3,Jaren Jackson Jr.,1628991,MEM vs. MIN,MEM,1610612763,MIN,1,42100151,2022-04-16,L,12,1,4,4,13,0.308,0,5,0.000,4,5,0.8,0,4,0,7,2,-16,37.3,0.789,0.307692,F,NaN,105.7,99.0,133.3,128.8,-27.7,0.0,0.167,0.077,0.071,0.308,0.5,0.283,0.395,112.40,106.93,0.037,53,89.10,0.285,240.0,39.0,86.0,0.453,7.0,27.0,0.259,32.0,43.0,0.744,8.0,27.0,35.0,25.0,7.0,8.0,12.0,24.0,117.0,108.92,108.9,108.88,107.418289,24:01,4.06,1.79,0,11,11,32,0,0,16,1,4,0.250,3,9,0.333,3,6,0.5,3.0,2.0,0.0,8.0,7.0,11.0,3.0,20.0,0.0,5.0,4.0,0.222,0.310,0.000,0.333,0.235,0.208,0.000,0.286,0.235,0.100,0.286,0.0,1.000,0.000,0.333,0.211,0.214
4,4,Karl-Anthony Towns,1626157,MIN @ MEM,MIN,1610612750,MEM,0,42100151,2022-04-16,W,29,3,13,11,18,0.611,2,5,0.400,5,5,1.0,4,9,0,1,3,16,49.1,1.436,0.666667,C,NaN,128.7,126.8,112.9,108.7,15.8,0.1,0.205,0.155,0.097,0.667,1.0,0.202,0.718,107.43,104.62,0.161,94,87.18,0.207,240.0,45.0,90.0,0.500,16.0,41.0,0.390,24.0,27.0,0.889,11.0,35.0,46.0,32.0,5.0,7.0,18.0,32.0,130.0,108.88,108.9,108.92,119.397502,42:54,3.83,3.00,9,15,24,66,1,1,40,5,11,0.455,6,7,0.857,4,5,0.8,4.0,4.0,0.0,18.0,19.0,12.0,16.0,52.0,3.0,3.0,7.0,0.262,0.222,0.143,0.135,0.217,0.192,0.364,0.310,0.325,0.100,0.214,0.0,0.167,0.429,0.111,0.318,0.240

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

# Get the path to the specific file
feature_path = os.path.abspath(r'c:\Users\alexg\OneDrive\Documents\Prize-Picks-Prop-Predictor')

# Add the parent directory to sys.path
if feature_path not in sys.path:
    sys.path.append(feature_path)

from FEATURE_ENGINEERING.features import *
from FEATURE_ENGINEERING.pts_features import *
from FEATURE_ENGINEERING.playoff_features import *
from DATA.PROCESSED.playerPositions import *
pd.set_option('display.max_columns', None)


s21_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P21.csv')
s21_playoffs['IS_PLAYOFF'] = 1
s21_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S21.csv')
s21_regular['IS_PLAYOFF'] = 0
s21 = pd.concat([s21_regular, s21_playoffs])

s22_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P22.csv')
s22_playoffs['IS_PLAYOFF'] = 1
s22_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S22.csv')
s22_regular['IS_PLAYOFF'] = 0
s22 = pd.concat([s22_regular, s22_playoffs])

s23_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P23.csv')
s23_playoffs['IS_PLAYOFF'] = 1
s23_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S23.csv')
s23_regular['IS_PLAYOFF'] = 0
s23 = pd.concat([s23_regular, s23_playoffs])

s24_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P24.csv')
s24_playoffs['IS_PLAYOFF'] = 1
s24_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S24.csv')
s24_regular['IS_PLAYOFF'] = 0
s24 = pd.concat([s24_regular, s24_playoffs])

s25_playoffs = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/P25.csv')
s25_playoffs['IS_PLAYOFF'] = 1
s25_regular = pd.read_csv('../DATA/CSV_FILES/REGULAR_DATA/S25.csv')
s25_regular['IS_PLAYOFF'] = 0
s25 = pd.concat([s25_regular, s25_playoffs])

data = pd.concat([s21, s22, s23, s24, s25])
data.sort_values(by='GAME_DATE', inplace=True)
data

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,MIN,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PF,PLUS_MINUS,FANTASY_PTS,PointsPerShot,eFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,TEAM_GAME_DATE,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,OPP_DEF_RATING,OPP_STL,OPP_BLK,OPP_REB,OPP_FG_PCT,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_PACE,GAME_PACE,OPP_PACE,IS_PLAYOFF,POINT_PER_SHOT,EFG,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PFD,PCT_FGM,PCT_FGA,PCT_FG3M,PCT_FG3A,PCT_FTM,PCT_FTA,PCT_OREB,PCT_DREB,PCT_REB,PCT_AST,PCT_TOV,PCT_STL,PCT_BLK,PCT_BLKA,PCT_PF,PCT_PFD,PCT_PTS
0,0.0,Kawhi Leonard,202695,LAC @ LAL,LAC,1610612746,LAL,0,22000002,2020-12-22,W,34,26,3,2,10,26,0.385,1,8,0.125,5,5,1.000,0,2,2,0,3,5.0,1,35.9,0.922,0.403846,F,NaN,117.8,113.1,113.3,109.6,4.5,0.000,0.069,0.030,0.136,0.404,1.00,0.365,0.461,108.42,104.47,0.069,73.0,87.05,0.360,"DEC 22, 2020",240,44,93,0.473,14,40,0.350,14,19,0.737,11,29,40,22,10,3,16,29,116,109.063558,4.0,2.0,45.0,0.469136,1.610613e+09,109.063558,106.36,106.0,105.64,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29.0,Kyle Kuzma,1628398,LAL vs. LAC,LAL,1610612747,LAC,1,22000002,2020-12-22,L,27,15,0,1,6,11,0.545,1,3,0.333,2,2,1.000,0,1,0,0,2,2.0,1,14.2,1.263,0.590909,NaN,NaN,93.2,91.3,91.5,94.8,1.7,0.000,0.034,0.017,0.000,0.591,0.00,0.206,0.631,105.61,106.33,0.093,59.0,88.61,0.208,"DEC 22, 2020",240,38,81,0.469,9,29,0.310,24,31,0.774,8,37,45,22,4,2,19,20,109,103.180613,10.0,3.0,40.0,0.473118,1.610613e+09,103.180613,105.64,106.0,106.36,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30.0,Spencer Dinwiddie,203915,BKN vs. GSW,BKN,1610612751,GSW,1,22000001,2020-12-22,W,20,9,4,5,2,6,0.333,1,3,0.333,4,4,1.000,0,5,0,0,3,1.0,24,18.0,1.160,0.416667,G,NaN,125.5,116.3,74.5,75.4,51.1,0.000,0.185,0.102,0.211,0.417,1.33,0.196,0.580,116.84,113.08,0.124,47.0,94.24,0.197,"DEC 22, 2020",240,42,92,0.457,15,35,0.429,26,32,0.813,13,44,57,24,11,7,20,22,125,110.541210,6.0,6.0,47.0,0.373737,1.610613e+09,110.541210,113.08,113.6,114.12,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,31.0,Luke Kennard,1628379,LAC @ LAL,LAC,1610612746,LAL,0,22000002,2020-12-22,W,21,4,2,2,2,6,0.333,0,3,0.000,0,0,NaN,0,2,2,1,1,3.0,-3,17.4,0.667,0.333333,NaN,NaN,115.9,116.9,114.9,112.2,1.0,0.000,0.100,0.051,0.111,0.333,2.00,0.140,0.333,104.59,103.73,0.032,44.0,86.44,0.144,"DEC 22, 2020",240,44,93,0.473,14,40,0.350,14,19,0.737,11,29,40,22,10,3,16,29,116,109.063558,4.0,2.0,45.0,0.469136,1.610613e+09,109.063558,106.36,106.0,105.64,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,32.0,Stephen Curry,201939,GSW @ BKN,GSW,1610612744,BKN,0,22000001,2020-12-22,L,30,20,10,4,7,21,0.333,2,10,0.200,4,4,1.000,3,1,2,0,3,1.0,-23,42.8,0.879,0.380952,G,NaN,89.2,88.3,120.3,116.9,-31.1,0.073,0.029,0.053,0.556,0.381,3.33,0.313,0.439,119.41,117.16,0.127,74.0,97.64,0.314,"DEC 22, 2020",240,37,99,0.374,10,33,0.303,15,23,0.652,13,34,47,26,6,6,18,24,99,86.750789,11.0,7.0,57.0,0.456522,1.610613e+09,86.750789,114.12,113.6,113.08,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1781,NaN,Luguentz Dort,1629652,OKC vs. IND,OKC,1610612760,IND,1,42400407,2025-06-22,W,35:13,9,0,7,3,10,0.300,2,9,0.222,1,2,0.500,3,4,3,0,1,3.0,12,25.4,NaN,NaN,G,NaN,117.6,114.3,101.5,99.3,16.2,0.071,0.138,0.099,0.000,0.400,0.00,0.148,0.414,94.39,92.02,0.048,68.0,76.68,0.152,NaN,240,35,87,0.402,11,40,0.275,22,31,0.710,13,27,40,20,14,8,7,23,103,108.833474,NaN,NaN,NaN,NaN,NaN,NaN,94.64,93.2,91.76,1,0.827,0.400000,4.06,2.58,5.0,6.0,10.0,39.0,0.0,0.0,26.0,0.0,0.0,0.000,3.0,10.0,0.300,0.0,0.0,0.00,3.0,3.0,0.0,2.0,5.0,11.0,7.0,20.0,0.0,2.0,0.120,0.156,0.200,0.265,0.050,0.080,0.333,0.235,0.269,0.000,0.250,0.300,0.000,0.000,0.214,0.111,0.113
1780,NaN,Aaron Nesmith,1630174,IND @ OKC,IND,1610612754,OKC,0,42400407,2025-06-22,L,30:28,3,1,6,1,5,0.200,1,3,0.333,0,0,NaN,1,5,2,2,1,6.0,6,22.7,NaN,NaN,F,NaN,108.5,108.6,101.8,99.9,6.7,0.036,0.132,0.091,0.050,0.300,1.00,0.087,0.300,92.16,91.40,0.016,59.0,76.17,0.090,NaN,240,29,70,0.414,11,28,0.393,22,29,0.759,12,33,45,17,6,4,21,24,91,99.171752,NaN,NaN,NaN,NaN,NaN,NaN,91.76,93.2,94.64,1,0.600,0.300000,4.26,2.34,4.0,8.0,12.0,28.0,0.0,0.0,22.0,0.0,2.0,0.000,1.0,3.0,0.333,1.0,4.0,0.25,0.0,3.0,0.0,0.0,16.0,12.0,7.0,22.0,2.0,1.0,0.048,0.106,0.125,0.158,0.000,0.000,0.125,0.217,0.194,0.083,0.083,0.500,0.500,0.286,0.462,0.063,0.047
1802,NaN,T.J. McConnell,204456,IND @ OKC,IND,1610612754,OKC,0,42400407,2025-06-22,L,28:05,16,3,6,8,13,0.615,0,0,NaN,0,0,NaN,0,6,1,1,7,2.0,-12,26.7,NaN,NaN,NaN,NaN,83.6,83.9,101.8,99.6,-18.1,0.000,0.167,0.102,0.300,0.615,0.43,0.333,0.615,96.65,95.73,0.162,55.0,79.77,0.346,NaN,240,29,70,0.414,11,28,0.393,22,29,0.759,12,33,45,17,6,4,21,24,91,99.171752,NaN,NaN,NaN,NaN,NaN,NaN,91.76,93.2,94.64,1,1.231,0.615385,4.53,2.29,3.0,9.0,12.0,64.0,0.0,0.0,41.0,5.0,9.0,0.556,3.0,4.0,0.750,1.0,1.0,1.00,0.0,0.0,0.0,12.0,18.0,11.0,2.0,24.0,1.0,2.0,0.444,0.342,0.000,0.000,0.000,0.000,0.000,0.261,0.231,0.300,0.467,0.333,0.333,0.333,0.125,0.182,0.348
1790,NaN,Johnny Furphy,1642277,IND @ OKC,IND,1610612754,OKC,0,42400407,2025-06-22,L,0:32,0,0,0,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0.0,4,0.0,NaN,NaN,NaN,NaN,200.0,212.8,0.0,0.0,200.0,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,128.00,177.78,0.000,2.0,148.15,0.000,NaN,240,29,70,0.414,11,28,0.393,22,29,0.759,12,33,45,17,6,4,21,24,91,99.171752,NaN,NaN,NaN,NaN,NaN,NaN,91.76,93.2,94.64,1,0.000,NaN,3.51,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1803,NaN,Andrew Nembhard,1629614,IND @ OKC,IND,1610612754,OKC,0,42400407,2025-06-22,L,36:41,15,6,5,4,10,0.400,2,3,0.667,5,6,0.833,1,4,0,0,2,3.0,-9,28.0,NaN,NaN,G,NaN,104.3,103.3,115.5,112.3,-11.2,0.030,0.089,0.064,0.316,0.500,3.00,0.183,0.593,93.99,92.24,0.113,70.0,76.86,0.186,NaN,240,29,70,0.414,11,28,0.393,22,29,0.759,12,33,45,17,6,4,21,24,91,99.171752,NaN,NaN,NaN,NaN,NaN,NaN,91.76,93.2,94.64,1,1.187,0.500000,4.11,2.73,3.0,6.0,8.0,76.0,0.0,2.0,60.0,1.0,2.0,0.500,3.0,8.0,0.375,3.0,3.0,1.00,0.0,2.0,0.0,2.0,24.0,16.0,7.0,26.0,1.0,3.0,0.174,0.185,0.200,0.125,0.294,0.273,0.100,0.148,0.135,0.429,0.118,0.000,0.000,0.125,0.158,0.176,0.205

## Assign features for regular season data

In [3]:
star_players_by_year = {
    2021: [
        "Giannis Antetokounmpo", "Kawhi Leonard", "Nikola Jokic", "Stephen Curry", "Luka Doncic",
        "Julius Randle", "LeBron James", "Joel Embiid", "Damian Lillard", "Chris Paul",
        "Jimmy Butler", "Paul George", "Rudy Gobert", "Bradley Beal", "Kyrie Irving",
        "Devin Booker", "Mike Conley", "James Harden", "Zach LaVine", "Donovan Mitchell",
        "Nikola Vucevic", "Anthony Davis"
    ],
    2022: [
        "Giannis Antetokounmpo", "Luka Doncic", "Jayson Tatum", "Nikola Jokic", "Devin Booker",
        "Ja Morant", "Stephen Curry", "DeMar DeRozan", "Kevin Durant", "Joel Embiid",
        "LeBron James", "Chris Paul", "Trae Young", "Pascal Siakam", "Karl-Anthony Towns",
        "Andrew Wiggins", "Donovan Mitchell", "Rudy Gobert", "Zach LaVine", "Khris Middleton",
        "Jimmy Butler", "Darius Garland", "Fred VanVleet", "LaMelo Ball"
    ],
    2023: [
        "Giannis Antetokounmpo", "Jayson Tatum", "Joel Embiid", "Shai Gilgeous-Alexander", "Luka Doncic",
        "Jaylen Brown", "Jimmy Butler", "Nikola Jokic", "Stephen Curry", "Donovan Mitchell",
        "LeBron James", "Julius Randle", "Domantas Sabonis", "De'Aaron Fox", "Damian Lillard",
        "Kyrie Irving", "Zion Williamson", "Kevin Durant", "Ja Morant", "DeMar DeRozan",
        "Tyrese Haliburton", "Jrue Holiday", "Bam Adebayo", "Jaren Jackson Jr.", "Paul George",
        "Pascal Siakam", "Anthony Edwards"
    ],
    2024: [
        "Shai Gilgeous-Alexander", "Luka Doncic", "Jayson Tatum", "Giannis Antetokounmpo", "Nikola Jokic",
        "Jalen Brunson", "Anthony Edwards", "Kawhi Leonard", "Kevin Durant", "Anthony Davis",
        "Stephen Curry", "Devin Booker", "LeBron James", "Domantas Sabonis", "Bam Adebayo",
        "Tyrese Haliburton", "Damian Lillard", "Karl-Anthony Towns", "Jaylen Brown",
        "Trae Young", "Paolo Banchero", "Scottie Barnes", 'Joel Embiid'
    ],
    2025: [
        'Shai Gilgeous-Alexander', 'Nikola Jokić', 'Giannis Antetokounmpo', 'Jayson Tatum', 'Donovan Mitchell',
        'Anthony Edwards', 'LeBron James', 'Stephen Curry', 'Evan Mobley', 'Jalen Brunson',
        'Cade Cunningham', 'Karl-Anthony Towns', 'Tyrese Haliburton', 'Jalen Williams', 'James Harden',
        'Darius Garland', 'Damian Lillard', 'Anthony Davis', 'Kyrie Irving', 'Jaylen Brown', 'Tyler Herro', 'Jaren Jackson Jr.', 
        'Pascal Siakam', 'Victor Wembanyama', 'Alperen Sengun', 'Trae Young', 'LaMelo Ball', 'Devin Booker', 'Joel Embiid', 'Luka Doncic'
]}

all_defensive_players = {
    2021:['Rudy Gobert', 'Ben Simmons', 'Draymond Green', 'Jrue Holiday', 'Giannis Antetokounmpo', 'Bam Adebayo', 'Jimmy Butler',
          'Joel Embiid', 'Matisse Thybulle', 'Kawhi Leonard','Mikal Bridges', 'Marcus Smart', 'Luguentz Dort', 'Chris Paul',
           'Cline Capela', 'Myles Turner' ],
    2022:['Marcus Smart', 'Mikal Bridges', 'Rudy Gobert', 'Giannis Antetokounmpo', 'Jaren Jackson Jr.', 'Bam Adebayo', 'Jrue Holiday', 
          'Matisse Thybulle', 'Robert Williams III', 'Draymond Green', 'Fred VanVleet', 'Dejounte Murray', 'Chris Paul', 'Patrick Beverley'
          'Joel Embiid', 'Evan Mobley', 'Herbert Jones', 'Dorian Finney-Smith'],
    2023:['Alex Caruso', 'Jrue Holiday', 'Jaren Jackson Jr.', 'Brook Lopez', 'Evan Mobley', 'Bam Adebayo', 'O.G Anunoby',
          'Dillon Brooks', 'Draymond Green', 'Derrick White', 'Marcus Smart', 'Mikal Bridges', 'Jimmy Butler', 'Giannis Antetokounmpo', 'Jaden McDaniels', 'Anthony Davis',
           'Nic Claxton', 'Joel Embiid' ],
    2024:['Alex Caruso', 'Jrue Holiday', 'Jaren Jackson Jr.', 'Brook Lopez', 'Evan Mobley', 'Bam Adebayo', 'O.G Anunoby',
          'Dillon Brooks', 'Draymond Green', 'Derrick White', 'Marcus Smart', 'Mikal Bridges', 'Jimmy Butler', 'Giannis Antetokounmpo', 'Jaden McDaniels', 'Anthony Davis',
           'Nic Claxton', 'Joel Embiid', 'Herbert Jones', 'Jalen Suggs'],
    2025:['Dyson Daniels', 'Draymond Green', 'Luguentz Dort', 'Evan Mobley', 'Amen Thompson', 'Toumani Camara',
           'Rudy Gobert', 'Jaren Jackson Jr.', 'Jalen Williams', 'Ivica Zabac', 'Anthony Davis', 'Victor Wembanyama', 'Alex Caruso', 'Jure Holiday'
           'Bam Adebayo', 'Derrick White']
}

In [ ]:
def process_season_features(season_df, prop_type, year, star_players):
    """
    Process features for a specific season and prop type
    """
    # Basic preprocessing that's common for all props
    df = season_df.copy()
    df['STARTING'] = df['START_POSITION'].apply(lambda x: 1 if x in ['G','F','C'] else 0)
    df['OPP_TEAM_ID'] = df['OPP_TEAM_ID'].astype(int)
    
    # Add position data
    cache_file = os.path.join(feature_path, 'DATA', 'PROCESSED', 'playerInfo.csv')
    df = assign_position_with_cache(
        df, 
        cache_file=cache_file,
        max_workers=4, 
        delay_between_requests=1.5
    )
    
    # Common features for all props
    df = add_rest_day_features(df)
    df = encode_teams(df)
    
    # Prop-specific features
    df = statAgainstTeam(df, player_id_col='PLAYER_ID', opp_col='OPP_ABBREVIATION', stat_line=prop_type)
    df = rollingAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE', stat_line=prop_type)
    df = HomeAwayAverages(df, player_id_col='PLAYER_ID', date_col='GAME_DATE')
    df = addLagFeatures(df, stat_line=prop_type)
    df = add_all_opponent_features(df)
    df = allLineupFeatures(df, star_players)
    df = analyzeTeammateSplitsPTS(df, min_minutes=10) 
    df = analyzeTeammateSplitsWhenAnyStarSitsPTS(df, min_minutes=10)
    df = add_all_defensive_features(df, all_defensive_players, year)

    # Clean up any unwanted columns
    if 'Unnamed: 0' in df.columns:
        df.drop(columns=['Unnamed: 0'], inplace=True)
    if 'Unnamed: 0.1' in df.columns:
        df.drop(columns=['Unnamed: 0.1'], inplace=True)
    return df

prop_types = ['PTS']
data = [s21, s22, s23, s24, s25]
seasons = [2021, 2022, 2023, 2024, 2025]

# Pre-define output directory once
output_dir = os.path.join(feature_path, 'DATA', 'CSV_FILES', 'TRAIN_DATA')
os.makedirs(output_dir, exist_ok=True)

# Process each season sequentially but with optimized operations
for season_data, year in zip(data, seasons):
    print(f"Processing year {year}...")
    
    # Process features
    processed_data = process_season_features(
        season_data, 
        prop_type='PTS',
        year=year,
        star_players=star_players_by_year[year]
    )
    
    # Save file
    output_path = os.path.join(output_dir, f'PTS_TRAIN_{str(year)[-2:]}.csv')
    processed_data.to_csv(output_path)
    print(f"Completed {year}")

In [ ]:
import pandas as pd
import os
import sys

# Get the absolute path to your project directory
feature_path = os.path.abspath('/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor')
if feature_path not in sys.path:
    sys.path.append(feature_path)

from DATA.PROCESSED.fetchPlayersStats import FetchPlayersStats

class UpdateMissingStats:
    def __init__(self, input_file_path, output_file_path=None, sleep_time=0.1):
        self.input_file_path = input_file_path
        self.output_file_path = output_file_path or input_file_path
        self.sleep_time = sleep_time
        self.fetcher = FetchPlayersStats(sleep_time=sleep_time)
        
    def validate_data(self, df, stage=""):
        """Helper function to validate data at different stages"""
        print(f"\nValidation at {stage}:")
        print(f"Total rows: {len(df)}")
        print(f"Unique game-player combinations: {len(df.drop_duplicates(subset=['GAME_ID', 'PLAYER_ID']))}")
        print(f"Unique games: {len(df['GAME_ID'].unique())}")
        print(f"Unique players: {len(df['PLAYER_ID'].unique())}")
        
    def update_tracking_stats(self, batch_size=50):
        """Update tracking stats for all games since they don't exist yet"""
        print("Loading existing data...")
        df = pd.read_csv(self.input_file_path, dtype={'GAME_ID': str})
        df = df.drop_duplicates(subset=['GAME_ID', 'PLAYER_ID'])
        self.validate_data(df, "Initial load")
        
        # Define the columns we want to keep
        tracking_cols = [
            'GAME_ID', 'PLAYER_ID', 'MIN', 'SPD', 'DIST', 'ORBC', 'DRBC', 'RBC',
            'TCHS', 'SAST', 'FTAST', 'PASS', 'CFGM', 'CFGA', 'CFG_PCT',
            'UFGM', 'UFGA', 'UFG_PCT', 'DFGM', 'DFGA', 'DFG_PCT'
        ]
        
        game_ids = df['GAME_ID'].unique()
        print(f"\nFetching tracking stats for {len(game_ids)} games...")
        
        all_tracking = []
        processed_games = set()
        
        for i in range(0, len(game_ids), batch_size):
            batch = game_ids[i:i+batch_size]
            print(f"\nProcessing batch {i//batch_size + 1} of {(len(game_ids)-1)//batch_size + 1}")
            
            batch = [gid for gid in batch if gid not in processed_games]
            if not batch:
                continue
            
            temp_df = df[df['GAME_ID'].isin(batch)].copy()
            tracking = self.fetcher.getTrackingStats(temp_df, self.sleep_time)
            
            if not tracking.empty:
                # Keep only the columns we want
                tracking = tracking[tracking_cols].drop_duplicates(subset=['GAME_ID', 'PLAYER_ID'])
                all_tracking.append(tracking)
                processed_games.update(batch)
                
                if all_tracking:
                    combined_tracking = pd.concat(all_tracking, ignore_index=True)
                    combined_tracking = combined_tracking[tracking_cols].drop_duplicates(subset=['GAME_ID', 'PLAYER_ID'])
                    
                    # Merge only the tracking columns we want
                    merged = pd.merge(
                        df,
                        combined_tracking,
                        on=['GAME_ID', 'PLAYER_ID'],
                        how='left',
                        validate='1:1'
                    )
                    
                    self.validate_data(merged, "After merge")
                    merged.to_csv(self.output_file_path, index=False)
                    print(f"Progress saved - {len(processed_games)} unique games processed")
        
        if all_tracking:
            combined_tracking = pd.concat(all_tracking, ignore_index=True)
            combined_tracking = combined_tracking[tracking_cols].drop_duplicates(subset=['GAME_ID', 'PLAYER_ID'])
            
            merged = pd.merge(
                df,
                combined_tracking,
                on=['GAME_ID', 'PLAYER_ID'],
                how='left',
                validate='1:1'
            )
            
            self.validate_data(merged, "Final output")
            return merged
        return df

# Try it with a small batch size:
updater = UpdateMissingStats(
    input_file_path='../DATA/CSV_FILES/REGULAR_DATA/S25.csv',
    output_file_path='../DATA/CSV_FILES/REGULAR_DATA/S25_updated.csv',
    sleep_time=0.5
)

# Start with tracking stats:
df = updater.update_tracking_stats(batch_size=10)
df

:

In [19]:
lbj = df[df['PLAYER_NAME'] == 'LeBron James']
lbj[lbj['GAME_ID'] == '0022401159']

,Unnamed: 0,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,...,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT
1638554,25413,LeBron James,2544,LAL @ DAL,LAL,1610612747,DAL,0,0022401159,2025-04-09,...,44,7,9,0.778,4,11,0.364,4,5,0.8
1638555,25413,LeBron James,2544,LAL @ DAL,LAL,1610612747,DAL,0,0022401159,2025-04-09,...,44,7,9,0.778,4,11,0.364,4,5,0.8
1638556,25413,LeBron James,2544,LAL @ DAL,LAL,1610612747,DAL,0,0022401159,2025-04-09,...,44,7,9,0.778,4,11,0.364,4,5,0.8
1638557,25413,LeBron James,2544,LAL @ DAL,LAL,1610612747,DAL,0,0022401159,2025-04-09,...,44,7,9,0.778,4,11,0.364,4,5,0.8
1638558,25413,LeBron James,2544,LAL @ DAL,LAL,1610612747,DAL,0,0022401159,2025-04-09,...,44,7,9,0.778,4,11,0.364,4,5,0.8