In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from pathlib import Path
import sys
import os
from sklearn.preprocessing import LabelEncoder


project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.utils.nbaPlayerLogs import NBAGameLogs
from src.features.feature_engineer.pbp_features import *

pd.set_option('display.max_columns', None)

## Fetches Player Gamelogs

In [ ]:
# df = NBAGameLogs(season='2024-25', season_type='Regular Season').fetch(skip_start_positions=True).build().get_df()
# df.head()

# Session by session — run this repeatedly until all games are done
logs = NBAGameLogs(season='2025-26', season_type='Playoffs')
logs.fetch(batch_size=50, start_position_delay=2.5, start_position_workers=5, checkpoint_path='tracking_checkpoint.csv')

In [ ]:
s26 = pd.read_csv(project_root / 'data/raw/season_stats/S26.csv').sort_values(by='GAME_DATE')
p26 = pd.read_csv(project_root / 'data/raw/playoff_stats/P26.csv').sort_values(by='GAME_DATE')
s26 = pd.concat([s26, p26])
s26.tail(5)

C:\Users\alexg\AppData\Local\Temp\ipykernel_9176\2086954391.py:1: DtypeWarning: Columns (186) have mixed types. Specify dtype option on import or set low_memory=False.
  s26 = pd.read_csv(project_root / 'data/raw/season_stats/S26.csv').sort_values(by='GAME_DATE')

,Unnamed: 0.1,Unnamed: 0,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT,E_OFF_RATING,OFF_RATING,sp_work_OFF_RATING,E_DEF_RATING,DEF_RATING,sp_work_DEF_RATING,E_NET_RATING,NET_RATING,sp_work_NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,E_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,sp_work_PACE,PIE,POSS,FGM_PG,FGA_PG,START_POSITION,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_TOV,TEAM_STL,TEAM_BLK,TEAM_BLKA,TEAM_PF,TEAM_PFD,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_E_OFF_RATING,TEAM_OFF_RATING,TEAM_E_DEF_RATING,TEAM_DEF_RATING,TEAM_E_NET_RATING,TEAM_NET_RATING,TEAM_AST_PCT,TEAM_AST_TO,TEAM_AST_RATIO,TEAM_OREB_PCT,TEAM_DREB_PCT,TEAM_REB_PCT,TEAM_TM_TOV_PCT,TEAM_EFG_PCT,TEAM_TS_PCT,TEAM_E_PACE,TEAM_PACE,TEAM_PACE_PER40,TEAM_POSS,TEAM_PIE,OPP_TEAM_ID,OPP_OPP_ABBREVIATION_base,OPP_OPP_NAME_base,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_BLKA,OPP_PF,OPP_PFD,OPP_PTS,OPP_PLUS_MINUS,OPP_E_OFF_RATING,OPP_OFF_RATING,OPP_E_DEF_RATING,OPP_DEF_RATING,OPP_E_NET_RATING,OPP_NET_RATING,OPP_AST_PCT,OPP_AST_TO,OPP_AST_RATIO,OPP_OREB_PCT,OPP_DREB_PCT,OPP_REB_PCT,OPP_TM_TOV_PCT,OPP_EFG_PCT,OPP_TS_PCT,OPP_E_PACE,OPP_PACE,OPP_PACE_PER40,OPP_POSS,OPP_PIE,IS_PLAYOFF,POS,AGE,TEAM_SPREAD,GAME_TOTAL,STARTING,PTS_PER_MIN,AST_PER_MIN,REB_PER_MIN,IS_HOME,POSITION_ENCODED,name
28056,2,NaN,2025-26,1630596,Evan Mobley,Evan,1610612739,CLE,Cleveland Cavaliers,42500204,2026-05-11,CLE vs. DET,W,39.195000,6,11,0.545,1,4,0.250,4,4,1.000,4,4,8,5,3,3,5,1,2,3,17,30,55.1,0,0,47.0,1,39:12,1,131.1,132.9,132.9,92.6,97.4,97.4,38.5,35.5,35.5,0.192,1.67,23.8,0.108,0.100,0.104,14.3,14.5,0.591,0.666,0.172,0.175,98.61,95.52,79.60,95.52,0.159,79,6.0,11.0,F,4.18,2.95,7,10,17,90,0,0,72,5,8,0.625,1,3,0.333,5,8,0.625,34,78,0.436,14,41,0.341,30,34,0.882,12,21,33,23,15.0,11,8,3,15,27,112,9.0,116.7,120.4,105.9,110.8,10.8,9.7,0.676,1.53,17.3,0.391,0.595,0.489,0.161,0.526,0.602,96.6,93.0,77.50,93,0.566,1610612765,DET,Detroit Pistons,42,83,0.506,10,23,0.435,9,12,0.750,11,24,35,23,20.0,10,3,8,27,15,103,-9.0,105.9,110.8,116.7,120.4,-10.8,-9.7,0.548,1.15,17.4,0.405,0.609,0.511,0.215,0.566,0.583,96.6,93.0,77.50,93,0.434,1,PF,24.0,-3.5,213.0,1,0.433729,0.127567,0.204108,1,1,Evan Mobley
28057,21,NaN,2025-26,1630241,Sam Merrill,Sam,1610612739,CLE,Cleveland Cavaliers,42500204,2026-05-11,CLE vs. DET,W,16.328333,2,8,0.250,2,7,0.286,0,0,0.000,0,1,1,2,0,1,0,0,4,1,6,6,13.2,0,0,13.0,1,16:20,1,124.1,123.5,123.5,107.0,109.1,109.1,17.1,14.4,14.4,0.182,0.00,20.0,0.000,0.077,0.034,0.0,0.0,0.375,0.375,0.200,0.206,99.18,98.48,82.07,98.48,0.000,34,2.0,8.0,NaN,4.48,1.34,0,3,3,23,0,0,14,0,1,0.000,2,7,0.286,2,3,0.667,34,78,0.436,14,41,0.341,30,34,0.882,12,21,33,23,15.0,11,8,3,15,27,112,9.0,116.7,120.4,105.9,110.8,10.8,9.7,0.676,1.53,17.3,0.391,0.595,0.489,0.161,0.526,0.602,96.6,93.0,77.50,93,0.566,1610612765,DET,Detroit Pistons,42,83,0.506,10,23,0.435,9,12,0.750,11,24,35,23,20.0,10,3,8,27,15,103,-9.0,105.9,110.8,116.7,120.4,-10.8,-9.7,0.548,1.15,17.4,0.405,0.609,0.511,0.215,0.566,0.583,96.6,93.0,77.50,93,0.434,1,SG,29.0,-3.5,213.0,1,0.367459,0.122486,0.061243,1,4,Sam Merrill
28058,11,NaN,2025-26,1631096,Chet Holmgren,Chet,1610612760,OKC,Oklahoma City Thunder,42500224,2026-05-11,OKC @ LAL,W,35.220000,6,9,0.667,0,2,0.000,4,4,1.000,1,8,9,0,1,1,0,0,2,5,16,1,28.8,0,0,27.0,1,35:13,1,118.9,114.5,114.5,117.0,117.8,117.8,1.9,-3.3,-3.3,0.000,0.00,0.0,0.031,0.286,0.150,8.3,8.5,0.667,0.743,0.145,0.149,99.93,101.53,84.61,101.53,0.129,76,6.0,9.0,F,4.25,2.65,4,11,14,50,0,0,35,3,3,1.000,3,6,0.500,5,9,0.556,42,81,0.519,11,31,0.355,20,24,0.833,6,28,34,19,12.0,12,0,5,24,22,115,5.0,117.9,117.3,111.2,112.2,6.6,5.1,0.452,1.58,15.2,0.190,0.737,0.450,0.122,0.586,0.628,98.2,98.0,81.67,98,0.533,1610612747,LAL,Los Angeles Lakers,38,75,0.507,10,28,0.357,24,27,0.889,7,30,37,18,19.0,3,5,0,22,24,110,-5.0,111.2,112.2,117.9,117.3,-6.6,-5.1,0.474,0.95,14.3,0.263,0.810,0.550,0.194,0.573,0.633,98.2,98.0,81.67,98,0.467,1,PF,23.0,-12.5,214.5,1,0.454287,0.000000,0.255537,0,1,Chet Holmgren
28060,34,NaN,2025-26,1642281,Jaylon Tyson,Jaylon,1610612739,CLE,Cleveland Cavaliers,42500204,2026-05-11,CLE vs. DET,W,7.533333,0,1,0.000,0,1,0.000,1,2,0.500,1,2,3,0,0,0,0,0,0,1,1,-7,4.6,0,0,4.0,1,7:32,1,60.5,64.3,64.3,124.2,123.1,123.1,-63.7,-58.8,-58.8,0.000,0.00,0.0,0.091,0.500,0.200,0.0,0.0,0.000,0.266,0.118,0.118,88.44,86.02,71.68,86.02,0.094,14,0.0,1.0,NaN,4.25,0.57,2,2,4,13,0,0,12,0,0,0.000,0,1,0.000,0,0,0.000,34,78,0.436,14,41,0.341,30,34,0.882,12,21,33,23,15.0,11,8,3,15,27,112,9.0,116.7,120.4,105.9,110.8,10.8,9.7,0.676,1.53,17.3,0.391,0.595,0.489,0.161,0.526,0.602,96.6,93.0,77.50,93,0.566,1610612765,DET,Detroit Pistons,42,83,0.506,10,23,0.435,9,12,0.750,11,24,35,23,20.0,10,3,8,27,15,103,-9.0,105.9,110.8,116.7,120.4,-10.8,-9.7,0.548,1.15,17.4,0.405,0.609,0.511,0.215,0.566,0.583,96.6,93.0,77.50,93,0.434,1,SG,23.0,-3.5,213.0,1,0.132743,0.000000,0.398230,1,4,Jaylon Tyson
28084,0,NaN,2025-26,1628378,Donovan Mitchell,Donovan,1610612739,CLE,Cleveland Cavaliers,42500204,2026-05-11,CLE vs. DET,W,36.578333,13,26,0.500,4,12,0.333,13,15,0.867,1,4,5,2,1,1,0,0,1,9,43,28,54.0,0,0,56.0,1,36:35,1,131.9,133.3,133.3,91.9,94.4,94.4,40.0,38.9,38.9,0.118,2.00,5.6,0.030,0.108,0.071,2.8,2.8,0.577,0.660,0.405,0.416,96.27,94.48,78.74,94.48,0.261,72,13.0,26.0,G,4.04,2.66,2,5,7,65,2,0,30,5,9,0.556,8,17,0.471,1,2,0.500,34,78,0.436,14,41,0.341,30,34,0.882,12,21,33,23,15.0,11,8,3,15,27,112,9.0,116.7,120.4,105.9,110.8,10.8,9.7,0.676,1.53,17.3,0.391,0.595,0.489,0.161,0.526,0.602,96.6,93.0,77.50,93,0.566,1610612765,DET,Detroit Pistons,42,83,0.506,10,23,0.435,9,12,0.750,11,24,35,23,20.0,10,3,8,27,15,103,-9.0,105.9,110.8,116.7,120.4,-10.8,-9.7,0.548,1.15,17.4,0.405,0.609,0.511,0.215,0.566,0.583,96.6,93.0,77.50,93,0.434,1,SG,29.0,-3.5,213.0,1,1.175559,0.054677,0.136693,1,4,Donovan Mitchell

In [ ]:
import sys
sys.path.append('src')
from src.utils.pbp_stats import NBAPlayByPlay

# Pass a list of game IDs
game_ids = p26['GAME_ID'].unique().tolist()

pbp = NBAPlayByPlay(game_ids).fetch(
    delay=2,           # seconds between requests (default 0.3)
    workers=5,           # parallel threads (default 8)
    batch_size=100,      # games per batch (default 100)
    checkpoint_path='C:\\Users\\alexg\\OneDrive\\Documents\\NBA-Prop-Predictor\\notebooks\\pbp_checkpoint.csv',  # saves progress so you can resume
    run_all_batches=True # set False to stop after first batch
).build()
df = pbp.get_df()
# df.to_csv(project_root / 'data/raw/pbp_season_stats/S22.csv', index=False)
df

✓ Checkpoint loaded — 0/85 games done, 85 remaining

── Batch 1/1 (85 games) ──
  … 25/85 games in batch
  … 50/85 games in batch
  … 75/85 games in batch
  ✓ Batch 1 done — checkpoint saved (43289 rows total)
✓ Built — shape: (43289, 24)

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0042500131,2,PT12M00.00S,1,0,,0,,,0,0,0,,0,0,0,0,,Start of 1st Period (1:10 PM EST),period,start,1,0,1
1,0042500131,4,PT12M00.00S,1,1610612739,CLE,1628386,Allen,J. Allen,0,0,0,,0,,,0,h,Jump Ball Allen vs. Poeltl: Tip to Harden,Jump Ball,,1,0,2
2,0042500131,7,PT11M45.00S,1,1610612739,CLE,1630596,Mobley,E. Mobley,0,0,0,,0,,,0,h,Mobley Out of Bounds - Bad Pass Turnover Turno...,Turnover,Out of Bounds - Bad Pass Turnover,1,0,3
3,0042500131,8,PT11M30.00S,1,1610612761,TOR,1627742,Ingram,B. Ingram,-53,168,18,Missed,1,,,0,v,MISS Ingram 18' Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,2,4
4,0042500131,9,PT11M27.00S,1,1610612739,CLE,1630596,Mobley,E. Mobley,0,0,0,,0,,,0,h,Mobley REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43284,0042500405,764,PT00M07.70S,4,1610612752,NYK,1630574,Hukporti,A. Hukporti,0,0,0,,0,,,0,v,SUB: Shamet FOR Hukporti,Substitution,,0,0,550
43285,0042500405,768,PT00M07.70S,4,1610612752,NYK,1628384,Anunoby,O. Anunoby,0,0,0,,0,90,94,184,v,Anunoby Free Throw 2 of 2 (11 PTS),Free Throw,Free Throw 2 of 2,1,0,551
43286,0042500405,769,PT00M02.00S,4,1610612759,SAS,1641705,Wembanyama,V. Wembanyama,-186,178,26,Missed,1,,,0,h,MISS Wembanyama 26' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,552
43287,0042500405,770,PT00M02.00S,4,1610612752,NYK,1628384,Anunoby,O. Anunoby,0,0,0,,0,,,0,v,Anunoby REBOUND (Off:0 Def:8),Rebound,Unknown,1,0,553
43288,0042500405,771,PT00M00.00S,4,0,,0,,,0,0,0,,0,90,94,184,,End of 4th Period (11:30 PM EST),period,end,1,0,554

In [5]:
df.to_parquet("p26_pbp.parquet", compression="snappy")

In [10]:
s25 = pd.read_parquet(project_root / 'data/raw/pbp_stats/s25_pbp.parquet')
s25.head()

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,yLegacy,shotDistance,shotResult,isFieldGoal,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022400061,2,PT12M00.00S,1,0,,0,,,0,0,0,,0,0,0,0,,Start of 1st Period (7:36 PM EST),period,start,0,0,1
1,0022400061,4,PT12M00.00S,1,1610612738,BOS,201143,Horford,A. Horford,0,0,0,,0,,,0,h,Jump Ball Horford vs. Towns: Tip to White,Jump Ball,,1,0,2
2,0022400061,7,PT11M48.00S,1,1610612738,BOS,1628369,Tatum,J. Tatum,141,228,27,Made,1,3,0,3,h,Tatum 27' 3PT Pullup Jump Shot (3 PTS) (White ...,Made Shot,Pullup Jump shot,1,3,3
3,0022400061,9,PT11M27.00S,1,1610612752,NYK,1628384,Anunoby,O. Anunoby,36,46,6,Made,1,3,2,5,v,Anunoby 6' Driving Layup (2 PTS) (Brunson 1 AST),Made Shot,Driving Layup Shot,1,2,4
4,0022400061,11,PT11M16.00S,1,1610612738,BOS,1628369,Tatum,J. Tatum,-83,242,26,Missed,1,,,0,h,MISS Tatum 26' 3PT Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,3,5

In [23]:
game_df = s25[s25['gameId'] == '0022400061']
game_df = cleanPlaybyPlay(game_df)
# game_df.to_parquet("example_game.parquet", compression="snappy")
game_df['subType'].unique()

/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/features/feature_engineer/pbp_features.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MIN_SECONDS'] = df['clock'].apply(lambda x: isodate.parse_duration(x).total_seconds())
/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/features/feature_engineer/pbp_features.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['scoreHome'] = df['scoreHome'].replace('', np.nan).ffill()
/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/features/feature_engineer/pbp_features.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['scoreAway'] = df['scoreAway'].replace('', np.nan).ffill()

array(['start', '', 'Pullup Jump shot', 'Driving Layup Shot', 'Unknown',
       'Running Layup Shot', 'Driving Floating Jump Shot', 'Jump Shot',
       'Turnaround Hook Shot', 'Regular', 'Cutting Layup Shot',
       'Turnaround Fadeaway shot', 'Lost Ball', 'Running Dunk Shot',
       'Layup Shot', 'Tip Layup Shot', 'Fadeaway Jump Shot', 'Shooting',
       'Free Throw 1 of 2', 'Normal Rebound', 'Free Throw 2 of 2',
       'Bad Pass', 'Driving Finger Roll Layup Shot',
       'Step Back Jump shot', 'Putback Layup Shot', 'Personal',
       'Support Ruling', 'Running Pull-Up Jump Shot', 'Free Throw 1 of 1',
       'Defensive Goaltending', 'Driving Hook Shot', 'end',
       'Offensive Charge', 'Offensive Foul Turnover',
       'Floating Jump shot', 'Step Out of Bounds Turnover',
       'Running Jump Shot', 'Cutting Dunk Shot',
       'Driving Reverse Layup Shot', 'Out of Bounds Lost Ball Turnover',
       'Defense 3 Second', 'Free Throw Technical',
       'Driving Floating Bank Jump Shot', '8 Second Violation',
       'Tip Dunk Shot', 'Loose Ball', 'Kicked Ball',
       'Out of Bounds - Bad Pass Turnover', 'Shot Clock Turnover'],
      dtype=object)

In [24]:
game_df['actionType'].unique()

array(['period', 'Jump Ball', 'Made Shot', 'Missed Shot', 'Rebound',
       'Timeout', 'Turnover', '', 'Foul', 'Free Throw', 'Substitution',
       'Instant Replay', 'Violation'], dtype=object)