In [1]:
import pandas as pd
import sys
import os
from pathlib import Path

project_root = Path.cwd().parent.parent
project_root_str = str(project_root)

if project_root_str not in sys.path:
    sys.path.insert(0, project_root_str)

os.chdir(project_root_str)

from src.utils.fetch_player_stats import *
from src.utils.fetch_team_stats import *
# from src.utils.helper_functions import *

## Fetches Player Gamelogs

In [2]:
nba = FetchPlayersStats()
data = nba.getCompleteStats(
    season='2025-26', 
    season_type='Regular Season', 
    sleep_time=2, 
    max_workers=5,
    batch_limit=100,
    complete_cache_file='data/raw/seaon_stats/S26.csv',
    include_playbyplay=False
)
data.tail()

/Users/alexgonzalez/Documents/NBA-Prop-Predictor/src/utils/fetch_player_stats.py:737: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  cache = pd.read_csv(complete_cache_file, dtype={'GAME_ID':str})

Processing 47 games (limited by batch_limit=100)

Processing batch 1/5 (10 games)
Completed batch 1/5

Processing batch 2/5 (10 games)
[RETRY 1] Matchup stats for 0022500900: list index out of range
[RETRY 2] Matchup stats for 0022500900: list index out of range
[ERROR] Failed fetching matchup for 0022500900: list index out of range
[RETRY 1] Matchup stats for 0022500899: list index out of range
[RETRY 2] Matchup stats for 0022500899: list index out of range
[ERROR] Failed fetching matchup for 0022500899: list index out of range
[RETRY 1] Matchup stats for 0022500901: list index out of range
[RETRY 2] Matchup stats for 0022500901: list index out of range
[ERROR] Failed fetching matchup for 0022500901: list index out of range
[RETRY 1] Matchup stats for 0022500902: list index out of range
[RETRY 2] Matchup stats for 0022500902: list index out of range
[ERROR] Failed fetching matchup for 0022500902: list index out of range
[RETRY 1] Matchup stats for 0022500903: list index out of range
[RETRY 2] Matchup stats for 0022500903: list index out of range
[ERROR] Failed fetching matchup for 0022500903: list index out of range
[RETRY 1] Matchup stats for 0022500904: list index out of range
[RETRY 2] Matchup stats for 0022500904: list index out of range
[ERROR] Failed fetching matchup for 0022500904: list index out of range
[RETRY 1] Matchup stats for 0022500905: list index out of range
[RETRY 2] Matchup stats for 0022500905: list index out of range
[ERROR] Failed fetching matchup for 0022500905: list index out of range
[RETRY 1] Matchup stats for 0022500907: list index out of range
[RETRY 2] Matchup stats for 0022500907: list index out of range
[ERROR] Failed fetching matchup for 0022500907: list index out of range
[RETRY 1] Matchup stats for 0022500906: list index out of range
[RETRY 2] Matchup stats for 0022500906: list index out of range
[ERROR] Failed fetching matchup for 0022500906: list index out of range
Completed batch 2/5

Processing batch 3/5 (10 games)
Completed batch 3/5

Processing batch 4/5 (10 games)
Completed batch 4/5

Processing batch 5/5 (7 games)
Completed batch 5/5

Merging team stats...
Cache updated. Total games now: 963

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,...,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
20881,Nicolas Batum,201587,LAC vs. NYK,LAC,1610612746,NYK,1,0022500935,2026-03-09,W,...,114.5,118.0,46.0,90.0,0.511,51.0,32.0,5.0,1.0,20.0
20882,Ariel Hukporti,1630574,NYK @ LAC,NYK,1610612752,LAC,0,0022500935,2026-03-09,L,...,121.8,126.0,43.0,93.0,0.462,36.0,25.0,12.0,4.0,8.0
20883,Kris Dunn,1627739,LAC vs. NYK,LAC,1610612746,NYK,1,0022500935,2026-03-09,W,...,114.5,118.0,46.0,90.0,0.511,51.0,32.0,5.0,1.0,20.0
20884,Jalen Brunson,1628973,NYK @ LAC,NYK,1610612752,LAC,0,0022500935,2026-03-09,L,...,121.8,126.0,43.0,93.0,0.462,36.0,25.0,12.0,4.0,8.0
20885,Derrick Jones Jr.,1627884,LAC vs. NYK,LAC,1610612746,NYK,1,0022500935,2026-03-09,W,...,114.5,118.0,46.0,90.0,0.511,51.0,32.0,5.0,1.0,20.0

In [3]:
pd.set_option('display.max_columns', None)

# s19_regular = pd.read_csv('data/raw/seaon_stats/S19.csv')
# s20_regular = pd.read_csv('data/raw/seaon_stats/S20.csv')
# s21_regular = pd.read_csv('data/raw/seaon_stats/S21.csv')
s22_regular = pd.read_csv('data/raw/seaon_stats/S22.csv')
s23_regular = pd.read_csv('data/raw/seaon_stats/S23.csv')
s24_regular = pd.read_csv('data/raw/seaon_stats/S24.csv')
s25_regular = pd.read_csv('data/raw/seaon_stats/S25.csv')
s26_regular = pd.read_csv('data/raw/seaon_stats/S26.csv')
s26_regular.sample()

/var/folders/9q/5_554qsx5z70w9d_vkmvjg0h0000gn/T/ipykernel_16663/1752843501.py:10: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  s26_regular = pd.read_csv('data/raw/seaon_stats/S26.csv')

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK_x,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLK_y,BLKA,PF,PFD,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
1507,Kentavious Caldwell-Pope,203484,MEM @ PHX,MEM,1610612763,PHX,0,22500137,2025-10-29,W,11,5,2,5,12,0.417,1,2,0.5,0,0,NaN,0,2,1,0,0,6,23.9,0.917,0.458333,F,NaN,100.0,100.0,85.4,85.4,14.6,0.0,0.091,0.047,0.417,0.458,0.0,0.25,0.458,104.87,104.87,0.205,41.0,87.39,0.25,18:46,4.14,1.22,0,4,4,35,0,0,21,0,2,0.0,5,10,0.5,1,1,1.0,0.833,0.167,0.727,0.364,0.273,0.182,0.0,0.182,0.364,0.75,0.25,1.0,0.0,0.8,0.2,3.0,4.0,2.0,3.0,8.0,6.59,0.75,0.667,0.75,0.667,1.21,0.15,0.0,0.0,0.0,2.0,0.0,2.0,4.0,3.0,2.0,2.0,18.0,0.0,0.0,0.0,2.0,22025.0,Memphis Grizzlies,2025-10-29,MEM @ PHX,W,240.0,44.0,93.0,0.473,15.0,38.0,0.395,11.0,13.0,0.846,9.0,32.0,41.0,31.0,12.0,3.0,17.0,17.0,114.0,1.0,1.0,106.6,106.6,106.6,1.610613e+09,106.8,105.9,107.1,106.1,113.0,41.0,86.0,0.477,40.0,25.0,11.0,4.0,21.0

## Fetching play by play data for model v2

In [ ]:
# nba = FetchPlayersStats()
# data = nba.getCompleteStats(
#     season='2025-26', 
#     season_type='Regular Season', 
#     sleep_time=1, 
#     max_workers=5,
#     batch_limit=50,
#     complete_cache_file='data/raw/seaon_stats/S26v2.csv',
#     include_playbyplay=True
# )
# data.tail()

## Assign features for regular season data

In [4]:
# data = [s22_regular,s23_regular,s24_regular, s25_regular, s26_regular]
# seasons = [2022,2023,2024, 2025, 2026]
data = [s26_regular]
seasons = [2026]

output_dir = os.path.join(project_root, 'data', 'processed', 'training')
os.makedirs(output_dir, exist_ok=True)

for season_data, year in zip(data, seasons):
    print(f"Processing year {year}...")
    
    # Process features
    processed_data = process_season_features(
        season_data, 
        prop_type='PTS',
        year=year
    )
    
    # Save file
    output_path = os.path.join(output_dir, f'PTS_TRAIN_{str(year)[-2:]}.csv')
    processed_data.to_csv(output_path)
    print(f"Completed {year}")

Processing year 2026...
Loading position cache...
Loaded 1251 players from cache
Found 530 unique players, 2 need to be fetched
Fetching 2 new players using 4 threads...
Fetched PLAYER_ID 1643133... (1/2)
Fetched PLAYER_ID 1642955... (2/2)
Saving updated cache...
Cache saved with 1253 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Completed 2026