In [1]:
import pandas as pd
import sys
import os
from pathlib import Path

project_root = Path.cwd().parent.parent
project_root_str = str(project_root)

if project_root_str not in sys.path:
    sys.path.insert(0, project_root_str)

os.chdir(project_root_str)

from src.utils.fetch_player_stats import *
from src.utils.fetch_team_stats import *
from src.utils.helper_functions import *

## Fetches Player Gamelogs

In [2]:
nba = FetchPlayersStats()
data = nba.getCompleteStats(
    season='2025-26', 
    season_type='Regular Season', 
    sleep_time=2, 
    max_workers=5,
    batch_limit=100,
    complete_cache_file='data/raw/seaon_stats/S26.csv',
    include_playbyplay=False
)
data.tail()

Processing 15 games (limited by batch_limit=100)

Processing batch 1/2 (10 games)
Completed batch 1/2

Processing batch 2/2 (5 games)
[RETRY 1] Matchup stats for 0022501226: list index out of range
[RETRY 2] Matchup stats for 0022501226: list index out of range
[ERROR] Failed fetching matchup for 0022501226: list index out of range
[RETRY 1] Matchup stats for 0022501222: list index out of range
[RETRY 2] Matchup stats for 0022501222: list index out of range
[ERROR] Failed fetching matchup for 0022501222: list index out of range
[RETRY 1] Matchup stats for 0022501224: list index out of range
[RETRY 2] Matchup stats for 0022501224: list index out of range
[ERROR] Failed fetching matchup for 0022501224: list index out of range
[RETRY 1] Matchup stats for 0022501225: list index out of range
[RETRY 2] Matchup stats for 0022501225: list index out of range
[ERROR] Failed fetching matchup for 0022501225: list index out of range
Completed batch 2/2

Merging team stats...
Cache updated. Total games now: 387

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,...,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
8460,Alperen Sengun,1630578,HOU @ DEN,HOU,1610612745,DEN,0,0022501225,2025-12-15,L,...,123.6,128.0,43.0,85.0,0.506,38.0,24.0,10.0,4.0,11.0
8461,Steven Adams,203500,HOU @ DEN,HOU,1610612745,DEN,0,0022501225,2025-12-15,L,...,123.6,128.0,43.0,85.0,0.506,38.0,24.0,10.0,4.0,11.0
8462,Jonas Valančiūnas,202685,DEN vs. HOU,DEN,1610612743,HOU,1,0022501225,2025-12-15,W,...,115.3,125.0,47.0,93.0,0.505,46.0,29.0,7.0,8.0,16.0
8463,Nikola Jokić,203999,DEN vs. HOU,DEN,1610612743,HOU,1,0022501225,2025-12-15,W,...,115.3,125.0,47.0,93.0,0.505,46.0,29.0,7.0,8.0,16.0
8464,Reed Sheppard,1642263,HOU @ DEN,HOU,1610612745,DEN,0,0022501225,2025-12-15,L,...,123.6,128.0,43.0,85.0,0.506,38.0,24.0,10.0,4.0,11.0

In [4]:
pd.set_option('display.max_columns', None)

# s19_regular = pd.read_csv('data/raw/seaon_stats/S19.csv')
# s20_regular = pd.read_csv('data/raw/seaon_stats/S20.csv')
# s21_regular = pd.read_csv('data/raw/seaon_stats/S21.csv')
s22_regular = pd.read_csv('data/raw/seaon_stats/S22.csv')
s23_regular = pd.read_csv('data/raw/seaon_stats/S23.csv')
s24_regular = pd.read_csv('data/raw/seaon_stats/S24.csv')
s25_regular = pd.read_csv('data/raw/seaon_stats/S25.csv')
s26_regular = pd.read_csv('data/raw/seaon_stats/S26.csv')
s26_regular.sample()

,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK_x,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,OFF_RATING,E_OFF_RATING,DEF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,matchupFieldGoalsPercentage,matchupThreePointersPercentage,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLK_y,BLKA,PF,PFD,TEAM_SEASON_ID,TEAM_NAME,TEAM_GAME_DATE,TEAM_MATCHUP,TEAM_WL,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,VIDEO_AVAILABLE,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV
248,Kris Murray,1631200,POR vs. MIN,POR,1610612757,MIN,1,22500089,2025-10-22,L,7,0,0,2,3,0.667,1,2,0.5,2,2,1.0,0,0,0,0,1,2,6.0,1.804,0.833333,NaN,NaN,126.8,126.8,119.0,119.0,7.8,0.0,0.0,0.0,0.0,0.833,0.0,0.102,0.902,107.39,107.39,0.049,41.0,89.49,0.102,18:33,4.61,1.39,1,2,3,9,0,0,4,1,1,1.0,1,2,0.5,2,3,0.667,0.333,0.667,0.286,0.0,0.429,0.0,0.286,0.0,0.286,1.0,0.0,1.0,0.0,1.0,0.0,2.0,7.0,0.0,1.0,4.0,7.47,0.286,0.0,0.286,0.0,0.54,0.13,0.0,0.0,0.0,0,0,0,2,8,7,11,18,0,0,1,1,22025,Portland Trail Blazers,2025-10-22,POR vs. MIN,L,240.0,36.0,90.0,0.4,13.0,42.0,0.31,29.0,35.0,0.829,7.0,32.0,39.0,25.0,10.0,3.0,16.0,17.0,114.0,-4.0,1.0,110.0,110.0,110.0,1.610613e+09,99.7,103.1,108.0,111.8,118.0,42.0,86.0,0.488,45.0,21.0,10.0,10.0,19.0

## Fetching play by play data for model v2

In [4]:
# nba = FetchPlayersStats()
# data = nba.getCompleteStats(
#     season='2025-26', 
#     season_type='Regular Season', 
#     sleep_time=1, 
#     max_workers=5,
#     batch_limit=50,
#     complete_cache_file='data/raw/seaon_stats/S26v2.csv',
#     include_playbyplay=True
# )
# data.tail()

## Assign features for regular season data

In [5]:
# data = [s22_regular,s23_regular,s24_regular, s25_regular, s26_regular]
# seasons = [2022,2023,2024, 2025, 2026]
data = [s25_regular, s26_regular]
seasons = [2025, 2026]

output_dir = os.path.join(project_root, 'data', 'processed', 'training')
os.makedirs(output_dir, exist_ok=True)

for season_data, year in zip(data, seasons):
    print(f"Processing year {year}...")
    
    # Process features
    processed_data = process_season_features(
        season_data, 
        prop_type='PTS',
        year=year
    )
    
    # Save file
    output_path = os.path.join(output_dir, f'PTS_TRAIN_{str(year)[-2:]}.csv')
    processed_data.to_csv(output_path)
    print(f"Completed {year}")

Processing year 2025...
Loading position cache...
Loaded 1245 players from cache
Found 569 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1245 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Completed 2025
Processing year 2026...
Loading position cache...
Loaded 1245 players from cache
Found 499 unique players, 0 need to be fetched
Saving updated cache...
Cache saved with 1245 players
Applying positions to dataset...
Creating position flags...
Position assignment completed!
Completed 2026