In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sys
import os


# feature_path = os.path.abspath(r"C:\Users\alexg\OneDrive\Documents\NBA-Prop-Predictor")
feature_path = os.path.abspath('/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor')
if feature_path not in sys.path:
    sys.path.append(feature_path)

from FEATURE_ENGINEERING.features import *
from PROPS_EV.calculateEVS import *
from BACKTEST.backtest import *

### Load Model

In [4]:
model = joblib.load('Models/xgbModel.pkl')
features = joblib.load('Models/top_features.pkl')

### Load Data

In [5]:
pd.set_option('display.max_columns', None)
eplison = 0.000001

s25 = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_25.csv')
s25['EXPECTED_USAGE_MIN'] = s25['USG_PCT_ROLLING_AVG_5'] * (s25['MIN_ROLLING_AVG_5'] + eplison)

s24 = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_24.csv')
s24['EXPECTED_USAGE_MIN'] = s24['USG_PCT_ROLLING_AVG_5'] * (s24['MIN_ROLLING_AVG_5'] + eplison)
df = pd.concat([s25, s24]).sort_values(by='GAME_DATE')


date = '2025-03-11'
df = df[df['GAME_DATE'] < date]

dfsData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/dfs_data.csv')
dfsData = dfsData[(dfsData['BOOKMAKER'] == 'prizepicks') & (dfsData['GAME_DATE'] == date) & (dfsData['CATEGORY'] == 'player_points')]
df.tail()

/var/folders/nw/9w4r5hrd05s122kt5hg_t8bw0000gn/T/ipykernel_14676/4012596075.py:15: DtypeWarning: Columns (11,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  dfsData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/dfs_data.csv')

,Unnamed: 0,Unnamed: 0.2,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,E_OFF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_SEASON_ID_x,whos_favored,spread,total,team_is_favored,team_spread,OPP_BLOWOUT_RISK,TEAM_NAME,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,AGE,FREQ_FG3,FG3M_main,FG3A_main,FG3_PCT_main,NS_FG3_PCT,PLUS_MINUS_FG3,FREQ_FG2,FG2M,FG2A,FG2_PCT,NS_FG2_PCT,PLUS_MINUS_FG2,FREQ_LT_06,FGM_LT_06,FGA_LT_06,LT_06_PCT,NS_LT_06_PCT,PLUS_MINUS_LT_06,FREQ_LT_10,FGM_LT_10,FGA_LT_10,LT_10_PCT,NS_LT_10_PCT,PLUS_MINUS_LT_10,FREQ_GT_15,FGM_GT_15,FGA_GT_15,GT_15_PCT,NS_GT_15_PCT,PLUS_MINUS_GT_15,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,STARTING,BLOWOUT_RISK,TEAM_IMPLIED_PTS_FAV,TEAM_IMPLIED_PTS_UND,HEIGHT,WEIGHT,GUARD,FORWARD,CENTER,TEAM_DAYS_REST,PLAYER_DAYS_REST,TEAM_B2B,IS_BACK_TO_BACK,PLAYER_MISSED_LAST,TEAM_GUARD_DEF_FG_PCT_ALLOWED,TEAM_GUARD_DEF_3PT_PCT_ALLOWED,TEAM_GUARD_PTS_ALLOWED_PER_MIN,TEAM_FORWARD_DEF_FG_PCT_ALLOWED,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED,TEAM_FORWARD_PTS_ALLOWED_PER_MIN,TEAM_CENTER_DEF_FG_PCT_ALLOWED,TEAM_CENTER_DEF_3PT_PCT_ALLOWED,TEAM_CENTER_PTS_ALLOWED_PER_MIN,OPP_GUARD_DEF_FG_PCT_ALLOWED,OPP_GUARD_DEF_3PT_PCT_ALLOWED,OPP_GUARD_PTS_ALLOWED_PER_MIN,OPP_FORWARD_DEF_FG_PCT_ALLOWED,OPP_FORWARD_DEF_3PT_PCT_ALLOWED,OPP_FORWARD_PTS_ALLOWED_PER_MIN,OPP_CENTER_DEF_FG_PCT_ALLOWED,OPP_CENTER_DEF_3PT_PCT_ALLOWED,OPP_CENTER_PTS_ALLOWED_PER_MIN,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_GUARD_FREQ_FG3,TEAM_GUARD_FG3_PCT_main,TEAM_GUARD_NS_FG3_PCT,TEAM_GUARD_PLUS_MINUS_FG3,TEAM_GUARD_FREQ_FG2,TEAM_GUARD_FG2_PCT,TEAM_GUARD_NS_FG2_PCT,TEAM_GUARD_PLUS_MINUS_FG2,TEAM_GUARD_FREQ_LT_06,TEAM_GUARD_LT_06_PCT,TEAM_GUARD_NS_LT_06_PCT,TEAM_GUARD_PLUS_MINUS_LT_06,TEAM_GUARD_FREQ_LT_10,TEAM_GUARD_LT_10_PCT,TEAM_GUARD_NS_LT_10_PCT,TEAM_GUARD_PLUS_MINUS_LT_10,TEAM_GUARD_FREQ_GT_15,TEAM_GUARD_GT_15_PCT,TEAM_GUARD_NS_GT_15_PCT,TEAM_GUARD_PLUS_MINUS_GT_15,TEAM_FORWARD_FREQ_FG3,TEAM_FORWARD_FG3_PCT_main,TEAM_FORWARD_NS_FG3_PCT,TEAM_FORWARD_PLUS_MINUS_FG3,TEAM_FORWARD_FREQ_FG2,TEAM_FORWARD_FG2_PCT,TEAM_FORWARD_NS_FG2_PCT,TEAM_FORWARD_PLUS_MINUS_FG2,TEAM_FORWARD_FREQ_LT_06,TEAM_FORWARD_LT_06_PCT,TEAM_FORWARD_NS_LT_06_PCT,TEAM_FORWARD_PLUS_MINUS_LT_06,TEAM_FORWARD_FREQ_LT_10,TEAM_FORWARD_LT_10_PCT,TEAM_FORWARD_NS_LT_10_PCT,TEAM_FORWARD_PLUS_MINUS_LT_10,TEAM_FORWARD_FREQ_GT_15,TEAM_FORWARD_GT_15_PCT,TEAM_FORWARD_NS_GT_15_PCT,TEAM_FORWARD_PLUS_MINUS_GT_15,TEAM_CENTER_FREQ_FG3,TEAM_CENTER_FG3_PCT_main,TEAM_CENTER_NS_FG3_PCT,TEAM_CENTER_PLUS_MINUS_FG3,TEAM_CENTER_FREQ_FG2,TEAM_CENTER_FG2_PCT,TEAM_CENTER_NS_FG2_PCT,TEAM_CENTER_PLUS_MINUS_FG2,TEAM_CENTER_FREQ_LT_06,TEAM_CENTER_LT_06_PCT,TEAM_CENTER_NS_LT_06_PCT,TEAM_CENTER_PLUS_MINUS_LT_06,TEAM_CENTER_FREQ_LT_10,TEAM_CENTER_LT_10_PCT,TEAM_CENTER_NS_LT_10_PCT,TEAM_CENTER_PLUS_MINUS_LT_10,TEAM_CENTER_FREQ_GT_15,TEAM_CENTER_GT_15_PCT,TEAM_CENTER_NS_GT_15_PCT,TEAM_CENTER_PLUS_MINUS_GT_15,OPP_GUARD_FREQ_FG3,OPP_GUARD_FG3_PCT_main,OPP_GUARD_NS_FG3_PCT,OPP_GUARD_PLUS_MINUS_FG3,OPP_GUARD_FREQ_FG2,OPP_GUARD_FG2_PCT,OPP_GUARD_NS_FG2_PCT,OPP_GUARD_PLUS_MINUS_FG2,OPP_GUARD_FREQ_LT_06,OPP_GUARD_LT_06_PCT,OPP_GUARD_NS_LT_06_PCT,OPP_GUARD_PLUS_MINUS_LT_06,OPP_GUARD_FREQ_LT_10,OPP_GUARD_LT_10_PCT,OPP_GUARD_NS_LT_10_PCT,OPP_GUARD_PLUS_MINUS_LT_10,OPP_GUARD_FREQ_GT_15,OPP_GUARD_GT_15_PCT,OPP_GUARD_NS_GT_15_PCT,OPP_GUARD_PLUS_MINUS_GT_15,OPP_FORWARD_FREQ_FG3,OPP_FORWARD_FG3_PCT_main,OPP_FORWARD_NS_FG3_PCT,OPP_FORWARD_PLUS_MINUS_FG3,OPP_FORWARD_FREQ_FG2,OPP_FORWARD_FG2_PCT,OPP_FORWARD_NS_FG2_PCT,OPP_FORWARD_PLUS_MINUS_FG2,OPP_FORWARD_FREQ_LT_06,OPP_FORWARD_LT_06_PCT,OPP_FORWARD_NS_LT_06_PCT,OPP_FORWARD_PLUS_MINUS_LT_06,OPP_FORWARD_FREQ_LT_10,OPP_FORWARD_LT_10_PCT,OPP_FORWARD_NS_LT_10_PCT,OPP_FORWARD_PLUS_MINUS_LT_10,OPP_FORWARD_FREQ_GT_15,OPP_FORWARD_GT_15_PCT,OPP_FORWARD_NS_GT_15_PCT,OPP_FORWARD_PLUS_MINUS_GT_15,OPP_CENTER_FREQ_FG3,OPP_CENTER_FG3_PCT_main,OPP_CENTER_NS_FG3_PCT,OPP_CENTER_PLUS_MINUS_FG3,OPP_CENTER_FREQ_FG2,OPP_CENTER_FG2_PCT,OPP_CENTER_NS_FG2_PCT,OPP_CENTER_PLUS_MINUS_FG2,OPP_CENTER_FREQ_LT_06,OPP_CENTER_LT_06_PCT,OPP_CENTER_NS_LT_06_PCT,OPP_CENTER_PLUS_MINUS_LT_06,OPP_CENTER_FREQ_LT_10,OPP_CENTER_LT_10_PCT,OPP_CENTER_NS_LT_10_PCT,OPP_CENTER_PLUS_MINUS_LT_10,OPP_CENTER_FREQ_GT_15,OPP_CENTER_GT_15_PCT,OPP_CENTER_NS_GT_15_PCT,OPP_CENTER_PLUS_MINUS_GT_15,PTS_ROLLING_AVG_5,FGA_ROLLING_AVG_5,FG3A_ROLLING_AVG_5,FTM_ROLLING_AVG_5,FGM_ROLLING_AVG_5,FG3M_ROLLING_AVG_5,FG_PCT_ROLLING_AVG_5,EFG_PCT_ROLLING_AVG_5,TS_PCT_ROLLING_AVG_5,USG_PCT_ROLLING_AVG_5,E_USG_PCT_ROLLING_AVG_5,MIN_ROLLING_AVG_5,POSS_ROLLING_AVG_5,PACE_ROLLING_AVG_5,E_PACE_ROLLING_AVG_5,percentagePointsPaint_ROLLING_AVG_5,percentagePointsFreeThrow_ROLLING_AVG_5,percentageFieldGoalsAttempted2pt_ROLLING_AVG_5,percentageFieldGoalsAttempted3pt_ROLLING_AVG_5,percentagePoints2pt_ROLLING_AVG_5,percentagePoints3pt_ROLLING_AVG_5,percentagePointsMidrange2pt_ROLLING_AVG_5,percentageAssisted2pt_ROLLING_AVG_5,percentageAssisted3pt_ROLLING_AVG_5,percentageUnassisted3pt_ROLLING_AVG_5,percentageAssistedFGM_ROLLING_AVG_5,percentageUnassistedFGM_ROLLING_AVG_5,percentagePointsOffTurnovers_ROLLING_AVG_5,UFGA_ROLLING_AVG_5,DFGM_ROLLING_AVG_5,DFGA_ROLLING_AVG_5,ORBC_ROLLING_AVG_5,DRBC_ROLLING_AVG_5,RBC_ROLLING_AVG_5,DREB_PCT_ROLLING_AVG_5,SAST_ROLLING_AVG_5,CFGM_ROLLING_AVG_5,CFGA_ROLLING_AVG_5,SPD_ROLLING_AVG_5,DIST_ROLLING_AVG_5,AST_PCT_ROLLING_AVG_5,NET_RATING_ROLLING_AVG_5,PIE_ROLLING_AVG_5,PLUS_MINUS_ROLLING_AVG_5,FANTASY_PTS_ROLLING_AVG_5,PTS_2ND_CHANCE_ROLLING_AVG_5,PTS_PAINT_ROLLING_AVG_5,OPP_PTS_PAINT_ROLLING_AVG_5,PFD_ROLLING_AVG_5,STL_ROLLING_AVG_5,BLK_ROLLING_AVG_5,TOV_ROLLING_AVG_5,PF_ROLLING_AVG_5,PTS_ROLLING_AVG_10,FGA_ROLLING_AVG_10,FG3A_ROLLING_AVG_10,FTM_ROLLING_AVG_10,FGM_ROLLING_AVG_10,FG3M_ROLLING_AVG_10,FG_PCT_ROLLING_AVG_10,EFG_PCT_ROLLING_AVG_10,TS_PCT_ROLLING_AVG_10,USG_PCT_ROLLING_AVG_10,E_USG_PCT_ROLLING_AVG_10,MIN_ROLLING_AVG_10,POSS_ROLLING_AVG_10,PACE_ROLLING_AVG_10,E_PACE_ROLLING_AVG_10,percentagePointsPaint_ROLLING_AVG_10,percentagePointsFreeThrow_ROLLING_AVG_10,percentageFieldGoalsAttempted2pt_ROLLING_AVG_10,percentageFieldGoalsAttempted3pt_ROLLING_AVG_10,percentagePoints2pt_ROLLING_AVG_10,percentagePoints3pt_ROLLING_AVG_10,percentagePointsMidrange2pt_ROLLING_AVG_10,percentageAssisted2pt_ROLLING_AVG_10,percentageAssisted3pt_ROLLING_AVG_10,percentageUnassisted3pt_ROLLING_AVG_10,percentageAssistedFGM_ROLLING_AVG_10,percentageUnassistedFGM_ROLLING_AVG_10,percentagePointsOffTurnovers_ROLLING_AVG_10,UFGA_ROLLING_AVG_10,DFGM_ROLLING_AVG_10,DFGA_ROLLING_AVG_10,ORBC_ROLLING_AVG_10,DRBC_ROLLING_AVG_10,RBC_ROLLING_AVG_10,DREB_PCT_ROLLING_AVG_10,SAST_ROLLING_AVG_10,CFGM_ROLLING_AVG_10,CFGA_ROLLING_AVG_10,SPD_ROLLING_AVG_10,DIST_ROLLING_AVG_10,AST_PCT_ROLLING_AVG_10,NET_RATING_ROLLING_AVG_10,PIE_ROLLING_AVG_10,PLUS_MINUS_ROLLING_AVG_10,FANTASY_PTS_ROLLING_AVG_10,PTS_2ND_CHANCE_ROLLING_AVG_10,PTS_PAINT_ROLLING_AVG_10,OPP_PTS_PAINT_ROLLING_AVG_10,PFD_ROLLING_AVG_10,STL_ROLLING_AVG_10,BLK_ROLLING_AVG_10,TOV_ROLLING_AVG_10,PF_ROLLING_AVG_10,PTS_ROLLING_AVG_15,FGA_ROLLING_AVG_15,FG3A_ROLLING_AVG_15,FTM_ROLLING_AVG_15,FGM_ROLLING_AVG_15,FG3M_ROLLING_AVG_15,FG_PCT_ROLLING_AVG_15,EFG_PCT_ROLLING_AVG_15,TS_PCT_ROLLING_AVG_15,USG_PCT_ROLLING_AVG_15,E_USG_PCT_ROLLING_AVG_15,MIN_ROLLING_AVG_15,POSS_ROLLING_AVG_15,PACE_ROLLING_AVG_15,E_PACE_ROLLING_AVG_15,percentagePointsPaint_ROLLING_AVG_15,percentagePointsFreeThrow_ROLLING_AVG_15,percentageFieldGoalsAttempted2pt_ROLLING_AVG_15,percentageFieldGoalsAttempted3pt_ROLLING_AVG_15,percentagePoints2pt_ROLLING_AVG_15,percentagePoints3pt_ROLLING_AVG_15,percentagePointsMidrange2pt_ROLLING_AVG_15,percentageAssisted2pt_ROLLING_AVG_15,percentageAssisted3pt_ROLLING_AVG_15,percentageUnassisted3pt_ROLLING_AVG_15,percentageAssistedFGM_ROLLING_AVG_15,percentageUnassistedFGM_ROLLING_AVG_15,percentagePointsOffTurnovers_ROLLING_AVG_15,UFGA_ROLLING_AVG_15,DFGM_ROLLING_AVG_15,DFGA_ROLLING_AVG_15,ORBC_ROLLING_AVG_15,DRBC_ROLLING_AVG_15,RBC_ROLLING_AVG_15,DREB_PCT_ROLLING_AVG_15,SAST_ROLLING_AVG_15,CFGM_ROLLING_AVG_15,CFGA_ROLLING_AVG_15,SPD_ROLLING_AVG_15,DIST_ROLLING_AVG_15,AST_PCT_ROLLING_AVG_15,NET_RATING_ROLLING_AVG_15,PIE_ROLLING_AVG_15,PLUS_MINUS_ROLLING_AVG_15,FANTASY_PTS_ROLLING_AVG_15,PTS_2ND_CHANCE_ROLLING_AVG_15,PTS_PAINT_ROLLING_AVG_15,OPP_PTS_PAINT_ROLLING_AVG_15,PFD_ROLLING_AVG_15,STL_ROLLING_AVG_15,BLK_ROLLING_AVG_15,TOV_ROLLING_AVG_15,PF_ROLLING_AVG_15,PTS_ROLLING_AVG_40,FGA_ROLLING_AVG_40,FG3A_ROLLING_AVG_40,FTM_ROLLING_AVG_40,FGM_ROLLING_AVG_40,FG3M_ROLLING_AVG_40,FG_PCT_ROLLING_AVG_40,EFG_PCT_ROLLING_AVG_40,TS_PCT_ROLLING_AVG_40,USG_PCT_ROLLING_AVG_40,E_USG_PCT_ROLLING_AVG_40,MIN_ROLLING_AVG_40,POSS_ROLLING_AVG_40,PACE_ROLLING_AVG_40,E_PACE_ROLLING_AVG_40,percentagePointsPaint_ROLLING_AVG_40,percentagePointsFreeThrow_ROLLING_AVG_40,percentageFieldGoalsAttempted2pt_ROLLING_AVG_40,percentageFieldGoalsAttempted3pt_ROLLING_AVG_40,percentagePoints2pt_ROLLING_AVG_40,percentagePoints3pt_ROLLING_AVG_40,percentagePointsMidrange2pt_ROLLING_AVG_40,percentageAssisted2pt_ROLLING_AVG_40,percentageAssisted3pt_ROLLING_AVG_40,percentageUnassisted3pt_ROLLING_AVG_40,percentageAssistedFGM_ROLLING_AVG_40,percentageUnassistedFGM_ROLLING_AVG_40,percentagePointsOffTurnovers_ROLLING_AVG_40,UFGA_ROLLING_AVG_40,DFGM_ROLLING_AVG_40,DFGA_ROLLING_AVG_40,ORBC_ROLLING_AVG_40,DRBC_ROLLING_AVG_40,RBC_ROLLING_AVG_40,DREB_PCT_ROLLING_AVG_40,SAST_ROLLING_AVG_40,CFGM_ROLLING_AVG_40,CFGA_ROLLING_AVG_40,SPD_ROLLING_AVG_40,DIST_ROLLING_AVG_40,AST_PCT_ROLLING_AVG_40,NET_RATING_ROLLING_AVG_40,PIE_ROLLING_AVG_40,PLUS_MINUS_ROLLING_AVG_40,FANTASY_PTS_ROLLING_AVG_40,PTS_2ND_CHANCE_ROLLING_AVG_40,PTS_PAINT_ROLLING_AVG_40,OPP_PTS_PAINT_ROLLING_AVG_40,PFD_ROLLING_AVG_40,STL_ROLLING_AVG_40,BLK_ROLLING_AVG_40,TOV_ROLLING_AVG_40,PF_ROLLING_AVG_40,GAMES_VS_OPP,MATCHUP_AVG_MIN_LAST_3_TO_DATE,MATCHUP_AVG_MIN_LAST_5_TO_DATE,MATCHUP_AVG_MIN_LAST_10_TO_DATE,MATCHUP_AVG_MIN_LAST_15_TO_DATE,MATCHUP_AVG_FGA_LAST_3_TO_DATE,MATCHUP_AVG_FGA_LAST_5_TO_DATE,MATCHUP_AVG_FGA_LAST_10_TO_DATE,MATCHUP_AVG_FGA_LAST_15_TO_DATE,MATCHUP_AVG_FG3A_LAST_3_TO_DATE,MATCHUP_AVG_FG3A_LAST_5_TO_DATE,MATCHUP_AVG_FG3A_LAST_10_TO_DATE,MATCHUP_AVG_FG3A_LAST_15_TO_DATE,MATCHUP_AVG_FTA_LAST_3_TO_DATE,MATCHUP_AVG_FTA_LAST_5_TO_DATE,MATCHUP_AVG_FTA_LAST_10_TO_DATE,MATCHUP_AVG_FTA_LAST_15_TO_DATE,MATCHUP_AVG_PTS_LAST_3_TO_DATE,MATCHUP_AVG_PTS_LAST_5_TO_DATE,MATCHUP_AVG_PTS_LAST_10_TO_DATE,MATCHUP_AVG_PTS_LAST_15_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_3_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_5_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_10_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_15_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_3_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_5_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_10_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_15_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_3_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_5_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_10_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_15_TO_DATE,MATCHUP_AVG_POSS_LAST_3_TO_DATE,MATCHUP_AVG_POSS_LAST_5_TO_DATE,MATCHUP_AVG_POSS_LAST_10_TO_DATE,MATCHUP_AVG_POSS_LAST_15_TO_DATE,MATCHUP_AVG_TCHS_LAST_3_TO_DATE,MATCHUP_AVG_TCHS_LAST_5_TO_DATE,MATCHUP_AVG_TCHS_LAST_10_TO_DATE,MATCHUP_AVG_TCHS_LAST_15_TO_DATE,MATCHUP_AVG_PASS_LAST_3_TO_DATE,MATCHUP_AVG_PASS_LAST_5_TO_DATE,MATCHUP_AVG_PASS_LAST_10_TO_DATE,MATCHUP_AVG_PASS_LAST_15_TO_DATE,MATCHUP_AVG_SAST_LAST_3_TO_DATE,MATCHUP_AVG_SAST_LAST_5_TO_DATE,MATCHUP_AVG_SAST_LAST_10_TO_DATE,MATCHUP_AVG_SAST_LAST_15_TO_DATE,MATCHUP_AVG_FTAST_LAST_3_TO_DATE,MATCHUP_AVG_FTAST_LAST_5_TO_DATE,MATCHUP_AVG_FTAST_LAST_10_TO_DATE,MATCHUP_AVG_FTAST_LAST_15_TO_DATE,MATCHUP_AVG_TOV_LAST_3_TO_DATE,MATCHUP_AVG_TOV_LAST_5_TO_DATE,MATCHUP_AVG_TOV_LAST_10_TO_DATE,MATCHUP_AVG_TOV_LAST_15_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_3_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_5_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_10_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_15_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_3_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_5_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_10_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_15_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_3_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_5_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_10_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_15_TO_DATE,MATCHUP_AVG_PIE_LAST_3_TO_DATE,MATCHUP_AVG_PIE_LAST_5_TO_DATE,MATCHUP_AVG_PIE_LAST_10_TO_DATE,MATCHUP_AVG_PIE_LAST_15_TO_DATE,MATCHUP_AVG_SPD_LAST_3_TO_DATE,MATCHUP_AVG_SPD_LAST_5_TO_DATE,MATCHUP_AVG_SPD_LAST_10_TO_DATE,MATCHUP_AVG_SPD_LAST_15_TO_DATE,MATCHUP_AVG_DIST_LAST_3_TO_DATE,MATCHUP_AVG_DIST_LAST_5_TO_DATE,MATCHUP_AVG_DIST_LAST_10_TO_DATE,MATCHUP_AVG_DIST_LAST_15_TO_DATE,PLAYER_HOME_AVG_PTS_TO_DATE,PLAYER_AWAY_AVG_PTS_TO_DATE,PLAYER_HOME_AVG_FGA_TO_DATE,PLAYER_AWAY_AVG_FGA_TO_DATE,PLAYER_HOME_AVG_FG3A_TO_DATE,PLAYER_AWAY_AVG_FG3A_TO_DATE,PLAYER_HOME_AVG_FTM_TO_DATE,PLAYER_AWAY_AVG_FTM_TO_DATE,PLAYER_HOME_AVG_FGM_TO_DATE,PLAYER_AWAY_AVG_FGM_TO_DATE,PLAYER_HOME_AVG_FG3M_TO_DATE,PLAYER_AWAY_AVG_FG3M_TO_DATE,PLAYER_HOME_AVG_FG_PCT_TO_DATE,PLAYER_AWAY_AVG_FG_PCT_TO_DATE,PLAYER_HOME_AVG_EFG_PCT_TO_DATE,PLAYER_AWAY_AVG_EFG_PCT_TO_DATE,PLAYER_HOME_AVG_TS_PCT_TO_DATE,PLAYER_AWAY_AVG_TS_PCT_TO_DATE,PLAYER_HOME_AVG_USG_PCT_TO_DATE,PLAYER_AWAY_AVG_USG_PCT_TO_DATE,PLAYER_HOME_AVG_E_USG_PCT_TO_DATE,PLAYER_AWAY_AVG_E_USG_PCT_TO_DATE,PLAYER_HOME_AVG_MIN_TO_DATE,PLAYER_AWAY_AVG_MIN_TO_DATE,PLAYER_HOME_AVG_POSS_TO_DATE,PLAYER_AWAY_AVG_POSS_TO_DATE,PLAYER_HOME_AVG_PACE_TO_DATE,PLAYER_AWAY_AVG_PACE_TO_DATE,PLAYER_HOME_AVG_E_PACE_TO_DATE,PLAYER_AWAY_AVG_E_PACE_TO_DATE,PLAYER_HOME_AVG_percentagePointsPaint_TO_DATE,PLAYER_AWAY_AVG_percentagePointsPaint_TO_DATE,PLAYER_HOME_AVG_percentagePointsFreeThrow_TO_DATE,PLAYER_AWAY_AVG_percentagePointsFreeThrow_TO_DATE,PLAYER_HOME_AVG_percentageFieldGoalsAttempted2pt_TO_DATE,PLAYER_AWAY_AVG_percentageFieldGoalsAttempted2pt_TO_DATE,PLAYER_HOME_AVG_percentageFieldGoalsAttempted3pt_TO_DATE,PLAYER_AWAY_AVG_percentageFieldGoalsAttempted3pt_TO_DATE,PLAYER_HOME_AVG_percentagePoints2pt_TO_DATE,PLAYER_AWAY_AVG_percentagePoints2pt_TO_DATE,PLAYER_HOME_AVG_percentagePoints3pt_TO_DATE,PLAYER_AWAY_AVG_percentagePoints3pt_TO_DATE,PLAYER_HOME_AVG_percentagePointsMidrange2pt_TO_DATE,PLAYER_AWAY_AVG_percentagePointsMidrange2pt_TO_DATE,PLAYER_HOME_AVG_percentageAssisted2pt_TO_DATE,PLAYER_AWAY_AVG_percentageAssisted2pt_TO_DATE,PLAYER_HOME_AVG_percentageAssisted3pt_TO_DATE,PLAYER_AWAY_AVG_percentageAssisted3pt_TO_DATE,PLAYER_HOME_AVG_percentageUnassisted3pt_TO_DATE,PLAYER_AWAY_AVG_percentageUnassisted3pt_TO_DATE,PLAYER_HOME_AVG_percentageAssistedFGM_TO_DATE,PLAYER_AWAY_AVG_percentageAssistedFGM_TO_DATE,PLAYER_HOME_AVG_percentageUnassistedFGM_TO_DATE,PLAYER_AWAY_AVG_percentageUnassistedFGM_TO_DATE,PLAYER_HOME_AVG_percentagePointsOffTurnovers_TO_DATE,PLAYER_AWAY_AVG_percentagePointsOffTurnovers_TO_DATE,PLAYER_HOME_AVG_UFGA_TO_DATE,PLAYER_AWAY_AVG_UFGA_TO_DATE,PLAYER_HOME_AVG_DFGM_TO_DATE,PLAYER_AWAY_AVG_DFGM_TO_DATE,PLAYER_HOME_AVG_DFGA_TO_DATE,PLAYER_AWAY_AVG_DFGA_TO_DATE,PLAYER_HOME_AVG_ORBC_TO_DATE,PLAYER_AWAY_AVG_ORBC_TO_DATE,PLAYER_HOME_AVG_DRBC_TO_DATE,PLAYER_AWAY_AVG_DRBC_TO_DATE,PLAYER_HOME_AVG_RBC_TO_DATE,PLAYER_AWAY_AVG_RBC_TO_DATE,PLAYER_HOME_AVG_DREB_PCT_TO_DATE,PLAYER_AWAY_AVG_DREB_PCT_TO_DATE,PLAYER_HOME_AVG_SAST_TO_DATE,PLAYER_AWAY_AVG_SAST_TO_DATE,PLAYER_HOME_AVG_CFGM_TO_DATE,PLAYER_AWAY_AVG_CFGM_TO_DATE,PLAYER_HOME_AVG_CFGA_TO_DATE,PLAYER_AWAY_AVG_CFGA_TO_DATE,PLAYER_HOME_AVG_SPD_TO_DATE,PLAYER_AWAY_AVG_SPD_TO_DATE,PLAYER_HOME_AVG_DIST_TO_DATE,PLAYER_AWAY_AVG_DIST_TO_DATE,PLAYER_HOME_AVG_AST_PCT_TO_DATE,PLAYER_AWAY_AVG_AST_PCT_TO_DATE,PLAYER_HOME_AVG_NET_RATING_TO_DATE,PLAYER_AWAY_AVG_NET_RATING_TO_DATE,PLAYER_HOME_AVG_PIE_TO_DATE,PLAYER_AWAY_AVG_PIE_TO_DATE,PLAYER_HOME_AVG_PLUS_MINUS_TO_DATE,PLAYER_AWAY_AVG_PLUS_MINUS_TO_DATE,PLAYER_HOME_AVG_FANTASY_PTS_TO_DATE,PLAYER_AWAY_AVG_FANTASY_PTS_TO_DATE,PLAYER_HOME_AVG_PTS_2ND_CHANCE_TO_DATE,PLAYER_AWAY_AVG_PTS_2ND_CHANCE_TO_DATE,PLAYER_HOME_AVG_PTS_PAINT_TO_DATE,PLAYER_AWAY_AVG_PTS_PAINT_TO_DATE,PLAYER_HOME_AVG_OPP_PTS_PAINT_TO_DATE,PLAYER_AWAY_AVG_OPP_PTS_PAINT_TO_DATE,PLAYER_HOME_AVG_PFD_TO_DATE,PLAYER_AWAY_AVG_PFD_TO_DATE,PLAYER_HOME_AVG_STL_TO_DATE,PLAYER_AWAY_AVG_STL_TO_DATE,PLAYER_HOME_AVG_BLK_TO_DATE,PLAYER_AWAY_AVG_BLK_TO_DATE,PLAYER_HOME_AVG_TOV_TO_DATE,PLAYER_AWAY_AVG_TOV_TO_DATE,PLAYER_HOME_AVG_PF_TO_DATE,PL

In [6]:
backtestData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/singleBookies.csv')
backtestData = backtestData[(backtestData['ODDS'] <= 200) & (backtestData['ODDS'] >= -200)]
singleBookies = backtestData[(backtestData['CATEGORY'] == 'points') & (backtestData['GAME_DATE'] == date)]
singleBookies

,NAME,CATEGORY,SIDE,BOOKMAKER,LINE,ODDS,fair_line,fair_odds,GAME_DATE
124606,Draymond Green,points,under,fanduel,10.5,-122,10.5,102,2025-03-11
124607,Draymond Green,points,under,draftkings,10.5,-110,10.5,102,2025-03-11
124608,Draymond Green,points,under,espnbet,10.5,-120,10.5,102,2025-03-11
124610,Draymond Green,points,under,betrivers,10.5,-113,10.5,102,2025-03-11
124616,Draymond Green,points,over,fanduel,10.5,-104,10.5,-102,2025-03-11
...,...,...,...,...,...,...,...,...,...
127136,Karlo Matković,points,over,espnbet,6.5,-105,6.5,106,2025-03-11
127137,Karlo Matković,points,over,draftkings,6.5,-105,6.5,106,2025-03-11
127144,Karlo Matković,points,under,betmgm,6.5,-125,6.5,-106,2025-03-11
127145,Karlo Matković,points,under,espnbet,6.5,-125,6.5,-106,2025-03-11
127146,Karlo Matković,points,under,draftkings,6.5,-125,6.5,-106,2025-03-11

### Top EVs for single bets

In [7]:
results = single_bet(
    data=df,
    bookmakers=singleBookies,
    model=model,
    features=features,
    stake=5,
    simulations=10000, 
    std_window=10,
    min_std=2.0,
    max_std=10.0
)
results.sort_values(by='EV%', ascending=False).head(10)

Processing single bets...

,NAME,BOOKMAKER,CATEGORY,LINE,ODDS,SIDE,PREDICTION,RECOMMENDATION,OVER%,UNDER%,IMPLIED PROB,EV%,KELLY FULL,KELLY HALF,KELLY QUARTER,CONFIDENCE INTERVAL
560,Taurean Prince,betmgm,points,17.5,100,under,6.003530,1,0.016,0.984,0.500,96.76,0.97,0.48,0.24,"(0.5, 16.5)"
637,Thomas Bryant,betmgm,points,11.5,-110,under,5.895394,1,0.069,0.931,0.524,77.74,0.86,0.43,0.21,"(0.7, 13.2)"
374,Javonte Green,betmgm,points,0.5,-120,over,1.891558,0,0.956,0.044,0.545,75.25,0.90,0.45,0.23,"(0.3, 18.2)"
741,Amir Coffey,draftkings,points,7.5,-110,over,10.458364,0,0.916,0.084,0.524,74.82,0.82,0.41,0.21,"(6.2, 14.6)"
739,Amir Coffey,espnbet,points,7.5,-110,over,10.458364,0,0.915,0.085,0.524,74.72,0.82,0.41,0.21,"(6.3, 14.6)"
742,Amir Coffey,fanduel,points,7.5,-110,over,10.458364,0,0.912,0.088,0.524,74.20,0.82,0.41,0.20,"(6.3, 14.6)"
409,Jalen Duren,betmgm,points,17.5,-115,under,10.001787,1,0.072,0.928,0.535,73.55,0.85,0.42,0.21,"(1.6, 19.9)"
270,Cameron Johnson,espnbet,points,12.5,115,over,16.579876,0,0.806,0.194,0.465,73.40,0.64,0.32,0.16,"(7.5, 25.7)"
116,Josh Hart,betmgm,points,21.5,-130,under,13.092574,1,0.020,0.980,0.565,73.31,0.95,0.48,0.24,"(5.1, 21.2)"
353,Trendon Watford,espnbet,points,4.5,105,over,8.336388,0,0.835,0.165,0.488,71.15,0.68,0.34,0.17,"(1.2, 16.8)"

### Top EVs for 2 leg bets

In [8]:
results = prizepickspairsEV(
    data=df,
    bookmakers=dfsData,
    model=model,
    features=features,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=2.0,
    max_std=10.0
)
results.sort_values(by='EV%', ascending=False).head(10).reset_index(drop=True)

Processing pairs...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,SIDE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,SIDE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
0,Ben Sheppard,player_points,prizepicks,-137,4.5,over,8.60,OVER,0.882,0.118,"(2.0, 15.7)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",OVER/UNDER,0,0.8749,1.625,0.812
1,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",Max Christie,player_points,prizepicks,-137,16.5,under,13.35,UNDER,0.129,0.871,"(7.8, 18.7)",UNDER/UNDER,0,0.8647,1.594,0.797
2,Deni Avdija,player_points,prizepicks,-137,15.5,under,20.12,OVER,0.867,0.133,"(11.9, 28.3)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",OVER/UNDER,1,0.8601,1.580,0.790
3,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",Julian Champagnie,player_points,prizepicks,-137,7.5,over,12.71,OVER,0.867,0.133,"(3.6, 22.0)",UNDER/OVER,1,0.8597,1.579,0.790
4,Ja Morant,player_points,prizepicks,-137,27.0,over,20.85,UNDER,0.141,0.859,"(9.6, 32.0)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",UNDER/UNDER,1,0.8525,1.557,0.779
5,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",Tari Eason,player_points,prizepicks,-137,13.5,over,10.00,UNDER,0.154,0.846,"(3.4, 16.8)",UNDER/UNDER,0,0.8398,1.519,0.760
6,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,7.5,under,4.72,UNDER,0.156,0.844,"(0.6, 10.1)",UNDER/UNDER,0,0.8378,1.513,0.757
7,AJ Green,player_points,prizepicks,-137,6.5,under,3.54,UNDER,0.180,0.820,"(0.3, 9.5)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",UNDER/UNDER,0,0.8137,1.441,0.721
8,Harrison Barnes,player_points,prizepicks,-137,11.0,over,18.24,OVER,0.818,0.182,"(3.3, 34.6)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",OVER/UNDER,1,0.8111,1.433,0.717
9,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.08,UNDER,0.008,0.992,"(1.1, 19.5)",Obi Toppin,player_points,prizepicks,-137,7.5,under,11.60,OVER,0.817,0.183,"(3.0, 20.5)",UNDER/OVER,0,0.8105,1.432,0.716

In [5]:
threeLeg = prizepicks3LegEV(
    data=df,
    bookmakers=dfsData,
    model=model,
    features=features,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=2.0,
    max_std=10.0
)
threeLeg.sort_values(by='EV%', ascending=False).head(10)

Processing 3-leg parlays...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,SIDE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,SIDE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,PLAYER 3,CATEGORY 3,BOOKMAKER 3,ODDS 3,LINE 3,SIDE 3,PREDICTION 3,MODEL_SIDE 3,OVER% 3,UNDER% 3,CONFIDENCE INTERVAL 3,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
105502,Ben Sheppard,player_points,prizepicks,-137,4.5,over,8.95,OVER,0.901,0.099,"(2.3, 16.0)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Paolo Banchero,player_points,prizepicks,-137,24.5,over,15.62,UNDER,0.096,0.904,"(3.3, 29.1)",OVER/UNDER/UNDER,0,0.8030,3.818,0.764
351546,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Max Christie,player_points,prizepicks,-137,16.5,under,13.39,UNDER,0.133,0.867,"(7.9, 18.9)",Paolo Banchero,player_points,prizepicks,-137,24.5,over,15.62,UNDER,0.096,0.904,"(3.3, 29.1)",UNDER/UNDER/UNDER,0,0.7726,3.636,0.727
105487,Ben Sheppard,player_points,prizepicks,-137,4.5,over,8.95,OVER,0.901,0.099,"(2.3, 16.0)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Max Christie,player_points,prizepicks,-137,16.5,under,13.39,UNDER,0.133,0.867,"(7.9, 18.9)",OVER/UNDER/UNDER,0,0.7697,3.618,0.724
352051,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Obi Toppin,player_points,prizepicks,-137,7.5,under,12.55,OVER,0.862,0.138,"(3.7, 21.7)",Paolo Banchero,player_points,prizepicks,-137,24.5,over,15.62,UNDER,0.096,0.904,"(3.3, 29.1)",UNDER/OVER/UNDER,1,0.7686,3.612,0.722
105500,Ben Sheppard,player_points,prizepicks,-137,4.5,over,8.95,OVER,0.901,0.099,"(2.3, 16.0)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Obi Toppin,player_points,prizepicks,-137,7.5,under,12.55,OVER,0.862,0.138,"(3.7, 21.7)",OVER/UNDER/OVER,0,0.7657,3.594,0.719
352117,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Paolo Banchero,player_points,prizepicks,-137,24.5,over,15.62,UNDER,0.096,0.904,"(3.3, 29.1)",Patrick Williams,player_points,prizepicks,-137,8.5,over,4.05,UNDER,0.147,0.853,"(0.3, 11.8)",UNDER/UNDER/UNDER,0,0.7608,3.565,0.713
350812,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,7.5,under,4.49,UNDER,0.147,0.853,"(0.5, 9.9)",Paolo Banchero,player_points,prizepicks,-137,24.5,over,15.62,UNDER,0.096,0.904,"(3.3, 29.1)",UNDER/UNDER/UNDER,0,0.7602,3.561,0.712
105505,Ben Sheppard,player_points,prizepicks,-137,4.5,over,8.95,OVER,0.901,0.099,"(2.3, 16.0)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Patrick Williams,player_points,prizepicks,-137,8.5,over,4.05,UNDER,0.147,0.853,"(0.3, 11.8)",OVER/UNDER/UNDER,0,0.7579,3.547,0.709
105473,Ben Sheppard,player_points,prizepicks,-137,4.5,over,8.95,OVER,0.901,0.099,"(2.3, 16.0)",Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Kentavious Caldwell-Pope,player_points,prizepicks,-137,7.5,under,4.49,UNDER,0.147,0.853,"(0.5, 9.9)",OVER/UNDER/UNDER,0,0.7574,3.544,0.709
350566,Jalen Williams,player_points,prizepicks,-137,21.5,over,9.85,UNDER,0.014,0.986,"(1.4, 20.2)",Julian Champagnie,player_points,prizepicks,-137,7.5,over,12.30,OVER,0.844,0.156,"(3.4, 21.6)",Paolo Banchero,player_points,prizepicks,-137,24.5,over,15.62,UNDER,0.096,0.904,"(3.3, 29.1)",UNDER/OVER/UNDER,1,0.7526,3.515,0.703