In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sys
import os


# feature_path = os.path.abspath(r"C:\Users\alexg\OneDrive\Documents\NBA-Prop-Predictor")
feature_path = os.path.abspath('/Users/alexg/Documents/Documents/Prize-Picks-Prop-Predictor')
if feature_path not in sys.path:
    sys.path.append(feature_path)

from FEATURE_ENGINEERING.features import *
from PROPS_EV.calculateEVS import *
from PROPS_EV.backtest import *

### Load Model

In [2]:
model = joblib.load('Models/xgbModel.pkl')
features = joblib.load('Models/top_features.pkl')

### Load Data

In [3]:
pd.set_option('display.max_columns', None)
eplison = 0.000001

s25 = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_25.csv')
s25['EXPECTED_USAGE_MIN'] = s25['USG_PCT_ROLLING_AVG_5'] * (s25['MIN_ROLLING_AVG_5'] + eplison)

s24 = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_24.csv')
s24['EXPECTED_USAGE_MIN'] = s24['USG_PCT_ROLLING_AVG_5'] * (s24['MIN_ROLLING_AVG_5'] + eplison)
df = pd.concat([s25, s24]).sort_values(by='GAME_DATE')


date = '2025-04-11'
df = df[df['GAME_DATE'] < date]

dfsData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/dfs_data.csv')
dfsData = dfsData[(dfsData['BOOKMAKER'] == 'prizepicks') & (dfsData['GAME_DATE'] == date) & (dfsData['CATEGORY'] == 'player_points')]
df.tail()

/var/folders/nw/9w4r5hrd05s122kt5hg_t8bw0000gn/T/ipykernel_44527/2323915385.py:15: DtypeWarning: Columns (11,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  dfsData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/dfs_data.csv')

,Unnamed: 0,Unnamed: 0.2,PLAYER_NAME,PLAYER_ID,MATCHUP,TEAM_ABBREVIATION,TEAM_ID,OPP_ABBREVIATION,HOME_GAME,GAME_ID,GAME_DATE,WL,PTS,AST,REB,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,STL,BLK,TOV,PLUS_MINUS,FANTASY_PTS,POINT_PER_SHOT,EFG,START_POSITION,COMMENT,E_OFF_RATING,E_DEF_RATING,NET_RATING,OREB_PCT,DREB_PCT,REB_PCT,AST_PCT,EFG_PCT,AST_TOV,USG_PCT,TS_PCT,E_PACE,PACE,PIE,POSS,PACE_PER40,E_USG_PCT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,DFGM,DFGA,DFG_PCT,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLKA,PF,PFD,IS_PLAYOFF,TEAM_SEASON_ID_x,whos_favored,spread,total,team_is_favored,team_spread,OPP_BLOWOUT_RISK,TEAM_NAME,TEAM_MIN,TEAM_FGM,TEAM_FGA,TEAM_FG_PCT,TEAM_FG3M,TEAM_FG3A,TEAM_FG3_PCT,TEAM_FTM,TEAM_FTA,TEAM_FT_PCT,TEAM_OREB,TEAM_DREB,TEAM_REB,TEAM_AST,TEAM_STL,TEAM_BLK,TEAM_TOV,TEAM_PF,TEAM_PTS,TEAM_PLUS_MINUS,TEAM_PACE,GAME_PACE,OPP_PACE,OPP_TEAM_ID,TEAM_OFF_RATING,TEAM_DEF_RATING,OPP_DEF_RATING,OPP_OFF_RATING,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,percentageFieldGoalsAttempted2pt,percentageFieldGoalsAttempted3pt,percentagePoints2pt,percentagePointsMidrange2pt,percentagePoints3pt,percentagePointsFastBreak,percentagePointsFreeThrow,percentagePointsOffTurnovers,percentagePointsPaint,percentageAssisted2pt,percentageUnassisted2pt,percentageAssisted3pt,percentageUnassisted3pt,percentageAssistedFGM,percentageUnassistedFGM,matchupFieldGoalsMade,matchupFieldGoalsAttempted,matchupThreePointersMade,matchupThreePointersAttempted,playerPoints,matchupMinutes,DEF_FG_PCT_ALLOWED,DEF_3PT_PCT_ALLOWED,PTS_ALLOWED_PER_MIN,AGE,FREQ_FG3,FG3M_main,FG3A_main,FG3_PCT_main,NS_FG3_PCT,PLUS_MINUS_FG3,FREQ_FG2,FG2M,FG2A,FG2_PCT,NS_FG2_PCT,PLUS_MINUS_FG2,FREQ_LT_06,FGM_LT_06,FGA_LT_06,LT_06_PCT,NS_LT_06_PCT,PLUS_MINUS_LT_06,FREQ_LT_10,FGM_LT_10,FGA_LT_10,LT_10_PCT,NS_LT_10_PCT,PLUS_MINUS_LT_10,FREQ_GT_15,FGM_GT_15,FGA_GT_15,GT_15_PCT,NS_GT_15_PCT,PLUS_MINUS_GT_15,DEF_TOV_FORCED_PER_MIN,DEF_BLOCKS_PER_MIN,DEF_SHOOTING_FOULS_PER_MIN,DEF_AST_ALLOWED_PER_MIN,STARTING,BLOWOUT_RISK,TEAM_IMPLIED_PTS_FAV,TEAM_IMPLIED_PTS_UND,HEIGHT,WEIGHT,GUARD,FORWARD,CENTER,TEAM_DAYS_REST,PLAYER_DAYS_REST,TEAM_B2B,IS_BACK_TO_BACK,PLAYER_MISSED_LAST,TEAM_GUARD_DEF_FG_PCT_ALLOWED,TEAM_GUARD_DEF_3PT_PCT_ALLOWED,TEAM_GUARD_PTS_ALLOWED_PER_MIN,TEAM_FORWARD_DEF_FG_PCT_ALLOWED,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED,TEAM_FORWARD_PTS_ALLOWED_PER_MIN,TEAM_CENTER_DEF_FG_PCT_ALLOWED,TEAM_CENTER_DEF_3PT_PCT_ALLOWED,TEAM_CENTER_PTS_ALLOWED_PER_MIN,OPP_GUARD_DEF_FG_PCT_ALLOWED,OPP_GUARD_DEF_3PT_PCT_ALLOWED,OPP_GUARD_PTS_ALLOWED_PER_MIN,OPP_FORWARD_DEF_FG_PCT_ALLOWED,OPP_FORWARD_DEF_3PT_PCT_ALLOWED,OPP_FORWARD_PTS_ALLOWED_PER_MIN,OPP_CENTER_DEF_FG_PCT_ALLOWED,OPP_CENTER_DEF_3PT_PCT_ALLOWED,OPP_CENTER_PTS_ALLOWED_PER_MIN,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,TEAM_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,TEAM_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,TEAM_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_GUARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_GUARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_GUARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_FORWARD_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_FORWARD_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_FORWARD_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_5,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_5,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_5,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_10,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_10,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_10,OPP_CENTER_DEF_FG_PCT_ALLOWED_ROLLING_AVG_15,OPP_CENTER_DEF_3PT_PCT_ALLOWED_ROLLING_AVG_15,OPP_CENTER_PTS_ALLOWED_PER_MIN_ROLLING_AVG_15,TEAM_GUARD_FREQ_FG3,TEAM_GUARD_FG3_PCT_main,TEAM_GUARD_NS_FG3_PCT,TEAM_GUARD_PLUS_MINUS_FG3,TEAM_GUARD_FREQ_FG2,TEAM_GUARD_FG2_PCT,TEAM_GUARD_NS_FG2_PCT,TEAM_GUARD_PLUS_MINUS_FG2,TEAM_GUARD_FREQ_LT_06,TEAM_GUARD_LT_06_PCT,TEAM_GUARD_NS_LT_06_PCT,TEAM_GUARD_PLUS_MINUS_LT_06,TEAM_GUARD_FREQ_LT_10,TEAM_GUARD_LT_10_PCT,TEAM_GUARD_NS_LT_10_PCT,TEAM_GUARD_PLUS_MINUS_LT_10,TEAM_GUARD_FREQ_GT_15,TEAM_GUARD_GT_15_PCT,TEAM_GUARD_NS_GT_15_PCT,TEAM_GUARD_PLUS_MINUS_GT_15,TEAM_FORWARD_FREQ_FG3,TEAM_FORWARD_FG3_PCT_main,TEAM_FORWARD_NS_FG3_PCT,TEAM_FORWARD_PLUS_MINUS_FG3,TEAM_FORWARD_FREQ_FG2,TEAM_FORWARD_FG2_PCT,TEAM_FORWARD_NS_FG2_PCT,TEAM_FORWARD_PLUS_MINUS_FG2,TEAM_FORWARD_FREQ_LT_06,TEAM_FORWARD_LT_06_PCT,TEAM_FORWARD_NS_LT_06_PCT,TEAM_FORWARD_PLUS_MINUS_LT_06,TEAM_FORWARD_FREQ_LT_10,TEAM_FORWARD_LT_10_PCT,TEAM_FORWARD_NS_LT_10_PCT,TEAM_FORWARD_PLUS_MINUS_LT_10,TEAM_FORWARD_FREQ_GT_15,TEAM_FORWARD_GT_15_PCT,TEAM_FORWARD_NS_GT_15_PCT,TEAM_FORWARD_PLUS_MINUS_GT_15,TEAM_CENTER_FREQ_FG3,TEAM_CENTER_FG3_PCT_main,TEAM_CENTER_NS_FG3_PCT,TEAM_CENTER_PLUS_MINUS_FG3,TEAM_CENTER_FREQ_FG2,TEAM_CENTER_FG2_PCT,TEAM_CENTER_NS_FG2_PCT,TEAM_CENTER_PLUS_MINUS_FG2,TEAM_CENTER_FREQ_LT_06,TEAM_CENTER_LT_06_PCT,TEAM_CENTER_NS_LT_06_PCT,TEAM_CENTER_PLUS_MINUS_LT_06,TEAM_CENTER_FREQ_LT_10,TEAM_CENTER_LT_10_PCT,TEAM_CENTER_NS_LT_10_PCT,TEAM_CENTER_PLUS_MINUS_LT_10,TEAM_CENTER_FREQ_GT_15,TEAM_CENTER_GT_15_PCT,TEAM_CENTER_NS_GT_15_PCT,TEAM_CENTER_PLUS_MINUS_GT_15,OPP_GUARD_FREQ_FG3,OPP_GUARD_FG3_PCT_main,OPP_GUARD_NS_FG3_PCT,OPP_GUARD_PLUS_MINUS_FG3,OPP_GUARD_FREQ_FG2,OPP_GUARD_FG2_PCT,OPP_GUARD_NS_FG2_PCT,OPP_GUARD_PLUS_MINUS_FG2,OPP_GUARD_FREQ_LT_06,OPP_GUARD_LT_06_PCT,OPP_GUARD_NS_LT_06_PCT,OPP_GUARD_PLUS_MINUS_LT_06,OPP_GUARD_FREQ_LT_10,OPP_GUARD_LT_10_PCT,OPP_GUARD_NS_LT_10_PCT,OPP_GUARD_PLUS_MINUS_LT_10,OPP_GUARD_FREQ_GT_15,OPP_GUARD_GT_15_PCT,OPP_GUARD_NS_GT_15_PCT,OPP_GUARD_PLUS_MINUS_GT_15,OPP_FORWARD_FREQ_FG3,OPP_FORWARD_FG3_PCT_main,OPP_FORWARD_NS_FG3_PCT,OPP_FORWARD_PLUS_MINUS_FG3,OPP_FORWARD_FREQ_FG2,OPP_FORWARD_FG2_PCT,OPP_FORWARD_NS_FG2_PCT,OPP_FORWARD_PLUS_MINUS_FG2,OPP_FORWARD_FREQ_LT_06,OPP_FORWARD_LT_06_PCT,OPP_FORWARD_NS_LT_06_PCT,OPP_FORWARD_PLUS_MINUS_LT_06,OPP_FORWARD_FREQ_LT_10,OPP_FORWARD_LT_10_PCT,OPP_FORWARD_NS_LT_10_PCT,OPP_FORWARD_PLUS_MINUS_LT_10,OPP_FORWARD_FREQ_GT_15,OPP_FORWARD_GT_15_PCT,OPP_FORWARD_NS_GT_15_PCT,OPP_FORWARD_PLUS_MINUS_GT_15,OPP_CENTER_FREQ_FG3,OPP_CENTER_FG3_PCT_main,OPP_CENTER_NS_FG3_PCT,OPP_CENTER_PLUS_MINUS_FG3,OPP_CENTER_FREQ_FG2,OPP_CENTER_FG2_PCT,OPP_CENTER_NS_FG2_PCT,OPP_CENTER_PLUS_MINUS_FG2,OPP_CENTER_FREQ_LT_06,OPP_CENTER_LT_06_PCT,OPP_CENTER_NS_LT_06_PCT,OPP_CENTER_PLUS_MINUS_LT_06,OPP_CENTER_FREQ_LT_10,OPP_CENTER_LT_10_PCT,OPP_CENTER_NS_LT_10_PCT,OPP_CENTER_PLUS_MINUS_LT_10,OPP_CENTER_FREQ_GT_15,OPP_CENTER_GT_15_PCT,OPP_CENTER_NS_GT_15_PCT,OPP_CENTER_PLUS_MINUS_GT_15,PTS_ROLLING_AVG_5,AST_ROLLING_AVG_5,REB_ROLLING_AVG_5,FGM_ROLLING_AVG_5,FGA_ROLLING_AVG_5,FG_PCT_ROLLING_AVG_5,FG3M_ROLLING_AVG_5,FG3A_ROLLING_AVG_5,FG3_PCT_ROLLING_AVG_5,FTM_ROLLING_AVG_5,FTA_ROLLING_AVG_5,FT_PCT_ROLLING_AVG_5,OREB_ROLLING_AVG_5,DREB_ROLLING_AVG_5,STL_ROLLING_AVG_5,BLK_ROLLING_AVG_5,TOV_ROLLING_AVG_5,PLUS_MINUS_ROLLING_AVG_5,FANTASY_PTS_ROLLING_AVG_5,POINT_PER_SHOT_ROLLING_AVG_5,EFG_ROLLING_AVG_5,E_OFF_RATING_ROLLING_AVG_5,E_DEF_RATING_ROLLING_AVG_5,NET_RATING_ROLLING_AVG_5,OREB_PCT_ROLLING_AVG_5,DREB_PCT_ROLLING_AVG_5,REB_PCT_ROLLING_AVG_5,AST_PCT_ROLLING_AVG_5,EFG_PCT_ROLLING_AVG_5,AST_TOV_ROLLING_AVG_5,USG_PCT_ROLLING_AVG_5,TS_PCT_ROLLING_AVG_5,E_PACE_ROLLING_AVG_5,PACE_ROLLING_AVG_5,PIE_ROLLING_AVG_5,POSS_ROLLING_AVG_5,PACE_PER40_ROLLING_AVG_5,E_USG_PCT_ROLLING_AVG_5,MIN_ROLLING_AVG_5,SPD_ROLLING_AVG_5,DIST_ROLLING_AVG_5,ORBC_ROLLING_AVG_5,DRBC_ROLLING_AVG_5,RBC_ROLLING_AVG_5,TCHS_ROLLING_AVG_5,SAST_ROLLING_AVG_5,FTAST_ROLLING_AVG_5,PASS_ROLLING_AVG_5,CFGM_ROLLING_AVG_5,CFGA_ROLLING_AVG_5,CFG_PCT_ROLLING_AVG_5,UFGM_ROLLING_AVG_5,UFGA_ROLLING_AVG_5,UFG_PCT_ROLLING_AVG_5,DFGM_ROLLING_AVG_5,DFGA_ROLLING_AVG_5,DFG_PCT_ROLLING_AVG_5,PTS_OFF_TOV_ROLLING_AVG_5,PTS_2ND_CHANCE_ROLLING_AVG_5,PTS_FB_ROLLING_AVG_5,PTS_PAINT_ROLLING_AVG_5,OPP_PTS_OFF_TOV_ROLLING_AVG_5,OPP_PTS_2ND_CHANCE_ROLLING_AVG_5,OPP_PTS_FB_ROLLING_AVG_5,OPP_PTS_PAINT_ROLLING_AVG_5,BLKA_ROLLING_AVG_5,PF_ROLLING_AVG_5,PFD_ROLLING_AVG_5,percentageFieldGoalsAttempted2pt_ROLLING_AVG_5,percentageFieldGoalsAttempted3pt_ROLLING_AVG_5,percentagePoints2pt_ROLLING_AVG_5,percentagePointsMidrange2pt_ROLLING_AVG_5,percentagePoints3pt_ROLLING_AVG_5,percentagePointsFastBreak_ROLLING_AVG_5,percentagePointsFreeThrow_ROLLING_AVG_5,percentagePointsOffTurnovers_ROLLING_AVG_5,percentagePointsPaint_ROLLING_AVG_5,percentageAssisted2pt_ROLLING_AVG_5,percentageUnassisted2pt_ROLLING_AVG_5,percentageAssisted3pt_ROLLING_AVG_5,percentageUnassisted3pt_ROLLING_AVG_5,percentageAssistedFGM_ROLLING_AVG_5,percentageUnassistedFGM_ROLLING_AVG_5,PTS_ROLLING_AVG_10,AST_ROLLING_AVG_10,REB_ROLLING_AVG_10,FGM_ROLLING_AVG_10,FGA_ROLLING_AVG_10,FG_PCT_ROLLING_AVG_10,FG3M_ROLLING_AVG_10,FG3A_ROLLING_AVG_10,FG3_PCT_ROLLING_AVG_10,FTM_ROLLING_AVG_10,FTA_ROLLING_AVG_10,FT_PCT_ROLLING_AVG_10,OREB_ROLLING_AVG_10,DREB_ROLLING_AVG_10,STL_ROLLING_AVG_10,BLK_ROLLING_AVG_10,TOV_ROLLING_AVG_10,PLUS_MINUS_ROLLING_AVG_10,FANTASY_PTS_ROLLING_AVG_10,POINT_PER_SHOT_ROLLING_AVG_10,EFG_ROLLING_AVG_10,E_OFF_RATING_ROLLING_AVG_10,E_DEF_RATING_ROLLING_AVG_10,NET_RATING_ROLLING_AVG_10,OREB_PCT_ROLLING_AVG_10,DREB_PCT_ROLLING_AVG_10,REB_PCT_ROLLING_AVG_10,AST_PCT_ROLLING_AVG_10,EFG_PCT_ROLLING_AVG_10,AST_TOV_ROLLING_AVG_10,USG_PCT_ROLLING_AVG_10,TS_PCT_ROLLING_AVG_10,E_PACE_ROLLING_AVG_10,PACE_ROLLING_AVG_10,PIE_ROLLING_AVG_10,POSS_ROLLING_AVG_10,PACE_PER40_ROLLING_AVG_10,E_USG_PCT_ROLLING_AVG_10,MIN_ROLLING_AVG_10,SPD_ROLLING_AVG_10,DIST_ROLLING_AVG_10,ORBC_ROLLING_AVG_10,DRBC_ROLLING_AVG_10,RBC_ROLLING_AVG_10,TCHS_ROLLING_AVG_10,SAST_ROLLING_AVG_10,FTAST_ROLLING_AVG_10,PASS_ROLLING_AVG_10,CFGM_ROLLING_AVG_10,CFGA_ROLLING_AVG_10,CFG_PCT_ROLLING_AVG_10,UFGM_ROLLING_AVG_10,UFGA_ROLLING_AVG_10,UFG_PCT_ROLLING_AVG_10,DFGM_ROLLING_AVG_10,DFGA_ROLLING_AVG_10,DFG_PCT_ROLLING_AVG_10,PTS_OFF_TOV_ROLLING_AVG_10,PTS_2ND_CHANCE_ROLLING_AVG_10,PTS_FB_ROLLING_AVG_10,PTS_PAINT_ROLLING_AVG_10,OPP_PTS_OFF_TOV_ROLLING_AVG_10,OPP_PTS_2ND_CHANCE_ROLLING_AVG_10,OPP_PTS_FB_ROLLING_AVG_10,OPP_PTS_PAINT_ROLLING_AVG_10,BLKA_ROLLING_AVG_10,PF_ROLLING_AVG_10,PFD_ROLLING_AVG_10,percentageFieldGoalsAttempted2pt_ROLLING_AVG_10,percentageFieldGoalsAttempted3pt_ROLLING_AVG_10,percentagePoints2pt_ROLLING_AVG_10,percentagePointsMidrange2pt_ROLLING_AVG_10,percentagePoints3pt_ROLLING_AVG_10,percentagePointsFastBreak_ROLLING_AVG_10,percentagePointsFreeThrow_ROLLING_AVG_10,percentagePointsOffTurnovers_ROLLING_AVG_10,percentagePointsPaint_ROLLING_AVG_10,percentageAssisted2pt_ROLLING_AVG_10,percentageUnassisted2pt_ROLLING_AVG_10,percentageAssisted3pt_ROLLING_AVG_10,percentageUnassisted3pt_ROLLING_AVG_10,percentageAssistedFGM_ROLLING_AVG_10,percentageUnassistedFGM_ROLLING_AVG_10,PTS_ROLLING_AVG_15,AST_ROLLING_AVG_15,REB_ROLLING_AVG_15,FGM_ROLLING_AVG_15,FGA_ROLLING_AVG_15,FG_PCT_ROLLING_AVG_15,FG3M_ROLLING_AVG_15,FG3A_ROLLING_AVG_15,FG3_PCT_ROLLING_AVG_15,FTM_ROLLING_AVG_15,FTA_ROLLING_AVG_15,FT_PCT_ROLLING_AVG_15,OREB_ROLLING_AVG_15,DREB_ROLLING_AVG_15,STL_ROLLING_AVG_15,BLK_ROLLING_AVG_15,TOV_ROLLING_AVG_15,PLUS_MINUS_ROLLING_AVG_15,FANTASY_PTS_ROLLING_AVG_15,POINT_PER_SHOT_ROLLING_AVG_15,EFG_ROLLING_AVG_15,E_OFF_RATING_ROLLING_AVG_15,E_DEF_RATING_ROLLING_AVG_15,NET_RATING_ROLLING_AVG_15,OREB_PCT_ROLLING_AVG_15,DREB_PCT_ROLLING_AVG_15,REB_PCT_ROLLING_AVG_15,AST_PCT_ROLLING_AVG_15,EFG_PCT_ROLLING_AVG_15,AST_TOV_ROLLING_AVG_15,USG_PCT_ROLLING_AVG_15,TS_PCT_ROLLING_AVG_15,E_PACE_ROLLING_AVG_15,PACE_ROLLING_AVG_15,PIE_ROLLING_AVG_15,POSS_ROLLING_AVG_15,PACE_PER40_ROLLING_AVG_15,E_USG_PCT_ROLLING_AVG_15,MIN_ROLLING_AVG_15,SPD_ROLLING_AVG_15,DIST_ROLLING_AVG_15,ORBC_ROLLING_AVG_15,DRBC_ROLLING_AVG_15,RBC_ROLLING_AVG_15,TCHS_ROLLING_AVG_15,SAST_ROLLING_AVG_15,FTAST_ROLLING_AVG_15,PASS_ROLLING_AVG_15,CFGM_ROLLING_AVG_15,CFGA_ROLLING_AVG_15,CFG_PCT_ROLLING_AVG_15,UFGM_ROLLING_AVG_15,UFGA_ROLLING_AVG_15,UFG_PCT_ROLLING_AVG_15,DFGM_ROLLING_AVG_15,DFGA_ROLLING_AVG_15,DFG_PCT_ROLLING_AVG_15,PTS_OFF_TOV_ROLLING_AVG_15,PTS_2ND_CHANCE_ROLLING_AVG_15,PTS_FB_ROLLING_AVG_15,PTS_PAINT_ROLLING_AVG_15,OPP_PTS_OFF_TOV_ROLLING_AVG_15,OPP_PTS_2ND_CHANCE_ROLLING_AVG_15,OPP_PTS_FB_ROLLING_AVG_15,OPP_PTS_PAINT_ROLLING_AVG_15,BLKA_ROLLING_AVG_15,PF_ROLLING_AVG_15,PFD_ROLLING_AVG_15,percentageFieldGoalsAttempted2pt_ROLLING_AVG_15,percentageFieldGoalsAttempted3pt_ROLLING_AVG_15,percentagePoints2pt_ROLLING_AVG_15,percentagePointsMidrange2pt_ROLLING_AVG_15,percentagePoints3pt_ROLLING_AVG_15,percentagePointsFastBreak_ROLLING_AVG_15,percentagePointsFreeThrow_ROLLING_AVG_15,percentagePointsOffTurnovers_ROLLING_AVG_15,percentagePointsPaint_ROLLING_AVG_15,percentageAssisted2pt_ROLLING_AVG_15,percentageUnassisted2pt_ROLLING_AVG_15,percentageAssisted3pt_ROLLING_AVG_15,percentageUnassisted3pt_ROLLING_AVG_15,percentageAssistedFGM_ROLLING_AVG_15,percentageUnassistedFGM_ROLLING_AVG_15,PTS_ROLLING_AVG_40,AST_ROLLING_AVG_40,REB_ROLLING_AVG_40,FGM_ROLLING_AVG_40,FGA_ROLLING_AVG_40,FG_PCT_ROLLING_AVG_40,FG3M_ROLLING_AVG_40,FG3A_ROLLING_AVG_40,FG3_PCT_ROLLING_AVG_40,FTM_ROLLING_AVG_40,FTA_ROLLING_AVG_40,FT_PCT_ROLLING_AVG_40,OREB_ROLLING_AVG_40,DREB_ROLLING_AVG_40,STL_ROLLING_AVG_40,BLK_ROLLING_AVG_40,TOV_ROLLING_AVG_40,PLUS_MINUS_ROLLING_AVG_40,FANTASY_PTS_ROLLING_AVG_40,POINT_PER_SHOT_ROLLING_AVG_40,EFG_ROLLING_AVG_40,E_OFF_RATING_ROLLING_AVG_40,E_DEF_RATING_ROLLING_AVG_40,NET_RATING_ROLLING_AVG_40,OREB_PCT_ROLLING_AVG_40,DREB_PCT_ROLLING_AVG_40,REB_PCT_ROLLING_AVG_40,AST_PCT_ROLLING_AVG_40,EFG_PCT_ROLLING_AVG_40,AST_TOV_ROLLING_AVG_40,USG_PCT_ROLLING_AVG_40,TS_PCT_ROLLING_AVG_40,E_PACE_ROLLING_AVG_40,PACE_ROLLING_AVG_40,PIE_ROLLING_AVG_40,POSS_ROLLING_AVG_40,PACE_PER40_ROLLING_AVG_40,E_USG_PCT_ROLLING_AVG_40,MIN_ROLLING_AVG_40,SPD_ROLLING_AVG_40,DIST_ROLLING_AVG_40,ORBC_ROLLING_AVG_40,DRBC_ROLLING_AVG_40,RBC_ROLLING_AVG_40,TCHS_ROLLING_AVG_40,SAST_ROLLING_AVG_40,FTAST_ROLLING_AVG_40,PASS_ROLLING_AVG_40,CFGM_ROLLING_AVG_40,CFGA_ROLLING_AVG_40,CFG_PCT_ROLLING_AVG_40,UFGM_ROLLING_AVG_40,UFGA_ROLLING_AVG_40,UFG_PCT_ROLLING_AVG_40,DFGM_ROLLING_AVG_40,DFGA_ROLLING_AVG_40,DFG_PCT_ROLLING_AVG_40,PTS_OFF_TOV_ROLLING_AVG_40,PTS_2ND_CHANCE_ROLLING_AVG_40,PTS_FB_ROLLING_AVG_40,PTS_PAINT_ROLLING_AVG_40,OPP_PTS_OFF_TOV_ROLLING_AVG_40,OPP_PTS_2ND_CHANCE_ROLLING_AVG_40,OPP_PTS_FB_ROLLING_AVG_40,OPP_PTS_PAINT_ROLLING_AVG_40,BLKA_ROLLING_AVG_40,PF_ROLLING_AVG_40,PFD_ROLLING_AVG_40,percentageFieldGoalsAttempted2pt_ROLLING_AVG_40,percentageFieldGoalsAttempted3pt_ROLLING_AVG_40,percentagePoints2pt_ROLLING_AVG_40,percentagePointsMidrange2pt_ROLLING_AVG_40,percentagePoints3pt_ROLLING_AVG_40,percentagePointsFastBreak_ROLLING_AVG_40,percentagePointsFreeThrow_ROLLING_AVG_40,percentagePointsOffTurnovers_ROLLING_AVG_40,percentagePointsPaint_ROLLING_AVG_40,percentageAssisted2pt_ROLLING_AVG_40,percentageUnassisted2pt_ROLLING_AVG_40,percentageAssisted3pt_ROLLING_AVG_40,percentageUnassisted3pt_ROLLING_AVG_40,percentageAssistedFGM_ROLLING_AVG_40,percentageUnassistedFGM_ROLLING_AVG_40,GAMES_VS_OPP,MATCHUP_AVG_MIN_LAST_3_TO_DATE,MATCHUP_AVG_FGA_LAST_3_TO_DATE,MATCHUP_AVG_FG3A_LAST_3_TO_DATE,MATCHUP_AVG_FTA_LAST_3_TO_DATE,MATCHUP_AVG_PTS_LAST_3_TO_DATE,MATCHUP_AVG_USG_PCT_LAST_3_TO_DATE,MATCHUP_AVG_EFG_PCT_LAST_3_TO_DATE,MATCHUP_AVG_TS_PCT_LAST_3_TO_DATE,MATCHUP_AVG_POSS_LAST_3_TO_DATE,MATCHUP_AVG_TCHS_LAST_3_TO_DATE,MATCHUP_AVG_PASS_LAST_3_TO_DATE,MATCHUP_AVG_SAST_LAST_3_TO_DATE,MATCHUP_AVG_FTAST_LAST_3_TO_DATE,MATCHUP_AVG_TOV_LAST_3_TO_DATE,MATCHUP_AVG_POINT_PER_SHOT_LAST_3_TO_DATE,MATCHUP_AVG_PLUS_MINUS_LAST_3_TO_DATE,MATCHUP_AVG_NET_RATING_LAST_3_TO_DATE,MATCHUP_AVG_PIE_LAST_3_TO_DATE,MATCHUP_AVG_SPD_LAST_3_TO_DATE,MATCHUP_AVG_DIST_LAST_3_TO_DATE,MATCHUP_AVG_percentageFieldGoalsAttempted3pt_LAST_3_TO_DATE,MATCHUP_AVG_percentageFieldGoalsAttempted2pt_LAST_3_TO_DATE,MATCHUP_AVG_percentagePoints2pt_LAST_3_TO_DATE,MATCHUP_AVG_percentagePointsMidrange2pt_LAST_3_TO_DATE,MATCHUP_AVG_percentagePoints3pt_LAST_3_TO_DATE,MATCHUP_AVG_percentagePointsFastBreak_LAST_3_TO_DATE,MATCHUP_AVG_percentagePointsFreeThrow_LAST_3_TO_DATE,MATCHUP_AVG_percentagePointsOffTurnovers_LAST_3_TO_DATE,MATCHUP_AVG_percentagePointsPaint_LAST_3_TO_DATE,MATCHUP_AVG_percentageAssisted2pt_LAST_3_TO_DATE,MATCHUP_AVG_percentageUnassisted2pt_LAST_3_TO_DATE,MATCHUP_AVG_percentageAssisted3pt_LAST_3_TO_DATE,MATCHUP_AVG_percentageUnassisted3pt_LAST_3_TO_DATE,PLAYER_HOME_AVG_PTS_TO_DATE,PLAYER_AWAY_AVG_PTS_TO_DATE,PLAYER_HOME_AVG_AST_TO_DATE,PLAYER_AWAY_AVG_AST_TO_DATE,PLAYER_HOME_AVG_REB_TO_DATE,PLAYER_AWAY_AVG_REB_TO_DATE,PLAYER_HOME_AVG_FGM_TO_DATE,PLAYER_AWAY_AVG_FGM_TO_DATE,PLAYER_HOME_AVG_FGA_TO_DATE,PLAYER_AWAY_AVG_FGA_TO_DATE,PLAYER_HOME_AVG_FG_PCT_TO_DATE,PLAYER_AWAY_AVG_FG_PCT_TO_DATE,PLAYER_HOME_AVG_FG3M_TO_DATE,PLAYER_AWAY_AVG_FG3M_TO_DATE,PLAYER_HOME_AVG_FG3A_TO_DATE,PLAYER_AWAY_AVG_FG3A_TO_DATE,PLAYER_HOME_AVG_FG3_PCT_TO_DATE,PLAYER_AWAY_AVG_FG3_PCT_TO_DATE,PLAYER_HOME_AVG_FTM_TO_DATE,PLAYER_AWAY_AVG_FTM_TO_DATE,PLAYER_HOME_AVG_FTA_TO_DATE,PLAYER_AWAY_AVG_FTA_TO_DATE,PLAYER_HOME_AVG_FT_PCT_TO_DATE,PLAYER_AWAY_AVG_FT_PCT_TO_DATE,PLAYER_HOME_AVG_OREB_TO_DATE,PLAYER_AWAY_AVG_OREB_TO_DATE,PLAYER_HOME_AVG_DREB_TO_DATE,PLAYER_AWAY_AVG_DREB_TO_DATE,PLAYER_HOME_AVG_STL_TO_DATE,PLAYER_AWAY_AVG_STL_TO_DATE,PLAYER_HOME_AVG_BLK_TO_DATE,PLAYER_AWAY_AVG_BLK_TO_DATE,PLAYER_HOME_AVG_TOV_TO_DATE,PLAYER_AWAY_AVG_TOV_TO_DATE,PLAYER_HOME_AVG_PLUS_MINUS_TO_DATE,PLAYER_AWAY_AVG_PLUS_MINUS_TO_DATE,PLAYER_HOME_AVG_FANTASY_PTS_TO_DATE,PLAYER_AWAY_AVG_FANTASY_PTS_TO_DATE,PLAYER_HOME_AVG_POINT_PER_SHOT_TO_DATE,PLAYER_AWAY_AVG_POINT_PER_SHOT_TO_DATE,PLAYER_HOME_AVG_EFG_TO_DATE,PLAYER_AWAY_AVG_EFG_TO_DATE,PLAYER_HOME_AVG_E_OFF_RATING_TO_DATE,PLAYER_AWAY_AVG_E_OFF_RATING_TO_DATE,PLAYER_HOME_AVG_E_DEF_RATING_TO_DATE,PLAYER_AWAY_AVG_E_DEF_RATING_TO_DATE,PLAYER_HOME_AVG_NET_RATING_TO_DATE,PLAYER_AWAY_AVG_NET_RATING_TO_DATE,PLAYER_HOME_AVG_OREB_PCT_TO_DATE,PLAYER_AWAY_AVG_OREB_PCT_TO_DATE,PLAYER_HOME_AVG_DREB_PCT_TO_DATE,PLAYER_AWAY_AVG_DREB_PCT_TO_DATE,PLAYER_HOME_AVG_REB_PCT_TO_DATE,PLAYER_AWAY_AVG_REB_PCT_TO_DATE,PLAYER_HOME_AVG_AST_PCT_TO_DATE,PLAYER_AWAY_AVG_AST_PCT_TO_DATE,PLAYER_HOME_AVG_EFG_PCT_TO_DATE,PLAYER_AWAY_AVG_EFG_PCT_TO_DATE,PLAYER_HOME_AVG_AST_TOV_TO_DATE,PLAYER_AWAY_AVG_AST_TOV_TO_DATE,PLAYER_HOME_AVG_USG_PCT_TO_DATE,PLAYER_AWAY_AVG_USG_PCT_TO_DATE,PLAYER_HOME_AVG_TS_PCT_TO_DATE,PLAYER_AWAY_AVG_TS_PCT_TO_DATE,PLAYER_HOME_AVG_E_PACE_TO_DATE,PLAYER_AWAY_AVG_E_PACE_TO_DATE,PLAYER_HOME_AVG_PACE_TO_DATE,PLAYER_AWAY_AVG_PACE_TO_DATE,PLAYER_HOME_AVG_P

In [4]:
backtestData = pd.read_csv('../DATA/CSV_FILES/BACKTEST_DATA/singleBookies.csv')
backtestData = backtestData[(backtestData['ODDS'] <= 200) & (backtestData['ODDS'] >= -200)]
singleBookies = backtestData[(backtestData['CATEGORY'] == 'points') & (backtestData['GAME_DATE'] == date)]
singleBookies

,NAME,CATEGORY,SIDE,BOOKMAKER,LINE,ODDS,fair_line,fair_odds,GAME_DATE
228880,Jaren Jackson Jr,points,under,draftkings,19.5,-105,19.5,-101,2025-04-11
228882,Jaren Jackson Jr,points,under,betrivers,19.5,-117,19.5,-101,2025-04-11
228885,Jaren Jackson Jr,points,over,draftkings,19.5,-125,19.5,101,2025-04-11
228887,Jaren Jackson Jr,points,over,betrivers,19.5,-114,19.5,101,2025-04-11
228903,Nickeil Alexander-Walker,points,over,fanduel,10.5,-130,10.5,-123,2025-04-11
...,...,...,...,...,...,...,...,...,...
234562,Jordan Goodwin,points,under,betmgm,3.5,-135,3.5,-115,2025-04-11
234571,Jeff Green,points,over,espnbet,7.5,-130,8.5,120,2025-04-11
234572,Jeff Green,points,under,espnbet,7.5,-110,8.5,-120,2025-04-11
234573,Jeff Green,points,over,espnbet,1.5,-130,1.5,-105,2025-04-11
234574,Jeff Green,points,under,espnbet,1.5,100,1.5,105,2025-04-11

### Top EVs for single bets

In [5]:
results = single_bet(
    data=df,
    bookmakers=singleBookies,
    model=model,
    features=features,
    stake=5,
    simulations=5000
)
results.sort_values(by='EV%', ascending=False).head(10)

Processing single bets...

,NAME,BOOKMAKER,CATEGORY,LINE,ODDS,SIDE,PREDICTION,RECOMMENDATION,OVER%,UNDER%,IMPLIED PROB,EV%,KELLY FULL,KELLY HALF,KELLY QUARTER,CONFIDENCE INTERVAL
1119,Aaron Gordon,fanduel,points,32.5,154,under,17.462973,1,0.003,0.997,0.394,153.14,0.99,0.50,0.25,"(7.2, 27.7)"
1673,Jalen Green,betmgm,points,14.5,185,over,22.060591,1,0.865,0.135,0.351,146.53,0.79,0.40,0.20,"(8.7, 35.3)"
1397,Oso Ighodaro,espnbet,points,2.5,160,over,7.245047,1,0.908,0.092,0.385,135.98,0.85,0.42,0.21,"(0.9, 15.3)"
835,Kyle Anderson,espnbet,points,0.5,135,over,6.132473,1,0.991,0.009,0.426,132.98,0.99,0.49,0.25,"(1.1, 12.0)"
469,Jrue Holiday,fanduel,points,3.5,130,over,14.400353,1,1.000,0.000,0.435,129.91,1.00,0.50,0.25,"(8.1, 20.7)"
1121,Aaron Gordon,espnbet,points,32.5,130,under,17.462973,1,0.001,0.999,0.435,129.72,1.00,0.50,0.25,"(7.2, 28.0)"
475,Derrick White,fanduel,points,3.5,132,over,18.329044,1,0.973,0.027,0.431,125.83,0.95,0.48,0.24,"(3.4, 35.0)"
1336,Jaden Springer,espnbet,points,2.5,125,over,13.075449,1,0.996,0.004,0.444,124.14,0.99,0.50,0.25,"(5.4, 20.6)"
300,Anthony Black,espnbet,points,2.5,130,over,9.641301,1,0.974,0.026,0.435,124.11,0.95,0.48,0.24,"(2.4, 17.1)"
714,Kevin Huerter,fanduel,points,3.5,132,over,16.600399,1,0.963,0.037,0.431,123.32,0.93,0.47,0.23,"(2.5, 33.1)"

### Top EVs for 2 leg bets

In [6]:
results = prizepickspairsEV(
    data=df,
    bookmakers=dfsData,
    model=model,
    features=features,
    stake=100,
    simulations=10000
)
results.sort_values(by='EV%', ascending=False).head(10).reset_index(drop=True)

Processing pairs...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,SIDE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,SIDE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY,KELLY FULL
0,Adem Bona,player_points,prizepicks,-137,13.5,over,10.85,UNDER,0.093,0.907,"(6.9, 14.8)",Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",UNDER/OVER,0,0.8442,1.533,0.766,0.766
1,Goga Bitadze,player_points,prizepicks,-137,12.5,over,4.75,UNDER,0.102,0.898,"(0.4, 16.3)",Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",UNDER/OVER,1,0.8362,1.509,0.754,0.754
2,Cory Joseph,player_points,prizepicks,-137,8.0,over,5.50,UNDER,0.108,0.892,"(1.6, 9.3)",Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",UNDER/OVER,0,0.8304,1.491,0.746,0.746
3,Adem Bona,player_points,prizepicks,-137,13.5,over,10.85,UNDER,0.093,0.907,"(6.9, 14.8)",Goga Bitadze,player_points,prizepicks,-137,12.5,over,4.75,UNDER,0.102,0.898,"(0.4, 16.3)",UNDER/UNDER,0,0.8145,1.443,0.722,0.722
4,Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",Karlo Matković,player_points,prizepicks,-137,14.5,over,12.26,UNDER,0.130,0.870,"(8.3, 16.2)",OVER/UNDER,0,0.8103,1.431,0.716,0.716
5,Adem Bona,player_points,prizepicks,-137,13.5,over,10.85,UNDER,0.093,0.907,"(6.9, 14.8)",Cory Joseph,player_points,prizepicks,-137,8.0,over,5.50,UNDER,0.108,0.892,"(1.6, 9.3)",UNDER/UNDER,0,0.8088,1.426,0.713,0.713
6,Adem Bona,player_points,prizepicks,-137,13.5,over,10.85,UNDER,0.093,0.907,"(6.9, 14.8)",Al Horford,player_points,prizepicks,-137,9.0,over,13.77,OVER,0.883,0.117,"(5.8, 21.8)",UNDER/OVER,0,0.8008,1.402,0.701,0.701
7,Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",Mike Conley,player_points,prizepicks,-137,7.5,over,11.32,OVER,0.859,0.141,"(4.4, 18.1)",OVER/OVER,0,0.7998,1.399,0.700,0.700
8,Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",Lonnie Walker IV,player_points,prizepicks,-137,20.0,over,14.60,UNDER,0.146,0.854,"(4.7, 24.6)",OVER/UNDER,1,0.7954,1.386,0.693,0.693
9,Jrue Holiday,player_points,prizepicks,-137,9.5,over,14.40,OVER,0.931,0.069,"(8.1, 20.6)",Quentin Grimes,player_points,prizepicks,-137,24.5,over,20.02,UNDER,0.146,0.854,"(11.5, 28.6)",OVER/UNDER,0,0.7952,1.386,0.693,0.693