In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sys
import os

project_root = os.path.dirname(os.path.abspath(''))
if project_root not in sys.path:
    sys.path.append(project_root)

from FEATURES.features import *
from PROPS_EV.calculateEVS import *
from BACKTEST.backtest import *
from MODELS.pipeline import *

### Load Model

In [ ]:
# PTSmodel = joblib.load('Models/xgbPTSModel.pkl')
# PTSfeatures = joblib.load('Models/topPTSfeatures.pkl')
# REBmodel = joblib.load('Models/xgbREBModel.pkl')
# REBfeatures = joblib.load('Models/topREBfeatures.pkl')

### Load Data

In [2]:
pd.set_option('display.max_columns', None)


s25_pts = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_25.csv')
s24_pts = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/PTS_TRAIN_24.csv')
# s25_reb = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/REB_TRAIN_25.csv')
# s24_reb = pd.read_csv('../DATA/CSV_FILES/TRAIN_DATA/REB_TRAIN_24.csv')

dfPTS = pd.concat([s25_pts, s24_pts]).sort_values(by='GAME_DATE')
# dfREB = pd.concat([s25_reb, s24_reb]).sort_values(by='GAME_DATE')


# date = '2025-02-12'
# dfPTS = dfPTS[dfPTS['GAME_DATE'] < date]
# dfREB = dfREB[dfREB['GAME_DATE'] < date]


# usData = pd.read_csv('../DATA/CSV_FILES/PROP_DATA/PLAYER_LINES/NBA_US_20251014.csv')
# singlePTSBookies = usData[usData['CATEGORY'] == 'player_points']


# dfsData = pd.read_csv('../DATA/CSV_FILES/PROP_DATA/PLAYER_LINES/NBA_DFS_20251016.csv')
# dfsPTS = dfsData[(dfsData['BOOKMAKER'] == 'Underdog') & (dfsData['CATEGORY'] == 'player_points')]
# dfsREB = dfsData[(dfsData['BOOKMAKER'] == 'PrizePicks') & (dfsData['CATEGORY'] == 'player_rebounds')]
# dfsPTS.rename(columns={'OVER/UNDER':'SIDE'}, inplace=True)
# dfsREB.rename(columns={'OVER/UNDER':'SIDE'}, inplace=True)

In [3]:
buildVector('Austin Reaves', dfPTS, '2025-10-21')

[[1, 1, 0, 0, 4, 0, 193],
 [np.float64(21.85),
  np.float64(24.87),
  np.float64(13.86),
  np.float64(7.826700002100001),
  np.float64(23.1),
  np.float64(22.16),
  np.float64(16.709500000000002),
  np.float64(14.6),
  np.float64(14.0),
  np.float64(9.0),
  np.float64(19.43),
  np.float64(7.09),
  np.float64(20.14),
  np.float64(0.22),
  np.float64(11.53),
  np.float64(10.0),
  np.float64(25.9095),
  np.float64(0.24),
  np.float64(0.23),
  np.float64(0.24),
  np.float64(14.72)],
 [np.float64(112.0),
  np.float64(100.07),
  np.float64(116.4),
  np.float64(100.8),
  np.float64(22.0),
  np.float64(0.0),
  np.float64(0.0)],
 [np.float64(107.74),
  np.float64(99.85),
  np.float64(9.52),
  np.float64(62.16597999999999),
  np.float64(24.7802)],
 [np.float64(0.34),
  np.float64(0.34),
  np.float64(4.73),
  np.float64(0.11),
  np.float64(0.183),
  np.float64(0.42),
  np.float64(4.43)],
 [np.float64(0.34)],
 [np.float64(5.0), np.float64(8.68)]]

### Top EVs for single bets

In [6]:
results = single_bet(
    data=dfPTS,
    bookmakers=singlePTSBookies,
    model=PTSmodel,
    features=PTSfeatures,
    edge_threshold=4.5,
    stake=5,
    simulations=10000, 
    std_window=10,
    min_std=2.0,
    max_std=10.0,
    stat_col='PTS'
)
results.sort_values(by='EV%', ascending=False).head(10)

Processing single bets...

,NAME,BOOKMAKER,CATEGORY,LINE,ODDS,SIDE,PREDICTION,RECOMMENDATION,OVER%,UNDER%,IMPLIED PROB,EV%,KELLY FULL,KELLY HALF,KELLY QUARTER,CONFIDENCE INTERVAL
1621,Toumani Camara,betmgm,points,5.5,125,over,15.211010,1,0.997,0.003,0.444,124.30,0.99,0.50,0.25,"(8.6, 22.0)"
1540,Steven Adams,betmgm,points,2.5,125,over,5.820261,0,0.949,0.051,0.444,113.50,0.91,0.45,0.23,"(1.8, 9.7)"
1417,Jalen Green,draftkings,points,22.5,135,under,14.470527,1,0.128,0.872,0.426,105.01,0.78,0.39,0.19,"(2.6, 28.1)"
382,DaQuan Jeffries,betmgm,points,2.5,110,over,6.335608,0,0.973,0.027,0.476,104.37,0.95,0.47,0.24,"(2.5, 10.3)"
1541,Steven Adams,espnbet,points,2.5,110,over,5.820261,0,0.950,0.050,0.476,99.52,0.90,0.45,0.23,"(1.9, 9.8)"
1679,Zeke Nnaji,draftkings,points,12.5,100,under,5.575228,1,0.016,0.984,0.500,96.84,0.97,0.48,0.24,"(0.7, 11.9)"
1426,Alperen Sengun,espnbet,points,19.5,-110,under,7.601803,1,0.001,0.999,0.524,90.76,1.00,0.50,0.25,"(1.2, 15.1)"
1389,Jaylin Williams,draftkings,points,5.5,-105,over,10.058649,1,0.974,0.026,0.512,90.24,0.95,0.47,0.24,"(5.5, 14.6)"
1390,Jaylin Williams,betmgm,points,4.5,-110,over,10.058649,1,0.993,0.007,0.524,89.48,0.98,0.49,0.25,"(5.6, 14.5)"
441,Bilal Coulibaly,betmgm,points,7.5,105,over,14.761505,1,0.912,0.088,0.488,86.90,0.83,0.41,0.21,"(4.6, 25.4)"

In [7]:
results = single_bet(
    data=dfREB,
    bookmakers=singleREBBookies,
    model=REBmodel,
    features=REBfeatures,
    edge_threshold=2.0,
    stake=5,
    simulations=10000, 
    std_window=10,
    min_std=1.5,
    max_std=6.5,
    stat_col='REB'
)
results.sort_values(by='EV%', ascending=False).head(10)

Processing single bets...

,NAME,BOOKMAKER,CATEGORY,LINE,ODDS,SIDE,PREDICTION,RECOMMENDATION,OVER%,UNDER%,IMPLIED PROB,EV%,KELLY FULL,KELLY HALF,KELLY QUARTER,CONFIDENCE INTERVAL
412,Thomas Bryant,betmgm,rebounds,10.5,125,under,5.142313,1,0.006,0.994,0.444,123.74,0.99,0.49,0.25,"(1.4, 9.2)"
1531,Kris Murray,betmgm,rebounds,4.5,135,under,1.732772,1,0.101,0.899,0.426,111.24,0.82,0.41,0.21,"(0.1, 6.0)"
1448,Donovan Clingan,espnbet,rebounds,9.5,105,under,3.203625,1,0.002,0.998,0.488,104.61,1.00,0.50,0.25,"(0.3, 7.4)"
1555,Zeke Nnaji,espnbet,rebounds,5.5,115,under,2.452899,1,0.069,0.931,0.465,100.12,0.87,0.44,0.22,"(0.2, 6.4)"
1726,Olivier-Maxence Prosper,fanduel,rebounds,8.5,100,under,1.889173,1,0.001,0.999,0.500,99.88,1.00,0.50,0.25,"(0.2, 6.0)"
1557,Zeke Nnaji,fanduel,rebounds,5.5,112,under,2.452899,1,0.073,0.927,0.472,96.59,0.86,0.43,0.22,"(0.2, 6.5)"
1450,Donovan Clingan,betmgm,rebounds,9.5,-105,under,3.203625,1,0.002,0.998,0.512,94.89,1.00,0.50,0.25,"(0.3, 7.5)"
229,Keldon Johnson,draftkings,rebounds,2.5,150,over,4.210320,0,0.777,0.223,0.400,94.25,0.63,0.31,0.16,"(0.5, 9.7)"
1156,Bobby Portis,betmgm,rebounds,6.5,115,over,9.395657,1,0.903,0.097,0.465,94.10,0.82,0.41,0.20,"(5.0, 13.7)"
409,Thomas Bryant,espnbet,rebounds,8.5,105,under,5.142313,1,0.053,0.947,0.488,94.07,0.90,0.45,0.22,"(1.3, 9.2)"

### Top EVs for 2 leg bets

In [13]:
results = prizepickspairsEV(
    data=dfPTS,
    bookmakers=dfsPTS,
    model=PTSmodel,
    features=PTSfeatures,
    edge_threshold=5,
    stake=100,
    simulations=1000,
    std_window=15,
    min_std=2.0,
    max_std=10.0,
    stat_col='PTS'
)
results.sort_values(by='EV%', ascending=False).head(10).reset_index(drop=True)

Processing pairs...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
0,Jarrett Allen,player_points,Underdog,-137,12.5,3.64,UNDER,0.050,0.950,"(0.0, 13.3)",Quentin Grimes,player_points,Underdog,-137,13.5,20.43,OVER,0.950,0.050,"(12.1, 28.4)",UNDER/OVER,1,0.9025,1.708,0.854
1,Jarrett Allen,player_points,Underdog,-137,12.5,3.64,UNDER,0.050,0.950,"(0.0, 13.3)",Trey Murphy III,player_points,Underdog,-137,19.5,1.02,UNDER,0.050,0.950,"(0.0, 15.7)",UNDER/UNDER,1,0.9025,1.708,0.854
2,Quentin Grimes,player_points,Underdog,-137,13.5,20.43,OVER,0.950,0.050,"(12.1, 28.4)",Trey Murphy III,player_points,Underdog,-137,19.5,1.02,UNDER,0.050,0.950,"(0.0, 15.7)",OVER/UNDER,1,0.9025,1.708,0.854
3,James Harden,player_points,Underdog,-137,20.5,28.20,OVER,0.917,0.083,"(17.7, 40.2)",Trey Murphy III,player_points,Underdog,-137,19.5,1.02,UNDER,0.050,0.950,"(0.0, 15.7)",OVER/UNDER,1,0.8711,1.613,0.807
4,James Harden,player_points,Underdog,-137,20.5,28.20,OVER,0.917,0.083,"(17.7, 40.2)",Quentin Grimes,player_points,Underdog,-137,13.5,20.43,OVER,0.950,0.050,"(12.1, 28.4)",OVER/OVER,1,0.8711,1.613,0.807
5,James Harden,player_points,Underdog,-137,20.5,28.20,OVER,0.917,0.083,"(17.7, 40.2)",Jarrett Allen,player_points,Underdog,-137,12.5,3.64,UNDER,0.050,0.950,"(0.0, 13.3)",OVER/UNDER,1,0.8711,1.613,0.807
6,Jarrett Allen,player_points,Underdog,-137,12.5,3.64,UNDER,0.050,0.950,"(0.0, 13.3)",Mikal Bridges,player_points,Underdog,-137,15.5,3.92,UNDER,0.086,0.914,"(0.0, 19.2)",UNDER/UNDER,1,0.8683,1.605,0.802
7,Mikal Bridges,player_points,Underdog,-137,15.5,3.92,UNDER,0.086,0.914,"(0.0, 19.2)",Quentin Grimes,player_points,Underdog,-137,13.5,20.43,OVER,0.950,0.050,"(12.1, 28.4)",UNDER/OVER,1,0.8683,1.605,0.802
8,Mikal Bridges,player_points,Underdog,-137,15.5,3.92,UNDER,0.086,0.914,"(0.0, 19.2)",Trey Murphy III,player_points,Underdog,-137,19.5,1.02,UNDER,0.050,0.950,"(0.0, 15.7)",UNDER/UNDER,1,0.8683,1.605,0.802
9,Josh Hart,player_points,Underdog,-137,9.5,13.89,OVER,0.892,0.108,"(7.0, 21.0)",Quentin Grimes,player_points,Underdog,-137,13.5,20.43,OVER,0.950,0.050,"(12.1, 28.4)",OVER/OVER,0,0.8474,1.542,0.771

In [8]:
results = prizepickspairsEV(
    data=dfREB,
    bookmakers=dfsREB,
    model=REBmodel,
    features=REBfeatures,
    edge_threshold=2.0,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=1.5,
    max_std=6.5,
    stat_col='REB'
)
results.sort_values(by='EV%', ascending=False).head(10).reset_index(drop=True)

Processing pairs...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
0,Immanuel Quickley,player_rebounds,PrizePicks,-137,3.5,5.32,OVER,0.779,0.221,"(0.5, 10.0)",Jalen Johnson,player_rebounds,PrizePicks,-137,9.5,6.81,UNDER,0.176,0.824,"(1.3, 12.3)",OVER/UNDER,0,0.6417,0.925,0.463
1,De'Andre Hunter,player_rebounds,PrizePicks,-137,3.5,4.80,OVER,0.738,0.262,"(0.9, 8.7)",Jalen Johnson,player_rebounds,PrizePicks,-137,9.5,6.81,UNDER,0.176,0.824,"(1.3, 12.3)",OVER/UNDER,0,0.6083,0.825,0.412
2,Jalen Johnson,player_rebounds,PrizePicks,-137,9.5,6.81,UNDER,0.176,0.824,"(1.3, 12.3)",Klay Thompson,player_rebounds,PrizePicks,-137,2.5,3.73,OVER,0.730,0.270,"(0.0, 7.7)",UNDER/OVER,0,0.6015,0.805,0.402
3,Jalen Johnson,player_rebounds,PrizePicks,-137,9.5,6.81,UNDER,0.176,0.824,"(1.3, 12.3)",Stephon Castle,player_rebounds,PrizePicks,-137,4.5,5.67,OVER,0.723,0.277,"(1.8, 9.6)",UNDER/OVER,0,0.5960,0.788,0.394
4,Jalen Johnson,player_rebounds,PrizePicks,-137,9.5,6.81,UNDER,0.176,0.824,"(1.3, 12.3)",Jalen Williams,player_rebounds,PrizePicks,-137,5.0,6.05,OVER,0.706,0.294,"(2.0, 10.2)",UNDER/OVER,0,0.5816,0.745,0.372
5,De'Andre Hunter,player_rebounds,PrizePicks,-137,3.5,4.80,OVER,0.738,0.262,"(0.9, 8.7)",Immanuel Quickley,player_rebounds,PrizePicks,-137,3.5,5.32,OVER,0.779,0.221,"(0.5, 10.0)",OVER/OVER,0,0.5746,0.724,0.362
6,Immanuel Quickley,player_rebounds,PrizePicks,-137,3.5,5.32,OVER,0.779,0.221,"(0.5, 10.0)",Klay Thompson,player_rebounds,PrizePicks,-137,2.5,3.73,OVER,0.730,0.270,"(0.0, 7.7)",OVER/OVER,0,0.5682,0.705,0.352
7,Jalen Johnson,player_rebounds,PrizePicks,-137,9.5,6.81,UNDER,0.176,0.824,"(1.3, 12.3)",Mitchell Robinson,player_rebounds,PrizePicks,-137,7.0,5.12,UNDER,0.312,0.688,"(0.0, 13.1)",UNDER/UNDER,0,0.5673,0.702,0.351
8,Immanuel Quickley,player_rebounds,PrizePicks,-137,3.5,5.32,OVER,0.779,0.221,"(0.5, 10.0)",Stephon Castle,player_rebounds,PrizePicks,-137,4.5,5.67,OVER,0.723,0.277,"(1.8, 9.6)",OVER/OVER,0,0.5630,0.689,0.345
9,Immanuel Quickley,player_rebounds,PrizePicks,-137,3.5,5.32,OVER,0.779,0.221,"(0.5, 10.0)",Jalen Williams,player_rebounds,PrizePicks,-137,5.0,6.05,OVER,0.706,0.294,"(2.0, 10.2)",OVER/OVER,0,0.5495,0.648,0.324

## 3 leg parlay

In [5]:
threeLeg = prizepicks3LegEV(
    data=dfPTS,
    bookmakers=dfsPTS,
    model=PTSmodel,
    features=PTSfeatures,
    edge_threshold=4.5,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=2.0,
    max_std=10.0,
    stat_col='PTS'
)
threeLeg.sort_values(by='EV%', ascending=False).head(10)

Processing 3-leg parlays...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,PLAYER 3,CATEGORY 3,BOOKMAKER 3,ODDS 3,LINE 3,PREDICTION 3,MODEL_SIDE 3,OVER% 3,UNDER% 3,CONFIDENCE INTERVAL 3,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
48555,Jarrett Allen,player_points,Underdog,-137,12.5,3.31,UNDER,0.066,0.934,"(0.3, 14.9)",Mikal Bridges,player_points,Underdog,-137,15.5,4.02,UNDER,0.043,0.957,"(0.4, 16.9)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",UNDER/UNDER/UNDER,1,0.8876,4.325,0.865
47994,James Harden,player_points,Underdog,-137,20.5,28.37,OVER,0.929,0.071,"(17.9, 38.5)",Mikal Bridges,player_points,Underdog,-137,15.5,4.02,UNDER,0.043,0.957,"(0.4, 16.9)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",OVER/UNDER/UNDER,1,0.8824,4.295,0.859
53206,Lauri Markkanen,player_points,Underdog,-137,21.5,14.34,UNDER,0.082,0.918,"(4.0, 24.4)",Mikal Bridges,player_points,Underdog,-137,15.5,4.02,UNDER,0.043,0.957,"(0.4, 16.9)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",UNDER/UNDER/UNDER,1,0.8728,4.237,0.847
51261,Julian Champagnie,player_points,Underdog,-137,10.5,16.91,OVER,0.913,0.087,"(7.8, 26.2)",Mikal Bridges,player_points,Underdog,-137,15.5,4.02,UNDER,0.043,0.957,"(0.4, 16.9)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",OVER/UNDER/UNDER,1,0.8675,4.205,0.841
47587,James Harden,player_points,Underdog,-137,20.5,28.37,OVER,0.929,0.071,"(17.9, 38.5)",Jarrett Allen,player_points,Underdog,-137,12.5,3.31,UNDER,0.066,0.934,"(0.3, 14.9)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",OVER/UNDER/UNDER,1,0.8615,4.169,0.834
53795,Mikal Bridges,player_points,Underdog,-137,15.5,4.02,UNDER,0.043,0.957,"(0.4, 16.9)",Quentin Grimes,player_points,Underdog,-137,13.5,19.09,OVER,0.906,0.094,"(10.8, 27.4)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",UNDER/OVER/UNDER,1,0.8610,4.166,0.833
48498,Jarrett Allen,player_points,Underdog,-137,12.5,3.31,UNDER,0.066,0.934,"(0.3, 14.9)",Lauri Markkanen,player_points,Underdog,-137,21.5,14.34,UNDER,0.082,0.918,"(4.0, 24.4)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",UNDER/UNDER/UNDER,1,0.8521,4.112,0.822
47937,James Harden,player_points,Underdog,-137,20.5,28.37,OVER,0.929,0.071,"(17.9, 38.5)",Lauri Markkanen,player_points,Underdog,-137,21.5,14.34,UNDER,0.082,0.918,"(4.0, 24.4)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",OVER/UNDER/UNDER,1,0.8471,4.083,0.817
48330,Jarrett Allen,player_points,Underdog,-137,12.5,3.31,UNDER,0.066,0.934,"(0.3, 14.9)",Julian Champagnie,player_points,Underdog,-137,10.5,16.91,OVER,0.913,0.087,"(7.8, 26.2)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",UNDER/OVER/UNDER,1,0.8469,4.082,0.816
20351,Bobby Portis,player_points,Underdog,-137,10.5,15.92,OVER,0.886,0.114,"(7.3, 24.4)",Mikal Bridges,player_points,Underdog,-137,15.5,4.02,UNDER,0.043,0.957,"(0.4, 16.9)",Trey Murphy III,player_points,Underdog,-137,19.5,1.55,UNDER,0.007,0.993,"(0.2, 16.3)",OVER/UNDER/UNDER,1,0.8422,4.053,0.811

In [12]:
threeLeg = prizepicks3LegEV(
    data=dfREB,
    bookmakers=dfsREB,
    model=REBmodel,
    features=REBfeatures,
    edge_threshold=2.0,
    stake=100,
    simulations=10000,
    std_window=10,
    min_std=1.5,
    max_std=6.5,
    stat_col='REB'
)
threeLeg.sort_values(by='EV%', ascending=False).head(10)

Processing 3-leg parlays...

,PLAYER 1,CATEGORY 1,BOOKMAKER 1,ODDS 1,LINE 1,PREDICTION 1,MODEL_SIDE 1,OVER% 1,UNDER% 1,CONFIDENCE INTERVAL 1,PLAYER 2,CATEGORY 2,BOOKMAKER 2,ODDS 2,LINE 2,PREDICTION 2,MODEL_SIDE 2,OVER% 2,UNDER% 2,CONFIDENCE INTERVAL 2,PLAYER 3,CATEGORY 3,BOOKMAKER 3,ODDS 3,LINE 3,PREDICTION 3,MODEL_SIDE 3,OVER% 3,UNDER% 3,CONFIDENCE INTERVAL 3,RECOMMENDED_TYPE,RECOMMENDATION,PROBABILITY,EV%,KELLY
7201,Josh Hart,player_rebounds,prizepicks,-137,9.5,7.59,UNDER,0.243,0.757,"(2.4, 12.9)",Precious Achiuwa,player_rebounds,prizepicks,-137,8.5,7.05,UNDER,0.234,0.766,"(3.1, 10.9)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",UNDER/UNDER/OVER,0,0.4678,1.807,0.361
8216,Pascal Siakam,player_rebounds,prizepicks,-137,7.5,5.85,UNDER,0.256,0.744,"(1.3, 10.7)",Precious Achiuwa,player_rebounds,prizepicks,-137,8.5,7.05,UNDER,0.234,0.766,"(3.1, 10.9)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",UNDER/UNDER/OVER,0,0.4596,1.757,0.351
8315,Precious Achiuwa,player_rebounds,prizepicks,-137,8.5,7.05,UNDER,0.234,0.766,"(3.1, 10.9)",Thomas Bryant,player_rebounds,prizepicks,-137,6.5,5.14,UNDER,0.259,0.741,"(1.3, 9.1)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",UNDER/UNDER/OVER,0,0.4576,1.746,0.349
6055,Jalen Duren,player_rebounds,prizepicks,-137,11.5,14.22,OVER,0.739,0.261,"(5.7, 22.8)",Precious Achiuwa,player_rebounds,prizepicks,-137,8.5,7.05,UNDER,0.234,0.766,"(3.1, 10.9)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",OVER/UNDER/OVER,0,0.4568,1.741,0.348
7177,Josh Hart,player_rebounds,prizepicks,-137,9.5,7.59,UNDER,0.243,0.757,"(2.4, 12.9)",Pascal Siakam,player_rebounds,prizepicks,-137,7.5,5.85,UNDER,0.256,0.744,"(1.3, 10.7)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",UNDER/UNDER/OVER,0,0.4543,1.726,0.345
5084,Immanuel Quickley,player_rebounds,prizepicks,-137,3.5,4.89,OVER,0.735,0.265,"(0.8, 9.6)",Precious Achiuwa,player_rebounds,prizepicks,-137,8.5,7.05,UNDER,0.234,0.766,"(3.1, 10.9)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",OVER/UNDER/OVER,0,0.4541,1.724,0.345
8306,Precious Achiuwa,player_rebounds,prizepicks,-137,8.5,7.05,UNDER,0.234,0.766,"(3.1, 10.9)",Santi Aldama,player_rebounds,prizepicks,-137,5.5,7.50,OVER,0.733,0.267,"(1.6, 14.3)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",UNDER/OVER/OVER,0,0.4531,1.719,0.344
7216,Josh Hart,player_rebounds,prizepicks,-137,9.5,7.59,UNDER,0.243,0.757,"(2.4, 12.9)",Thomas Bryant,player_rebounds,prizepicks,-137,6.5,5.14,UNDER,0.259,0.741,"(1.3, 9.1)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",UNDER/UNDER/OVER,0,0.4524,1.714,0.343
5887,Jalen Duren,player_rebounds,prizepicks,-137,11.5,14.22,OVER,0.739,0.261,"(5.7, 22.8)",Josh Hart,player_rebounds,prizepicks,-137,9.5,7.59,UNDER,0.243,0.757,"(2.4, 12.9)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",OVER/UNDER/OVER,0,0.4516,1.710,0.342
4916,Immanuel Quickley,player_rebounds,prizepicks,-137,3.5,4.89,OVER,0.735,0.265,"(0.8, 9.6)",Josh Hart,player_rebounds,prizepicks,-137,9.5,7.59,UNDER,0.243,0.757,"(2.4, 12.9)",Zach Edey,player_rebounds,prizepicks,-137,7.0,9.92,OVER,0.807,0.193,"(3.2, 16.6)",OVER/UNDER/OVER,0,0.4488,1.693,0.339